//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;

.visible .entry _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 .ptr .align 1 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 .ptr .align 1 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 .ptr .align 1 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 .ptr .align 1 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 .ptr .align 1 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 .ptr .align 1 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<43>;
	.reg .b32 	%r<117>;
	.reg .b64 	%rd<146>;

	ld.param.b64 	%rd6, [_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.b64 	%rd7, [_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.b64 	%rd8, [_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6];
	ld.param.b64 	%rd9, [_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.b64 	%rd10, [_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.b64 	%rd11, [_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.b64 	%rd14, [_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.b64 	%rd15, [_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	ld.param.b64 	%rd12, [_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.b64 	%rd13, [_ZN5task436_voroni_square_euclidean_fast_kernelB3v48B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	cvta.to.global.u64 	%rd1, %rd6;
	mov.u32 	%r3, %tid.x;
	cvt.u64.u32 	%rd16, %r3;
	mov.u32 	%r4, %ntid.x;
	mov.u32 	%r5, %ctaid.x;
	mul.wide.u32 	%rd17, %r4, %r5;
	add.s64 	%rd2, %rd17, %rd16;
	mov.u32 	%r6, %tid.y;
	mov.u32 	%r7, %ntid.y;
	mov.u32 	%r8, %ctaid.y;
	mad.lo.s32 	%r9, %r7, %r8, %r6;
	cvt.u64.u32 	%rd3, %r9;
	cvt.rn.f32.u64 	%r10, %rd2;
	cvt.rn.f32.u64 	%r11, %rd14;
	div.approx.ftz.f32 	%r1, %r10, %r11;
	cvt.rn.f32.u32 	%r12, %r9;
	cvt.rn.f32.s64 	%r13, %rd15;
	div.approx.ftz.f32 	%r2, %r12, %r13;
	setp.lt.u64 	%p1, %rd2, %rd14;
	setp.gt.s64 	%p2, %rd15, %rd3;
	and.pred 	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_11;
$L__BB0_1:
	ret;
$L__BB0_2:
	.pragma "nounroll";
	mul.lo.s64 	%rd22, %rd145, %rd9;
	add.s64 	%rd23, %rd1, %rd22;
	add.s64 	%rd24, %rd6, %rd22;
	ld.global.b32 	%r14, [%rd23];
	add.s64 	%rd25, %rd10, %rd24;
	ld.b32 	%r15, [%rd25];
	sub.ftz.f32 	%r16, %r1, %r14;
	sub.ftz.f32 	%r17, %r2, %r15;
	mul.ftz.f32 	%r18, %r17, %r17;
	fma.rn.ftz.f32 	%r19, %r16, %r16, %r18;
	setp.lt.ftz.f32 	%p8, %r19, %r115;
	selp.b64 	%rd26, %rd145, %rd144, %p8;
	selp.f32 	%r20, %r19, %r115, %p8;
	setp.gt.s64 	%p9, %rd142, 0;
	selp.b64 	%rd27, 1, 0, %p9;
	add.s64 	%rd28, %rd143, %rd27;
	selp.b64 	%rd29, -1, 0, %p9;
	add.s64 	%rd30, %rd142, %rd29;
	mul.lo.s64 	%rd31, %rd143, %rd9;
	add.s64 	%rd32, %rd1, %rd31;
	add.s64 	%rd33, %rd6, %rd31;
	ld.global.b32 	%r21, [%rd32];
	add.s64 	%rd34, %rd10, %rd33;
	ld.b32 	%r22, [%rd34];
	sub.ftz.f32 	%r23, %r1, %r21;
	sub.ftz.f32 	%r24, %r2, %r22;
	mul.ftz.f32 	%r25, %r24, %r24;
	fma.rn.ftz.f32 	%r26, %r23, %r23, %r25;
	setp.lt.ftz.f32 	%p10, %r26, %r20;
	selp.b64 	%rd35, %rd143, %rd26, %p10;
	selp.f32 	%r27, %r26, %r20, %p10;
	setp.gt.s64 	%p11, %rd30, 0;
	selp.b64 	%rd36, 1, 0, %p11;
	add.s64 	%rd37, %rd28, %rd36;
	selp.b64 	%rd38, -1, 0, %p11;
	add.s64 	%rd39, %rd30, %rd38;
	mul.lo.s64 	%rd40, %rd28, %rd9;
	add.s64 	%rd41, %rd1, %rd40;
	add.s64 	%rd42, %rd6, %rd40;
	ld.global.b32 	%r28, [%rd41];
	add.s64 	%rd43, %rd10, %rd42;
	ld.b32 	%r29, [%rd43];
	sub.ftz.f32 	%r30, %r1, %r28;
	sub.ftz.f32 	%r31, %r2, %r29;
	mul.ftz.f32 	%r32, %r31, %r31;
	fma.rn.ftz.f32 	%r33, %r30, %r30, %r32;
	setp.lt.ftz.f32 	%p12, %r33, %r27;
	selp.b64 	%rd44, %rd28, %rd35, %p12;
	selp.f32 	%r34, %r33, %r27, %p12;
	setp.gt.s64 	%p13, %rd39, 0;
	selp.b64 	%rd45, 1, 0, %p13;
	add.s64 	%rd46, %rd37, %rd45;
	selp.b64 	%rd47, -1, 0, %p13;
	add.s64 	%rd48, %rd39, %rd47;
	mul.lo.s64 	%rd49, %rd37, %rd9;
	add.s64 	%rd50, %rd1, %rd49;
	add.s64 	%rd51, %rd6, %rd49;
	ld.global.b32 	%r35, [%rd50];
	add.s64 	%rd52, %rd10, %rd51;
	ld.b32 	%r36, [%rd52];
	sub.ftz.f32 	%r37, %r1, %r35;
	sub.ftz.f32 	%r38, %r2, %r36;
	mul.ftz.f32 	%r39, %r38, %r38;
	fma.rn.ftz.f32 	%r40, %r37, %r37, %r39;
	setp.lt.ftz.f32 	%p14, %r40, %r34;
	selp.b64 	%rd53, %rd37, %rd44, %p14;
	selp.f32 	%r41, %r40, %r34, %p14;
	setp.gt.s64 	%p15, %rd48, 0;
	selp.b64 	%rd54, 1, 0, %p15;
	add.s64 	%rd55, %rd46, %rd54;
	selp.b64 	%rd56, -1, 0, %p15;
	add.s64 	%rd57, %rd48, %rd56;
	mul.lo.s64 	%rd58, %rd46, %rd9;
	add.s64 	%rd59, %rd1, %rd58;
	add.s64 	%rd60, %rd6, %rd58;
	ld.global.b32 	%r42, [%rd59];
	add.s64 	%rd61, %rd10, %rd60;
	ld.b32 	%r43, [%rd61];
	sub.ftz.f32 	%r44, %r1, %r42;
	sub.ftz.f32 	%r45, %r2, %r43;
	mul.ftz.f32 	%r46, %r45, %r45;
	fma.rn.ftz.f32 	%r47, %r44, %r44, %r46;
	setp.lt.ftz.f32 	%p16, %r47, %r41;
	selp.b64 	%rd62, %rd46, %rd53, %p16;
	selp.f32 	%r48, %r47, %r41, %p16;
	setp.gt.s64 	%p17, %rd57, 0;
	selp.b64 	%rd63, 1, 0, %p17;
	add.s64 	%rd64, %rd55, %rd63;
	selp.b64 	%rd65, -1, 0, %p17;
	add.s64 	%rd66, %rd57, %rd65;
	mul.lo.s64 	%rd67, %rd55, %rd9;
	add.s64 	%rd68, %rd1, %rd67;
	add.s64 	%rd69, %rd6, %rd67;
	ld.global.b32 	%r49, [%rd68];
	add.s64 	%rd70, %rd10, %rd69;
	ld.b32 	%r50, [%rd70];
	sub.ftz.f32 	%r51, %r1, %r49;
	sub.ftz.f32 	%r52, %r2, %r50;
	mul.ftz.f32 	%r53, %r52, %r52;
	fma.rn.ftz.f32 	%r54, %r51, %r51, %r53;
	setp.lt.ftz.f32 	%p18, %r54, %r48;
	selp.b64 	%rd71, %rd55, %rd62, %p18;
	selp.f32 	%r55, %r54, %r48, %p18;
	setp.gt.s64 	%p19, %rd66, 0;
	selp.b64 	%rd72, 1, 0, %p19;
	add.s64 	%rd73, %rd64, %rd72;
	selp.b64 	%rd74, -1, 0, %p19;
	add.s64 	%rd75, %rd66, %rd74;
	mul.lo.s64 	%rd76, %rd64, %rd9;
	add.s64 	%rd77, %rd1, %rd76;
	add.s64 	%rd78, %rd6, %rd76;
	ld.global.b32 	%r56, [%rd77];
	add.s64 	%rd79, %rd10, %rd78;
	ld.b32 	%r57, [%rd79];
	sub.ftz.f32 	%r58, %r1, %r56;
	sub.ftz.f32 	%r59, %r2, %r57;
	mul.ftz.f32 	%r60, %r59, %r59;
	fma.rn.ftz.f32 	%r61, %r58, %r58, %r60;
	setp.lt.ftz.f32 	%p20, %r61, %r55;
	selp.b64 	%rd80, %rd64, %rd71, %p20;
	selp.f32 	%r62, %r61, %r55, %p20;
	setp.gt.s64 	%p21, %rd75, 0;
	selp.b64 	%rd81, 1, 0, %p21;
	add.s64 	%rd145, %rd73, %rd81;
	selp.b64 	%rd82, -1, 0, %p21;
	add.s64 	%rd83, %rd75, %rd82;
	mul.lo.s64 	%rd84, %rd73, %rd9;
	add.s64 	%rd85, %rd1, %rd84;
	add.s64 	%rd86, %rd6, %rd84;
	ld.global.b32 	%r63, [%rd85];
	add.s64 	%rd87, %rd10, %rd86;
	ld.b32 	%r64, [%rd87];
	sub.ftz.f32 	%r65, %r1, %r63;
	sub.ftz.f32 	%r66, %r2, %r64;
	mul.ftz.f32 	%r67, %r66, %r66;
	fma.rn.ftz.f32 	%r68, %r65, %r65, %r67;
	setp.lt.ftz.f32 	%p22, %r68, %r62;
	selp.b64 	%rd144, %rd73, %rd80, %p22;
	selp.f32 	%r115, %r68, %r62, %p22;
	setp.gt.s64 	%p23, %rd83, 0;
	selp.b64 	%rd88, 1, 0, %p23;
	add.s64 	%rd143, %rd145, %rd88;
	selp.b64 	%rd89, -1, 0, %p23;
	add.s64 	%rd142, %rd83, %rd89;
	add.s64 	%rd141, %rd141, -8;
	setp.ne.b64 	%p24, %rd141, 0;
	@%p24 bra 	$L__BB0_2;
	and.b64 	%rd90, %rd5, 7;
	setp.eq.b64 	%p25, %rd90, 0;
	@%p25 bra 	$L__BB0_9;
$L__BB0_4:
	and.b64 	%rd4, %rd5, 3;
	and.b64 	%rd91, %rd5, 7;
	setp.lt.u64 	%p26, %rd91, 4;
	@%p26 bra 	$L__BB0_6;
	mul.lo.s64 	%rd92, %rd145, %rd9;
	add.s64 	%rd93, %rd1, %rd92;
	add.s64 	%rd94, %rd6, %rd92;
	ld.global.b32 	%r69, [%rd93];
	add.s64 	%rd95, %rd10, %rd94;
	ld.b32 	%r70, [%rd95];
	sub.ftz.f32 	%r71, %r1, %r69;
	sub.ftz.f32 	%r72, %r2, %r70;
	mul.ftz.f32 	%r73, %r72, %r72;
	fma.rn.ftz.f32 	%r74, %r71, %r71, %r73;
	setp.lt.ftz.f32 	%p27, %r74, %r115;
	selp.b64 	%rd96, %rd145, %rd144, %p27;
	selp.f32 	%r75, %r74, %r115, %p27;
	setp.gt.s64 	%p28, %rd142, 0;
	selp.b64 	%rd97, 1, 0, %p28;
	add.s64 	%rd98, %rd143, %rd97;
	selp.b64 	%rd99, -1, 0, %p28;
	add.s64 	%rd100, %rd142, %rd99;
	mul.lo.s64 	%rd101, %rd143, %rd9;
	add.s64 	%rd102, %rd1, %rd101;
	add.s64 	%rd103, %rd6, %rd101;
	ld.global.b32 	%r76, [%rd102];
	add.s64 	%rd104, %rd10, %rd103;
	ld.b32 	%r77, [%rd104];
	sub.ftz.f32 	%r78, %r1, %r76;
	sub.ftz.f32 	%r79, %r2, %r77;
	mul.ftz.f32 	%r80, %r79, %r79;
	fma.rn.ftz.f32 	%r81, %r78, %r78, %r80;
	setp.lt.ftz.f32 	%p29, %r81, %r75;
	selp.b64 	%rd105, %rd143, %rd96, %p29;
	selp.f32 	%r82, %r81, %r75, %p29;
	setp.gt.s64 	%p30, %rd100, 0;
	selp.b64 	%rd106, 1, 0, %p30;
	add.s64 	%rd107, %rd98, %rd106;
	selp.b64 	%rd108, -1, 0, %p30;
	add.s64 	%rd109, %rd100, %rd108;
	mul.lo.s64 	%rd110, %rd98, %rd9;
	add.s64 	%rd111, %rd1, %rd110;
	add.s64 	%rd112, %rd6, %rd110;
	ld.global.b32 	%r83, [%rd111];
	add.s64 	%rd113, %rd10, %rd112;
	ld.b32 	%r84, [%rd113];
	sub.ftz.f32 	%r85, %r1, %r83;
	sub.ftz.f32 	%r86, %r2, %r84;
	mul.ftz.f32 	%r87, %r86, %r86;
	fma.rn.ftz.f32 	%r88, %r85, %r85, %r87;
	setp.lt.ftz.f32 	%p31, %r88, %r82;
	selp.b64 	%rd114, %rd98, %rd105, %p31;
	selp.f32 	%r89, %r88, %r82, %p31;
	setp.gt.s64 	%p32, %rd109, 0;
	selp.b64 	%rd115, 1, 0, %p32;
	add.s64 	%rd145, %rd107, %rd115;
	selp.b64 	%rd116, -1, 0, %p32;
	add.s64 	%rd117, %rd109, %rd116;
	mul.lo.s64 	%rd118, %rd107, %rd9;
	add.s64 	%rd119, %rd1, %rd118;
	add.s64 	%rd120, %rd6, %rd118;
	ld.global.b32 	%r90, [%rd119];
	add.s64 	%rd121, %rd10, %rd120;
	ld.b32 	%r91, [%rd121];
	sub.ftz.f32 	%r92, %r1, %r90;
	sub.ftz.f32 	%r93, %r2, %r91;
	mul.ftz.f32 	%r94, %r93, %r93;
	fma.rn.ftz.f32 	%r95, %r92, %r92, %r94;
	setp.lt.ftz.f32 	%p33, %r95, %r89;
	selp.b64 	%rd144, %rd107, %rd114, %p33;
	selp.f32 	%r115, %r95, %r89, %p33;
	setp.gt.s64 	%p34, %rd117, 0;
	selp.b64 	%rd122, 1, 0, %p34;
	add.s64 	%rd143, %rd145, %rd122;
	selp.b64 	%rd123, -1, 0, %p34;
	add.s64 	%rd142, %rd117, %rd123;
	setp.eq.b64 	%p35, %rd4, 0;
	@%p35 bra 	$L__BB0_9;
$L__BB0_6:
	setp.eq.b64 	%p36, %rd4, 1;
	@%p36 bra 	$L__BB0_8;
	mul.lo.s64 	%rd124, %rd145, %rd9;
	add.s64 	%rd125, %rd1, %rd124;
	add.s64 	%rd126, %rd6, %rd124;
	ld.global.b32 	%r96, [%rd125];
	add.s64 	%rd127, %rd10, %rd126;
	ld.b32 	%r97, [%rd127];
	sub.ftz.f32 	%r98, %r1, %r96;
	sub.ftz.f32 	%r99, %r2, %r97;
	mul.ftz.f32 	%r100, %r99, %r99;
	fma.rn.ftz.f32 	%r101, %r98, %r98, %r100;
	setp.lt.ftz.f32 	%p37, %r101, %r115;
	selp.b64 	%rd128, %rd145, %rd144, %p37;
	selp.f32 	%r102, %r101, %r115, %p37;
	setp.gt.s64 	%p38, %rd142, 0;
	selp.b64 	%rd129, 1, 0, %p38;
	add.s64 	%rd145, %rd143, %rd129;
	mul.lo.s64 	%rd130, %rd143, %rd9;
	add.s64 	%rd131, %rd1, %rd130;
	add.s64 	%rd132, %rd6, %rd130;
	ld.global.b32 	%r103, [%rd131];
	add.s64 	%rd133, %rd10, %rd132;
	ld.b32 	%r104, [%rd133];
	sub.ftz.f32 	%r105, %r1, %r103;
	sub.ftz.f32 	%r106, %r2, %r104;
	mul.ftz.f32 	%r107, %r106, %r106;
	fma.rn.ftz.f32 	%r108, %r105, %r105, %r107;
	setp.lt.ftz.f32 	%p39, %r108, %r102;
	selp.b64 	%rd144, %rd143, %rd128, %p39;
	selp.f32 	%r115, %r108, %r102, %p39;
	and.b64 	%rd134, %rd5, 1;
	setp.ne.b64 	%p40, %rd134, 0;
	not.pred 	%p41, %p40;
	@%p41 bra 	$L__BB0_9;
$L__BB0_8:
	mul.lo.s64 	%rd135, %rd145, %rd9;
	add.s64 	%rd136, %rd1, %rd135;
	add.s64 	%rd137, %rd6, %rd135;
	ld.global.b32 	%r109, [%rd136];
	add.s64 	%rd138, %rd10, %rd137;
	ld.b32 	%r110, [%rd138];
	sub.ftz.f32 	%r111, %r1, %r109;
	sub.ftz.f32 	%r112, %r2, %r110;
	mul.ftz.f32 	%r113, %r112, %r112;
	fma.rn.ftz.f32 	%r114, %r111, %r111, %r113;
	setp.lt.ftz.f32 	%p42, %r114, %r115;
	selp.b64 	%rd144, %rd145, %rd144, %p42;
$L__BB0_9:
	cvt.u32.u64 	%r116, %rd144;
$L__BB0_10:
	mad.lo.s64 	%rd139, %rd12, %rd2, %rd11;
	mad.lo.s64 	%rd140, %rd13, %rd3, %rd139;
	st.b32 	[%rd140], %r116;
	bra.uni 	$L__BB0_1;
$L__BB0_11:
	max.s64 	%rd18, %rd7, 0;
	setp.lt.s64 	%p4, %rd7, 1;
	setp.gt.s64 	%p5, %rd7, 0;
	selp.b64 	%rd19, -1, 0, %p5;
	add.s64 	%rd142, %rd18, %rd19;
	mov.b32 	%r116, 0;
	@%p4 bra 	$L__BB0_10;
	setp.ne.b64 	%p6, %rd8, 2;
	@%p6 bra 	$L__BB0_1;
	min.s64 	%rd20, %rd142, 0;
	sub.s64 	%rd21, %rd142, %rd20;
	add.s64 	%rd5, %rd21, 1;
	setp.lt.u64 	%p7, %rd21, 7;
	mov.b32 	%r115, 0f7F800000;
	mov.b64 	%rd144, 0;
	mov.b64 	%rd143, 1;
	mov.b64 	%rd145, %rd144;
	@%p7 bra 	$L__BB0_4;
	and.b64 	%rd141, %rd5, -8;
	mov.b32 	%r115, 0f7F800000;
	mov.b64 	%rd144, 0;
	mov.b64 	%rd143, 1;
	bra.uni 	$L__BB0_2;

}