//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-36037853
// Cuda compilation tools, release 12.9, V12.9.86
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_75
.address_size 64

	// .globl	_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;

.visible .entry _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<60>;
	.reg .f32 	%f<122>;
	.reg .b32 	%r<76>;
	.reg .b64 	%rd<115>;


	ld.param.u64 	%rd16, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.u64 	%rd17, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.u64 	%rd18, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6];
	ld.param.u64 	%rd19, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.u64 	%rd20, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.u64 	%rd22, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd23, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	mov.u32 	%r3, %tid.x;
	cvt.s64.s32 	%rd27, %r3;
	mov.u32 	%r4, %ntid.x;
	mov.u32 	%r5, %ctaid.x;
	mul.wide.s32 	%rd28, %r4, %r5;
	add.s64 	%rd1, %rd28, %rd27;
	mov.u32 	%r6, %tid.y;
	cvt.s64.s32 	%rd29, %r6;
	mov.u32 	%r7, %ntid.y;
	mov.u32 	%r8, %ctaid.y;
	mul.wide.s32 	%rd30, %r7, %r8;
	add.s64 	%rd2, %rd30, %rd29;
	mul.wide.s32 	%rd31, %r6, %r4;
	add.s64 	%rd32, %rd31, %rd27;
	shr.u64 	%rd33, %rd32, 63;
	add.s64 	%rd34, %rd32, %rd33;
	shr.s64 	%rd35, %rd34, 1;
	and.b64  	%rd36, %rd34, -2;
	sub.s64 	%rd3, %rd32, %rd36;
	shr.s64 	%rd37, %rd3, 63;
	add.s64 	%rd38, %rd37, %rd35;
	shr.s64 	%rd39, %rd38, 63;
	shr.u64 	%rd40, %rd39, 60;
	add.s64 	%rd41, %rd38, %rd40;
	and.b64  	%rd42, %rd41, -16;
	sub.s64 	%rd43, %rd38, %rd42;
	setp.lt.s64 	%p2, %rd43, 0;
	mov.u64 	%rd114, 0;
	add.s64 	%rd44, %rd43, 16;
	selp.b64 	%rd4, %rd44, %rd43, %p2;
	and.b64  	%rd45, %rd17, 15;
	setp.ne.s64 	%p3, %rd45, 0;
	selp.u64 	%rd46, 1, 0, %p3;
	shr.u64 	%rd47, %rd17, 4;
	add.s64 	%rd48, %rd47, %rd46;
	setp.gt.s64 	%p4, %rd17, 0;
	selp.b64 	%rd5, %rd48, 0, %p4;
	setp.ne.s64 	%p1, %rd5, 0;
	setp.eq.s64 	%p5, %rd5, 0;
	@%p5 bra 	$L__BB0_5;

	cvt.rn.f32.s64 	%f6, %rd22;
	cvt.rn.f32.s64 	%f7, %rd1;
	div.approx.ftz.f32 	%f1, %f7, %f6;
	cvt.rn.f32.s64 	%f8, %rd23;
	cvt.rn.f32.s64 	%f9, %rd2;
	div.approx.ftz.f32 	%f2, %f9, %f8;
	add.s64 	%rd51, %rd3, 2;
	setp.lt.s64 	%p6, %rd3, 0;
	mov.u64 	%rd112, 0;
	selp.b64 	%rd52, %rd51, %rd3, %p6;
	shr.s64 	%rd53, %rd52, 63;
	and.b64  	%rd54, %rd53, %rd18;
	add.s64 	%rd55, %rd54, %rd52;
	mul.lo.s64 	%rd56, %rd55, %rd20;
	add.s64 	%rd6, %rd56, %rd16;
	selp.s64 	%rd57, -1, 0, %p1;
	add.s64 	%rd111, %rd5, %rd57;
	mov.f32 	%f121, 0f7F800000;
	mov.u64 	%rd114, %rd112;

$L__BB0_2:
	add.s64 	%rd11, %rd4, %rd112;
	setp.ge.s64 	%p7, %rd11, %rd17;
	mov.u32 	%r75, 2139095040;
	@%p7 bra 	$L__BB0_4;

	shr.s64 	%rd58, %rd11, 63;
	and.b64  	%rd59, %rd58, %rd17;
	add.s64 	%rd60, %rd4, %rd59;
	add.s64 	%rd61, %rd60, %rd112;
	mul.lo.s64 	%rd62, %rd61, %rd19;
	add.s64 	%rd63, %rd6, %rd62;
	ld.u32 	%r75, [%rd63];

$L__BB0_4:
	mov.u32 	%r10, 31;
	mov.u32 	%r11, 0;
	mov.u32 	%r12, -1;
	shfl.sync.idx.b32 	%r13|%p8, %r75, %r11, %r10, %r12;
	mov.b32 	%f10, %r13;
	mov.u32 	%r14, 1;
	shfl.sync.idx.b32 	%r15|%p9, %r75, %r14, %r10, %r12;
	mov.b32 	%f11, %r15;
	sub.ftz.f32 	%f12, %f1, %f10;
	sub.ftz.f32 	%f13, %f2, %f11;
	mul.ftz.f32 	%f14, %f13, %f13;
	fma.rn.ftz.f32 	%f15, %f12, %f12, %f14;
	setp.lt.ftz.f32 	%p10, %f15, %f121;
	selp.b64 	%rd64, %rd112, %rd114, %p10;
	selp.f32 	%f16, %f15, %f121, %p10;
	mov.u32 	%r16, 2;
	shfl.sync.idx.b32 	%r17|%p11, %r75, %r16, %r10, %r12;
	mov.b32 	%f17, %r17;
	mov.u32 	%r18, 3;
	shfl.sync.idx.b32 	%r19|%p12, %r75, %r18, %r10, %r12;
	mov.b32 	%f18, %r19;
	sub.ftz.f32 	%f19, %f1, %f17;
	sub.ftz.f32 	%f20, %f2, %f18;
	mul.ftz.f32 	%f21, %f20, %f20;
	fma.rn.ftz.f32 	%f22, %f19, %f19, %f21;
	setp.lt.ftz.f32 	%p13, %f22, %f16;
	add.s64 	%rd65, %rd112, 1;
	selp.b64 	%rd66, %rd65, %rd64, %p13;
	selp.f32 	%f23, %f22, %f16, %p13;
	mov.u32 	%r20, 4;
	shfl.sync.idx.b32 	%r21|%p14, %r75, %r20, %r10, %r12;
	mov.b32 	%f24, %r21;
	mov.u32 	%r22, 5;
	shfl.sync.idx.b32 	%r23|%p15, %r75, %r22, %r10, %r12;
	mov.b32 	%f25, %r23;
	sub.ftz.f32 	%f26, %f1, %f24;
	sub.ftz.f32 	%f27, %f2, %f25;
	mul.ftz.f32 	%f28, %f27, %f27;
	fma.rn.ftz.f32 	%f29, %f26, %f26, %f28;
	setp.lt.ftz.f32 	%p16, %f29, %f23;
	add.s64 	%rd67, %rd112, 2;
	selp.b64 	%rd68, %rd67, %rd66, %p16;
	selp.f32 	%f30, %f29, %f23, %p16;
	mov.u32 	%r24, 6;
	shfl.sync.idx.b32 	%r25|%p17, %r75, %r24, %r10, %r12;
	mov.b32 	%f31, %r25;
	mov.u32 	%r26, 7;
	shfl.sync.idx.b32 	%r27|%p18, %r75, %r26, %r10, %r12;
	mov.b32 	%f32, %r27;
	sub.ftz.f32 	%f33, %f1, %f31;
	sub.ftz.f32 	%f34, %f2, %f32;
	mul.ftz.f32 	%f35, %f34, %f34;
	fma.rn.ftz.f32 	%f36, %f33, %f33, %f35;
	setp.lt.ftz.f32 	%p19, %f36, %f30;
	add.s64 	%rd69, %rd112, 3;
	selp.b64 	%rd70, %rd69, %rd68, %p19;
	selp.f32 	%f37, %f36, %f30, %p19;
	mov.u32 	%r28, 8;
	shfl.sync.idx.b32 	%r29|%p20, %r75, %r28, %r10, %r12;
	mov.b32 	%f38, %r29;
	mov.u32 	%r30, 9;
	shfl.sync.idx.b32 	%r31|%p21, %r75, %r30, %r10, %r12;
	mov.b32 	%f39, %r31;
	sub.ftz.f32 	%f40, %f1, %f38;
	sub.ftz.f32 	%f41, %f2, %f39;
	mul.ftz.f32 	%f42, %f41, %f41;
	fma.rn.ftz.f32 	%f43, %f40, %f40, %f42;
	setp.lt.ftz.f32 	%p22, %f43, %f37;
	add.s64 	%rd71, %rd112, 4;
	selp.b64 	%rd72, %rd71, %rd70, %p22;
	selp.f32 	%f44, %f43, %f37, %p22;
	mov.u32 	%r32, 10;
	shfl.sync.idx.b32 	%r33|%p23, %r75, %r32, %r10, %r12;
	mov.b32 	%f45, %r33;
	mov.u32 	%r34, 11;
	shfl.sync.idx.b32 	%r35|%p24, %r75, %r34, %r10, %r12;
	mov.b32 	%f46, %r35;
	sub.ftz.f32 	%f47, %f1, %f45;
	sub.ftz.f32 	%f48, %f2, %f46;
	mul.ftz.f32 	%f49, %f48, %f48;
	fma.rn.ftz.f32 	%f50, %f47, %f47, %f49;
	setp.lt.ftz.f32 	%p25, %f50, %f44;
	add.s64 	%rd73, %rd112, 5;
	selp.b64 	%rd74, %rd73, %rd72, %p25;
	selp.f32 	%f51, %f50, %f44, %p25;
	mov.u32 	%r36, 12;
	shfl.sync.idx.b32 	%r37|%p26, %r75, %r36, %r10, %r12;
	mov.b32 	%f52, %r37;
	mov.u32 	%r38, 13;
	shfl.sync.idx.b32 	%r39|%p27, %r75, %r38, %r10, %r12;
	mov.b32 	%f53, %r39;
	sub.ftz.f32 	%f54, %f1, %f52;
	sub.ftz.f32 	%f55, %f2, %f53;
	mul.ftz.f32 	%f56, %f55, %f55;
	fma.rn.ftz.f32 	%f57, %f54, %f54, %f56;
	setp.lt.ftz.f32 	%p28, %f57, %f51;
	add.s64 	%rd75, %rd112, 6;
	selp.b64 	%rd76, %rd75, %rd74, %p28;
	selp.f32 	%f58, %f57, %f51, %p28;
	mov.u32 	%r40, 14;
	shfl.sync.idx.b32 	%r41|%p29, %r75, %r40, %r10, %r12;
	mov.b32 	%f59, %r41;
	mov.u32 	%r42, 15;
	shfl.sync.idx.b32 	%r43|%p30, %r75, %r42, %r10, %r12;
	mov.b32 	%f60, %r43;
	sub.ftz.f32 	%f61, %f1, %f59;
	sub.ftz.f32 	%f62, %f2, %f60;
	mul.ftz.f32 	%f63, %f62, %f62;
	fma.rn.ftz.f32 	%f64, %f61, %f61, %f63;
	setp.lt.ftz.f32 	%p31, %f64, %f58;
	add.s64 	%rd77, %rd112, 7;
	selp.b64 	%rd78, %rd77, %rd76, %p31;
	selp.f32 	%f65, %f64, %f58, %p31;
	mov.u32 	%r44, 16;
	shfl.sync.idx.b32 	%r45|%p32, %r75, %r44, %r10, %r12;
	mov.b32 	%f66, %r45;
	mov.u32 	%r46, 17;
	shfl.sync.idx.b32 	%r47|%p33, %r75, %r46, %r10, %r12;
	mov.b32 	%f67, %r47;
	sub.ftz.f32 	%f68, %f1, %f66;
	sub.ftz.f32 	%f69, %f2, %f67;
	mul.ftz.f32 	%f70, %f69, %f69;
	fma.rn.ftz.f32 	%f71, %f68, %f68, %f70;
	setp.lt.ftz.f32 	%p34, %f71, %f65;
	add.s64 	%rd79, %rd112, 8;
	selp.b64 	%rd80, %rd79, %rd78, %p34;
	selp.f32 	%f72, %f71, %f65, %p34;
	mov.u32 	%r48, 18;
	shfl.sync.idx.b32 	%r49|%p35, %r75, %r48, %r10, %r12;
	mov.b32 	%f73, %r49;
	mov.u32 	%r50, 19;
	shfl.sync.idx.b32 	%r51|%p36, %r75, %r50, %r10, %r12;
	mov.b32 	%f74, %r51;
	sub.ftz.f32 	%f75, %f1, %f73;
	sub.ftz.f32 	%f76, %f2, %f74;
	mul.ftz.f32 	%f77, %f76, %f76;
	fma.rn.ftz.f32 	%f78, %f75, %f75, %f77;
	setp.lt.ftz.f32 	%p37, %f78, %f72;
	add.s64 	%rd81, %rd112, 9;
	selp.b64 	%rd82, %rd81, %rd80, %p37;
	selp.f32 	%f79, %f78, %f72, %p37;
	mov.u32 	%r52, 20;
	shfl.sync.idx.b32 	%r53|%p38, %r75, %r52, %r10, %r12;
	mov.b32 	%f80, %r53;
	mov.u32 	%r54, 21;
	shfl.sync.idx.b32 	%r55|%p39, %r75, %r54, %r10, %r12;
	mov.b32 	%f81, %r55;
	sub.ftz.f32 	%f82, %f1, %f80;
	sub.ftz.f32 	%f83, %f2, %f81;
	mul.ftz.f32 	%f84, %f83, %f83;
	fma.rn.ftz.f32 	%f85, %f82, %f82, %f84;
	setp.lt.ftz.f32 	%p40, %f85, %f79;
	add.s64 	%rd83, %rd112, 10;
	selp.b64 	%rd84, %rd83, %rd82, %p40;
	selp.f32 	%f86, %f85, %f79, %p40;
	mov.u32 	%r56, 22;
	shfl.sync.idx.b32 	%r57|%p41, %r75, %r56, %r10, %r12;
	mov.b32 	%f87, %r57;
	mov.u32 	%r58, 23;
	shfl.sync.idx.b32 	%r59|%p42, %r75, %r58, %r10, %r12;
	mov.b32 	%f88, %r59;
	sub.ftz.f32 	%f89, %f1, %f87;
	sub.ftz.f32 	%f90, %f2, %f88;
	mul.ftz.f32 	%f91, %f90, %f90;
	fma.rn.ftz.f32 	%f92, %f89, %f89, %f91;
	setp.lt.ftz.f32 	%p43, %f92, %f86;
	add.s64 	%rd85, %rd112, 11;
	selp.b64 	%rd86, %rd85, %rd84, %p43;
	selp.f32 	%f93, %f92, %f86, %p43;
	mov.u32 	%r60, 24;
	shfl.sync.idx.b32 	%r61|%p44, %r75, %r60, %r10, %r12;
	mov.b32 	%f94, %r61;
	mov.u32 	%r62, 25;
	shfl.sync.idx.b32 	%r63|%p45, %r75, %r62, %r10, %r12;
	mov.b32 	%f95, %r63;
	sub.ftz.f32 	%f96, %f1, %f94;
	sub.ftz.f32 	%f97, %f2, %f95;
	mul.ftz.f32 	%f98, %f97, %f97;
	fma.rn.ftz.f32 	%f99, %f96, %f96, %f98;
	setp.lt.ftz.f32 	%p46, %f99, %f93;
	add.s64 	%rd87, %rd112, 12;
	selp.b64 	%rd88, %rd87, %rd86, %p46;
	selp.f32 	%f100, %f99, %f93, %p46;
	mov.u32 	%r64, 26;
	shfl.sync.idx.b32 	%r65|%p47, %r75, %r64, %r10, %r12;
	mov.b32 	%f101, %r65;
	mov.u32 	%r66, 27;
	shfl.sync.idx.b32 	%r67|%p48, %r75, %r66, %r10, %r12;
	mov.b32 	%f102, %r67;
	sub.ftz.f32 	%f103, %f1, %f101;
	sub.ftz.f32 	%f104, %f2, %f102;
	mul.ftz.f32 	%f105, %f104, %f104;
	fma.rn.ftz.f32 	%f106, %f103, %f103, %f105;
	setp.lt.ftz.f32 	%p49, %f106, %f100;
	add.s64 	%rd89, %rd112, 13;
	selp.b64 	%rd90, %rd89, %rd88, %p49;
	selp.f32 	%f107, %f106, %f100, %p49;
	mov.u32 	%r68, 28;
	shfl.sync.idx.b32 	%r69|%p50, %r75, %r68, %r10, %r12;
	mov.b32 	%f108, %r69;
	mov.u32 	%r70, 29;
	shfl.sync.idx.b32 	%r71|%p51, %r75, %r70, %r10, %r12;
	mov.b32 	%f109, %r71;
	sub.ftz.f32 	%f110, %f1, %f108;
	sub.ftz.f32 	%f111, %f2, %f109;
	mul.ftz.f32 	%f112, %f111, %f111;
	fma.rn.ftz.f32 	%f113, %f110, %f110, %f112;
	setp.lt.ftz.f32 	%p52, %f113, %f107;
	add.s64 	%rd91, %rd112, 14;
	selp.b64 	%rd92, %rd91, %rd90, %p52;
	selp.f32 	%f114, %f113, %f107, %p52;
	mov.u32 	%r72, 30;
	shfl.sync.idx.b32 	%r73|%p53, %r75, %r72, %r10, %r12;
	mov.b32 	%f115, %r73;
	shfl.sync.idx.b32 	%r74|%p54, %r75, %r10, %r10, %r12;
	mov.b32 	%f116, %r74;
	sub.ftz.f32 	%f117, %f1, %f115;
	sub.ftz.f32 	%f118, %f2, %f116;
	mul.ftz.f32 	%f119, %f118, %f118;
	fma.rn.ftz.f32 	%f120, %f117, %f117, %f119;
	setp.lt.ftz.f32 	%p55, %f120, %f114;
	add.s64 	%rd93, %rd112, 15;
	selp.b64 	%rd114, %rd93, %rd92, %p55;
	selp.f32 	%f121, %f120, %f114, %p55;
	add.s64 	%rd13, %rd111, -1;
	add.s64 	%rd112, %rd112, 16;
	setp.gt.s64 	%p56, %rd111, 0;
	mov.u64 	%rd111, %rd13;
	@%p56 bra 	$L__BB0_2;

$L__BB0_5:
	ld.param.u64 	%rd109, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd104, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	setp.ge.s64 	%p57, %rd2, %rd104;
	setp.ge.s64 	%p58, %rd1, %rd109;
	or.pred  	%p59, %p58, %p57;
	@%p59 bra 	$L__BB0_7;

	ld.param.u64 	%rd110, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd108, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.u64 	%rd107, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	ld.param.u64 	%rd106, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.u64 	%rd105, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v68B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	shr.s64 	%rd94, %rd1, 63;
	and.b64  	%rd95, %rd94, %rd110;
	add.s64 	%rd96, %rd95, %rd1;
	shr.s64 	%rd97, %rd2, 63;
	and.b64  	%rd98, %rd97, %rd105;
	add.s64 	%rd99, %rd98, %rd2;
	mul.lo.s64 	%rd100, %rd96, %rd106;
	mul.lo.s64 	%rd101, %rd99, %rd107;
	add.s64 	%rd102, %rd100, %rd108;
	add.s64 	%rd103, %rd102, %rd101;
	st.u32 	[%rd103], %rd114;

$L__BB0_7:
	ret;

}