//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi
.common .global .align 8 .u64 _ZN08NumbaEnv6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi;

.visible .entry _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi(
	.param .u64 .ptr .align 1 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_0,
	.param .u64 .ptr .align 1 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_1,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_2,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_3,
	.param .u64 .ptr .align 1 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_4,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_5,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_6,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_7,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_8,
	.param .u64 .ptr .align 1 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_9,
	.param .u64 .ptr .align 1 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_10,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_11,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_12,
	.param .u64 .ptr .align 1 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_13,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_14,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_15,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_16,
	.param .u64 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_17,
	.param .u32 _ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_18
)
{
	.reg .pred 	%p<34>;
	.reg .b32 	%r<53>;
	.reg .b64 	%rd<88>;

	ld.param.b64 	%rd16, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_4];
	ld.param.b64 	%rd17, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_5];
	ld.param.b64 	%rd18, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_6];
	ld.param.b64 	%rd19, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_7];
	ld.param.b64 	%rd20, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_8];
	ld.param.b64 	%rd21, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_14];
	ld.param.b64 	%rd22, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_15];
	ld.param.b32 	%r4, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_18];
	cvta.to.global.u64 	%rd1, %rd16;
	mov.u32 	%r5, %tid.x;
	cvt.u64.u32 	%rd23, %r5;
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mul.wide.u32 	%rd24, %r6, %r7;
	add.s64 	%rd2, %rd24, %rd23;
	mov.u32 	%r8, %tid.y;
	mov.u32 	%r9, %ntid.y;
	mov.u32 	%r10, %ctaid.y;
	mad.lo.s32 	%r11, %r9, %r10, %r8;
	cvt.u64.u32 	%rd3, %r11;
	cvt.rn.f32.u64 	%r12, %rd2;
	cvt.rn.f32.u64 	%r13, %rd21;
	div.approx.ftz.f32 	%r1, %r12, %r13;
	cvt.rn.f32.u32 	%r14, %r11;
	cvt.rn.f32.s64 	%r15, %rd22;
	div.approx.ftz.f32 	%r2, %r14, %r15;
	setp.ge.u64 	%p1, %rd2, %rd21;
	setp.le.s64 	%p2, %rd22, %rd3;
	or.pred 	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_1;
	bra.uni 	$L__BB0_8;
$L__BB0_1:
	ret;
$L__BB0_2:
	setp.ge.s64 	%p23, %rd14, %rd22;
	setp.ge.s64 	%p24, %rd10, %rd21;
	or.pred 	%p25, %p24, %p23;
	mov.b32 	%r47, %r45;
	mov.b32 	%r48, %r46;
	@%p25 bra 	$L__BB0_5;
	ld.param.b64 	%rd86, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_17];
	shr.s64 	%rd63, %rd10, 63;
	and.b64 	%rd64, %rd63, %rd22;
	add.s64 	%rd65, %rd64, %rd10;
	mad.lo.s64 	%rd66, %rd65, %rd86, %rd15;
	ld.b32 	%r48, [%rd66];
	cvt.s64.s32 	%rd67, %r48;
	setp.lt.s32 	%p26, %r48, 0;
	selp.b64 	%rd68, %rd17, 0, %p26;
	add.s64 	%rd69, %rd68, %rd67;
	mul.lo.s64 	%rd70, %rd69, %rd19;
	add.s64 	%rd71, %rd1, %rd70;
	add.s64 	%rd72, %rd16, %rd70;
	ld.global.b32 	%r35, [%rd71];
	add.s64 	%rd73, %rd20, %rd72;
	ld.b32 	%r36, [%rd73];
	sub.ftz.f32 	%r37, %r1, %r35;
	sub.ftz.f32 	%r38, %r2, %r36;
	mul.ftz.f32 	%r39, %r38, %r38;
	fma.rn.ftz.f32 	%r47, %r37, %r37, %r39;
	setp.lt.ftz.f32 	%p27, %r47, %r45;
	@%p27 bra 	$L__BB0_5;
	mov.b32 	%r47, %r45;
	mov.b32 	%r48, %r46;
$L__BB0_5:
	setp.ge.s64 	%p28, %rd11, %rd21;
	or.pred 	%p29, %p28, %p23;
	mov.b32 	%r45, %r47;
	mov.b32 	%r46, %r48;
	@%p29 bra 	$L__BB0_24;
	add.s64 	%rd74, %rd15, %rd12;
	ld.b32 	%r46, [%rd74];
	cvt.s64.s32 	%rd75, %r46;
	setp.lt.s32 	%p30, %r46, 0;
	selp.b64 	%rd76, %rd17, 0, %p30;
	add.s64 	%rd77, %rd76, %rd75;
	mul.lo.s64 	%rd78, %rd77, %rd19;
	add.s64 	%rd79, %rd1, %rd78;
	add.s64 	%rd80, %rd16, %rd78;
	ld.global.b32 	%r40, [%rd79];
	add.s64 	%rd81, %rd20, %rd80;
	ld.b32 	%r41, [%rd81];
	sub.ftz.f32 	%r42, %r1, %r40;
	sub.ftz.f32 	%r43, %r2, %r41;
	mul.ftz.f32 	%r44, %r43, %r43;
	fma.rn.ftz.f32 	%r45, %r42, %r42, %r44;
	setp.lt.ftz.f32 	%p31, %r45, %r47;
	@%p31 bra 	$L__BB0_24;
	mov.b32 	%r45, %r47;
	mov.b32 	%r46, %r48;
	bra.uni 	$L__BB0_24;
$L__BB0_8:
	ld.param.b64 	%rd84, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_17];
	ld.param.b64 	%rd83, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_16];
	ld.param.b64 	%rd82, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_13];
	mul.lo.s64 	%rd4, %rd84, %rd2;
	mad.lo.s64 	%rd25, %rd83, %rd3, %rd82;
	add.s64 	%rd5, %rd25, %rd4;
	ld.b32 	%r46, [%rd5];
	cvt.s64.s32 	%rd26, %r46;
	setp.lt.s32 	%p4, %r46, 0;
	selp.b64 	%rd27, %rd17, 0, %p4;
	add.s64 	%rd28, %rd27, %rd26;
	mul.lo.s64 	%rd6, %rd28, %rd19;
	add.s64 	%rd7, %rd1, %rd6;
	setp.gt.s64 	%p5, %rd18, 0;
	@%p5 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_1;
$L__BB0_9:
	ld.global.b32 	%r3, [%rd7];
	setp.eq.b64 	%p6, %rd18, 1;
	@%p6 bra 	$L__BB0_1;
	add.s64 	%rd8, %rd16, %rd6;
	setp.gt.u64 	%p7, %rd18, 2;
	@%p7 bra 	$L__BB0_1;
	add.s64 	%rd29, %rd20, %rd8;
	ld.b32 	%r16, [%rd29];
	sub.ftz.f32 	%r17, %r1, %r3;
	sub.ftz.f32 	%r18, %r2, %r16;
	mul.ftz.f32 	%r19, %r18, %r18;
	fma.rn.ftz.f32 	%r45, %r17, %r17, %r19;
	cvt.s64.s32 	%rd9, %r4;
	sub.s64 	%rd10, %rd2, %rd9;
	add.s64 	%rd11, %rd2, %rd9;
	shr.s64 	%rd30, %rd11, 63;
	and.b64 	%rd31, %rd30, %rd22;
	add.s64 	%rd32, %rd31, %rd11;
	mul.lo.s64 	%rd12, %rd32, %rd84;
	mov.b64 	%rd13, 0;
$L__BB0_12:
	mov.b64 	%rd87, -1;
	mov.pred 	%p33, 0;
	setp.eq.b64 	%p8, %rd13, 2;
	@%p8 bra 	$L__BB0_27;
	setp.eq.b64 	%p9, %rd13, 1;
	@%p9 bra 	$L__BB0_26;
$L__BB0_14:
	add.s64 	%rd13, %rd13, 1;
	mad.lo.s64 	%rd14, %rd87, %rd9, %rd3;
	shr.s64 	%rd33, %rd14, 63;
	and.b64 	%rd34, %rd33, %rd21;
	add.s64 	%rd35, %rd34, %rd14;
	mad.lo.s64 	%rd15, %rd35, %rd83, %rd82;
	@%p33 bra 	$L__BB0_2;
	setp.ge.s64 	%p10, %rd14, %rd22;
	setp.ge.s64 	%p11, %rd10, %rd21;
	or.pred 	%p12, %p11, %p10;
	mov.b32 	%r49, %r45;
	mov.b32 	%r50, %r46;
	@%p12 bra 	$L__BB0_18;
	ld.param.b64 	%rd85, [_ZN6task6c39_jfa_inout_pass_square_euclidean_kernelB3v90B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEi_param_17];
	shr.s64 	%rd36, %rd10, 63;
	and.b64 	%rd37, %rd36, %rd22;
	add.s64 	%rd38, %rd37, %rd10;
	mad.lo.s64 	%rd39, %rd38, %rd85, %rd15;
	ld.b32 	%r50, [%rd39];
	cvt.s64.s32 	%rd40, %r50;
	setp.lt.s32 	%p13, %r50, 0;
	selp.b64 	%rd41, %rd17, 0, %p13;
	add.s64 	%rd42, %rd41, %rd40;
	mul.lo.s64 	%rd43, %rd42, %rd19;
	add.s64 	%rd44, %rd1, %rd43;
	add.s64 	%rd45, %rd16, %rd43;
	ld.global.b32 	%r20, [%rd44];
	add.s64 	%rd46, %rd20, %rd45;
	ld.b32 	%r21, [%rd46];
	sub.ftz.f32 	%r22, %r1, %r20;
	sub.ftz.f32 	%r23, %r2, %r21;
	mul.ftz.f32 	%r24, %r23, %r23;
	fma.rn.ftz.f32 	%r49, %r22, %r22, %r24;
	setp.lt.ftz.f32 	%p14, %r49, %r45;
	@%p14 bra 	$L__BB0_18;
	mov.b32 	%r49, %r45;
	mov.b32 	%r50, %r46;
$L__BB0_18:
	setp.ge.s64 	%p15, %rd2, %rd21;
	or.pred 	%p16, %p15, %p10;
	mov.b32 	%r51, %r49;
	mov.b32 	%r52, %r50;
	@%p16 bra 	$L__BB0_21;
	add.s64 	%rd47, %rd15, %rd4;
	ld.b32 	%r52, [%rd47];
	cvt.s64.s32 	%rd48, %r52;
	setp.lt.s32 	%p17, %r52, 0;
	selp.b64 	%rd49, %rd17, 0, %p17;
	add.s64 	%rd50, %rd49, %rd48;
	mul.lo.s64 	%rd51, %rd50, %rd19;
	add.s64 	%rd52, %rd1, %rd51;
	add.s64 	%rd53, %rd16, %rd51;
	ld.global.b32 	%r25, [%rd52];
	add.s64 	%rd54, %rd20, %rd53;
	ld.b32 	%r26, [%rd54];
	sub.ftz.f32 	%r27, %r1, %r25;
	sub.ftz.f32 	%r28, %r2, %r26;
	mul.ftz.f32 	%r29, %r28, %r28;
	fma.rn.ftz.f32 	%r51, %r27, %r27, %r29;
	setp.lt.ftz.f32 	%p18, %r51, %r49;
	@%p18 bra 	$L__BB0_21;
	mov.b32 	%r51, %r49;
	mov.b32 	%r52, %r50;
$L__BB0_21:
	setp.ge.s64 	%p19, %rd11, %rd21;
	or.pred 	%p20, %p19, %p10;
	mov.b32 	%r45, %r51;
	mov.b32 	%r46, %r52;
	@%p20 bra 	$L__BB0_24;
	add.s64 	%rd55, %rd15, %rd12;
	ld.b32 	%r46, [%rd55];
	cvt.s64.s32 	%rd56, %r46;
	setp.lt.s32 	%p21, %r46, 0;
	selp.b64 	%rd57, %rd17, 0, %p21;
	add.s64 	%rd58, %rd57, %rd56;
	mul.lo.s64 	%rd59, %rd58, %rd19;
	add.s64 	%rd60, %rd1, %rd59;
	add.s64 	%rd61, %rd16, %rd59;
	ld.global.b32 	%r30, [%rd60];
	add.s64 	%rd62, %rd20, %rd61;
	ld.b32 	%r31, [%rd62];
	sub.ftz.f32 	%r32, %r1, %r30;
	sub.ftz.f32 	%r33, %r2, %r31;
	mul.ftz.f32 	%r34, %r33, %r33;
	fma.rn.ftz.f32 	%r45, %r32, %r32, %r34;
	setp.lt.ftz.f32 	%p22, %r45, %r51;
	@%p22 bra 	$L__BB0_24;
	mov.b32 	%r45, %r51;
	mov.b32 	%r46, %r52;
$L__BB0_24:
	setp.eq.b64 	%p32, %rd13, 3;
	@%p32 bra 	$L__BB0_25;
	bra.uni 	$L__BB0_12;
$L__BB0_25:
	st.b32 	[%rd5], %r46;
	bra.uni 	$L__BB0_1;
$L__BB0_26:
	mov.b64 	%rd87, 0;
	mov.pred 	%p33, -1;
	bra.uni 	$L__BB0_14;
$L__BB0_27:
	mov.b64 	%rd87, 1;
	bra.uni 	$L__BB0_14;

}