//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii
.common .global .align 8 .u64 _ZN08NumbaEnv6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii;

.visible .entry _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii(
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_0,
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_1,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_2,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_3,
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_4,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_5,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_6,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_7,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_8,
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_9,
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_10,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_11,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_12,
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_13,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_14,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_15,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_16,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_17,
	.param .u32 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_18,
	.param .u32 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_19
)
{
	.reg .pred 	%p<50>;
	.reg .b32 	%r<52>;
	.reg .b64 	%rd<48>;

	ld.param.b64 	%rd11, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_4];
	ld.param.b64 	%rd12, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_6];
	ld.param.b64 	%rd13, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_7];
	ld.param.b64 	%rd14, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_8];
	ld.param.b64 	%rd15, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_15];
	ld.param.b64 	%rd16, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_16];
	ld.param.b32 	%r7, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_18];
	ld.param.b32 	%r8, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_19];
	mov.u32 	%r9, %tid.x;
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r1, %r10, %r11, %r9;
	mov.u32 	%r12, %tid.y;
	mov.u32 	%r13, %ntid.y;
	mov.u32 	%r14, %ctaid.y;
	mad.lo.s32 	%r15, %r13, %r14, %r12;
	max.s32 	%r16, %r1, %r15;
	setp.lt.s32 	%p4, %r16, %r8;
	@%p4 bra 	$L__BB0_2;
$L__BB0_1:
	ret;
$L__BB0_2:
	cvt.u64.u32 	%rd1, %r15;
	cvt.s64.s32 	%rd2, %r1;
	setp.lt.s32 	%p5, %r1, 0;
	selp.b64 	%rd17, %rd12, 0, %p5;
	add.s64 	%rd18, %rd17, %rd2;
	mul.lo.s64 	%rd19, %rd14, %rd18;
	mad.lo.s64 	%rd20, %rd13, %rd1, %rd11;
	add.s64 	%rd21, %rd20, %rd19;
	ld.b32 	%r50, [%rd21];
	cvt.u64.u32 	%rd3, %r8;
	add.s64 	%rd4, %rd3, %rd1;
	add.s64 	%rd22, %rd19, %rd11;
	mad.lo.s64 	%rd23, %rd4, %rd13, %rd22;
	ld.b32 	%r49, [%rd23];
	setp.eq.b32 	%p6, %r50, -1;
	setp.eq.b32 	%p7, %r49, -1;
	or.pred 	%p8, %p6, %p7;
	mov.b32 	%r48, 2147483647;
	@%p8 bra 	$L__BB0_4;
	sub.s32 	%r17, %r1, %r50;
	sub.s32 	%r18, %r15, %r49;
	mul.lo.s32 	%r19, %r17, %r17;
	mad.lo.s32 	%r48, %r18, %r18, %r19;
$L__BB0_4:
	sub.s32 	%r20, %r1, %r7;
	setp.gt.s32 	%p9, %r20, -1;
	setp.lt.s32 	%p10, %r20, %r8;
	and.pred 	%p1, %p9, %p10;
	cvt.u64.u32 	%rd24, %r20;
	mul.lo.s64 	%rd5, %rd14, %rd24;
	cvt.u64.u32 	%rd25, %r1;
	mul.lo.s64 	%rd6, %rd14, %rd25;
	add.s32 	%r21, %r7, %r1;
	setp.gt.s32 	%p11, %r21, -1;
	setp.lt.s32 	%p12, %r21, %r8;
	and.pred 	%p2, %p11, %p12;
	cvt.u64.u32 	%rd26, %r21;
	mul.lo.s64 	%rd7, %rd14, %rd26;
	mov.b64 	%rd8, 0;
$L__BB0_5:
	mov.b32 	%r51, -1;
	mov.pred 	%p49, 0;
	setp.eq.b64 	%p13, %rd8, 2;
	@%p13 bra 	$L__BB0_26;
	setp.eq.b64 	%p14, %rd8, 1;
	@%p14 bra 	$L__BB0_25;
$L__BB0_7:
	add.s64 	%rd8, %rd8, 1;
	mad.lo.s32 	%r22, %r51, %r7, %r15;
	setp.gt.s32 	%p15, %r22, -1;
	setp.lt.s32 	%p16, %r22, %r8;
	and.pred 	%p3, %p15, %p16;
	cvt.u64.u32 	%rd27, %r22;
	mad.lo.s64 	%rd9, %rd13, %rd27, %rd11;
	add.s64 	%rd28, %rd27, %rd3;
	mad.lo.s64 	%rd10, %rd28, %rd13, %rd11;
	@%p49 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_14;
$L__BB0_8:
	and.pred 	%p36, %p1, %p3;
	@%p36 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_11;
$L__BB0_9:
	add.s64 	%rd35, %rd9, %rd5;
	ld.b32 	%r2, [%rd35];
	add.s64 	%rd36, %rd10, %rd5;
	ld.b32 	%r38, [%rd36];
	setp.eq.b32 	%p37, %r2, -1;
	setp.eq.b32 	%p38, %r38, -1;
	or.pred 	%p39, %p37, %p38;
	@%p39 bra 	$L__BB0_11;
	sub.s32 	%r39, %r1, %r2;
	sub.s32 	%r40, %r15, %r38;
	mul.lo.s32 	%r41, %r39, %r39;
	mad.lo.s32 	%r42, %r40, %r40, %r41;
	setp.lt.s32 	%p40, %r42, %r48;
	min.s32 	%r48, %r42, %r48;
	selp.b32 	%r49, %r38, %r49, %p40;
	selp.b32 	%r50, %r2, %r50, %p40;
$L__BB0_11:
	and.pred 	%p41, %p2, %p3;
	not.pred 	%p42, %p41;
	@%p42 bra 	$L__BB0_23;
	add.s64 	%rd37, %rd9, %rd7;
	ld.b32 	%r3, [%rd37];
	add.s64 	%rd38, %rd10, %rd7;
	ld.b32 	%r43, [%rd38];
	setp.eq.b32 	%p43, %r3, -1;
	setp.eq.b32 	%p44, %r43, -1;
	or.pred 	%p45, %p43, %p44;
	@%p45 bra 	$L__BB0_23;
	sub.s32 	%r44, %r1, %r3;
	sub.s32 	%r45, %r15, %r43;
	mul.lo.s32 	%r46, %r44, %r44;
	mad.lo.s32 	%r47, %r45, %r45, %r46;
	setp.lt.s32 	%p46, %r47, %r48;
	min.s32 	%r48, %r47, %r48;
	selp.b32 	%r49, %r43, %r49, %p46;
	selp.b32 	%r50, %r3, %r50, %p46;
	bra.uni 	$L__BB0_23;
$L__BB0_14:
	and.pred 	%p17, %p1, %p3;
	not.pred 	%p18, %p17;
	@%p18 bra 	$L__BB0_17;
	add.s64 	%rd29, %rd9, %rd5;
	ld.b32 	%r4, [%rd29];
	add.s64 	%rd30, %rd10, %rd5;
	ld.b32 	%r23, [%rd30];
	setp.eq.b32 	%p19, %r4, -1;
	setp.eq.b32 	%p20, %r23, -1;
	or.pred 	%p21, %p19, %p20;
	@%p21 bra 	$L__BB0_17;
	sub.s32 	%r24, %r1, %r4;
	sub.s32 	%r25, %r15, %r23;
	mul.lo.s32 	%r26, %r24, %r24;
	mad.lo.s32 	%r27, %r25, %r25, %r26;
	setp.lt.s32 	%p22, %r27, %r48;
	min.s32 	%r48, %r27, %r48;
	selp.b32 	%r49, %r23, %r49, %p22;
	selp.b32 	%r50, %r4, %r50, %p22;
$L__BB0_17:
	setp.lt.s32 	%p23, %r1, 0;
	not.pred 	%p24, %p3;
	or.pred 	%p25, %p23, %p24;
	@%p25 bra 	$L__BB0_20;
	add.s64 	%rd31, %rd9, %rd6;
	ld.b32 	%r5, [%rd31];
	add.s64 	%rd32, %rd10, %rd6;
	ld.b32 	%r28, [%rd32];
	setp.eq.b32 	%p26, %r5, -1;
	setp.eq.b32 	%p27, %r28, -1;
	or.pred 	%p28, %p26, %p27;
	@%p28 bra 	$L__BB0_20;
	sub.s32 	%r29, %r1, %r5;
	sub.s32 	%r30, %r15, %r28;
	mul.lo.s32 	%r31, %r29, %r29;
	mad.lo.s32 	%r32, %r30, %r30, %r31;
	setp.lt.s32 	%p29, %r32, %r48;
	min.s32 	%r48, %r32, %r48;
	selp.b32 	%r49, %r28, %r49, %p29;
	selp.b32 	%r50, %r5, %r50, %p29;
$L__BB0_20:
	and.pred 	%p30, %p2, %p3;
	not.pred 	%p31, %p30;
	@%p31 bra 	$L__BB0_23;
	add.s64 	%rd33, %rd9, %rd7;
	ld.b32 	%r6, [%rd33];
	add.s64 	%rd34, %rd10, %rd7;
	ld.b32 	%r33, [%rd34];
	setp.eq.b32 	%p32, %r6, -1;
	setp.eq.b32 	%p33, %r33, -1;
	or.pred 	%p34, %p32, %p33;
	@%p34 bra 	$L__BB0_23;
	sub.s32 	%r34, %r1, %r6;
	sub.s32 	%r35, %r15, %r33;
	mul.lo.s32 	%r36, %r34, %r34;
	mad.lo.s32 	%r37, %r35, %r35, %r36;
	setp.lt.s32 	%p35, %r37, %r48;
	min.s32 	%r48, %r37, %r48;
	selp.b32 	%r49, %r33, %r49, %p35;
	selp.b32 	%r50, %r6, %r50, %p35;
$L__BB0_23:
	setp.eq.b64 	%p47, %rd8, 3;
	@%p47 bra 	$L__BB0_24;
	bra.uni 	$L__BB0_5;
$L__BB0_24:
	ld.param.b64 	%rd47, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_17];
	ld.param.b64 	%rd46, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v87B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_13];
	setp.lt.s32 	%p48, %r1, 0;
	selp.b64 	%rd39, %rd15, 0, %p48;
	add.s64 	%rd40, %rd39, %rd2;
	mul.lo.s64 	%rd41, %rd47, %rd40;
	mad.lo.s64 	%rd42, %rd16, %rd1, %rd46;
	add.s64 	%rd43, %rd42, %rd41;
	st.b32 	[%rd43], %r50;
	add.s64 	%rd44, %rd41, %rd46;
	mad.lo.s64 	%rd45, %rd4, %rd16, %rd44;
	st.b32 	[%rd45], %r49;
	bra.uni 	$L__BB0_1;
$L__BB0_25:
	mov.b32 	%r51, 0;
	mov.pred 	%p49, -1;
	bra.uni 	$L__BB0_7;
$L__BB0_26:
	mov.b32 	%r51, 1;
	bra.uni 	$L__BB0_7;

}