//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;

.visible .entry _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 .ptr .align 1 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 .ptr .align 1 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 .ptr .align 1 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 .ptr .align 1 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 .ptr .align 1 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 .ptr .align 1 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<58>;
	.reg .b32 	%r<132>;
	.reg .b64 	%rd<63>;

	ld.param.b64 	%rd7, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.b64 	%rd8, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.b64 	%rd9, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.b64 	%rd10, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.b64 	%rd11, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.b64 	%rd12, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.b64 	%rd13, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	ld.param.b64 	%rd14, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.b64 	%rd15, [_ZN5task546_voroni_square_euclidean_fast_warp_shfl_kernelB3v67B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	mov.u32 	%r5, %tid.x;
	cvt.u64.u32 	%rd16, %r5;
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mul.wide.u32 	%rd17, %r6, %r7;
	add.s64 	%rd1, %rd17, %rd16;
	mov.u32 	%r8, %tid.y;
	mov.u32 	%r9, %ntid.y;
	mov.u32 	%r10, %ctaid.y;
	mad.lo.s32 	%r1, %r9, %r10, %r8;
	cvt.u64.u32 	%rd2, %r1;
	mad.lo.s32 	%r2, %r8, %r6, %r5;
	shr.u32 	%r11, %r2, 1;
	and.b32 	%r12, %r11, 15;
	cvt.u64.u32 	%rd3, %r12;
	add.s64 	%rd18, %rd8, 15;
	shr.u64 	%rd19, %rd18, 4;
	setp.gt.s64 	%p1, %rd8, 0;
	selp.b64 	%rd20, %rd19, 0, %p1;
	setp.eq.b64 	%p2, %rd20, 0;
	setp.ne.b64 	%p3, %rd20, 0;
	selp.b64 	%rd21, -1, 0, %p3;
	add.s64 	%rd60, %rd20, %rd21;
	mov.b32 	%r130, 0;
	@%p2 bra 	$L__BB0_6;
	cvt.rn.f32.u64 	%r13, %rd12;
	cvt.rn.f32.u64 	%r14, %rd1;
	div.approx.ftz.f32 	%r3, %r14, %r13;
	cvt.rn.f32.s64 	%r15, %rd13;
	cvt.rn.f32.u32 	%r16, %r1;
	div.approx.ftz.f32 	%r4, %r16, %r15;
	and.b32 	%r17, %r2, 1;
	setp.ne.b32 	%p4, %r17, 0;
	selp.b64 	%rd22, %rd10, 0, %p4;
	add.s64 	%rd4, %rd22, %rd7;
	mov.b32 	%r129, 0f7F800000;
	mov.b64 	%rd61, 0;
	mov.b64 	%rd62, %rd61;
$L__BB0_2:
	add.s64 	%rd5, %rd3, %rd61;
	setp.ge.s64 	%p5, %rd5, %rd8;
	mov.b32 	%r131, 2139095040;
	@%p5 bra 	$L__BB0_4;
	shr.s64 	%rd23, %rd5, 63;
	and.b64 	%rd24, %rd23, %rd8;
	add.s64 	%rd25, %rd3, %rd24;
	add.s64 	%rd26, %rd25, %rd61;
	mad.lo.s64 	%rd27, %rd26, %rd9, %rd4;
	ld.b32 	%r131, [%rd27];
$L__BB0_4:
	shfl.sync.idx.b32 	%r18|%p6, %r131, 0, 31, -1;
	shfl.sync.idx.b32 	%r19|%p7, %r131, 1, 31, -1;
	sub.ftz.f32 	%r20, %r3, %r18;
	sub.ftz.f32 	%r21, %r4, %r19;
	mul.ftz.f32 	%r22, %r21, %r21;
	fma.rn.ftz.f32 	%r23, %r20, %r20, %r22;
	setp.lt.ftz.f32 	%p8, %r23, %r129;
	selp.b64 	%rd28, %rd61, %rd62, %p8;
	selp.f32 	%r24, %r23, %r129, %p8;
	shfl.sync.idx.b32 	%r25|%p9, %r131, 2, 31, -1;
	shfl.sync.idx.b32 	%r26|%p10, %r131, 3, 31, -1;
	sub.ftz.f32 	%r27, %r3, %r25;
	sub.ftz.f32 	%r28, %r4, %r26;
	mul.ftz.f32 	%r29, %r28, %r28;
	fma.rn.ftz.f32 	%r30, %r27, %r27, %r29;
	setp.lt.ftz.f32 	%p11, %r30, %r24;
	add.s64 	%rd29, %rd61, 1;
	selp.b64 	%rd30, %rd29, %rd28, %p11;
	selp.f32 	%r31, %r30, %r24, %p11;
	shfl.sync.idx.b32 	%r32|%p12, %r131, 4, 31, -1;
	shfl.sync.idx.b32 	%r33|%p13, %r131, 5, 31, -1;
	sub.ftz.f32 	%r34, %r3, %r32;
	sub.ftz.f32 	%r35, %r4, %r33;
	mul.ftz.f32 	%r36, %r35, %r35;
	fma.rn.ftz.f32 	%r37, %r34, %r34, %r36;
	setp.lt.ftz.f32 	%p14, %r37, %r31;
	add.s64 	%rd31, %rd61, 2;
	selp.b64 	%rd32, %rd31, %rd30, %p14;
	selp.f32 	%r38, %r37, %r31, %p14;
	shfl.sync.idx.b32 	%r39|%p15, %r131, 6, 31, -1;
	shfl.sync.idx.b32 	%r40|%p16, %r131, 7, 31, -1;
	sub.ftz.f32 	%r41, %r3, %r39;
	sub.ftz.f32 	%r42, %r4, %r40;
	mul.ftz.f32 	%r43, %r42, %r42;
	fma.rn.ftz.f32 	%r44, %r41, %r41, %r43;
	setp.lt.ftz.f32 	%p17, %r44, %r38;
	add.s64 	%rd33, %rd61, 3;
	selp.b64 	%rd34, %rd33, %rd32, %p17;
	selp.f32 	%r45, %r44, %r38, %p17;
	shfl.sync.idx.b32 	%r46|%p18, %r131, 8, 31, -1;
	shfl.sync.idx.b32 	%r47|%p19, %r131, 9, 31, -1;
	sub.ftz.f32 	%r48, %r3, %r46;
	sub.ftz.f32 	%r49, %r4, %r47;
	mul.ftz.f32 	%r50, %r49, %r49;
	fma.rn.ftz.f32 	%r51, %r48, %r48, %r50;
	setp.lt.ftz.f32 	%p20, %r51, %r45;
	add.s64 	%rd35, %rd61, 4;
	selp.b64 	%rd36, %rd35, %rd34, %p20;
	selp.f32 	%r52, %r51, %r45, %p20;
	shfl.sync.idx.b32 	%r53|%p21, %r131, 10, 31, -1;
	shfl.sync.idx.b32 	%r54|%p22, %r131, 11, 31, -1;
	sub.ftz.f32 	%r55, %r3, %r53;
	sub.ftz.f32 	%r56, %r4, %r54;
	mul.ftz.f32 	%r57, %r56, %r56;
	fma.rn.ftz.f32 	%r58, %r55, %r55, %r57;
	setp.lt.ftz.f32 	%p23, %r58, %r52;
	add.s64 	%rd37, %rd61, 5;
	selp.b64 	%rd38, %rd37, %rd36, %p23;
	selp.f32 	%r59, %r58, %r52, %p23;
	shfl.sync.idx.b32 	%r60|%p24, %r131, 12, 31, -1;
	shfl.sync.idx.b32 	%r61|%p25, %r131, 13, 31, -1;
	sub.ftz.f32 	%r62, %r3, %r60;
	sub.ftz.f32 	%r63, %r4, %r61;
	mul.ftz.f32 	%r64, %r63, %r63;
	fma.rn.ftz.f32 	%r65, %r62, %r62, %r64;
	setp.lt.ftz.f32 	%p26, %r65, %r59;
	add.s64 	%rd39, %rd61, 6;
	selp.b64 	%rd40, %rd39, %rd38, %p26;
	selp.f32 	%r66, %r65, %r59, %p26;
	shfl.sync.idx.b32 	%r67|%p27, %r131, 14, 31, -1;
	shfl.sync.idx.b32 	%r68|%p28, %r131, 15, 31, -1;
	sub.ftz.f32 	%r69, %r3, %r67;
	sub.ftz.f32 	%r70, %r4, %r68;
	mul.ftz.f32 	%r71, %r70, %r70;
	fma.rn.ftz.f32 	%r72, %r69, %r69, %r71;
	setp.lt.ftz.f32 	%p29, %r72, %r66;
	add.s64 	%rd41, %rd61, 7;
	selp.b64 	%rd42, %rd41, %rd40, %p29;
	selp.f32 	%r73, %r72, %r66, %p29;
	shfl.sync.idx.b32 	%r74|%p30, %r131, 16, 31, -1;
	shfl.sync.idx.b32 	%r75|%p31, %r131, 17, 31, -1;
	sub.ftz.f32 	%r76, %r3, %r74;
	sub.ftz.f32 	%r77, %r4, %r75;
	mul.ftz.f32 	%r78, %r77, %r77;
	fma.rn.ftz.f32 	%r79, %r76, %r76, %r78;
	setp.lt.ftz.f32 	%p32, %r79, %r73;
	add.s64 	%rd43, %rd61, 8;
	selp.b64 	%rd44, %rd43, %rd42, %p32;
	selp.f32 	%r80, %r79, %r73, %p32;
	shfl.sync.idx.b32 	%r81|%p33, %r131, 18, 31, -1;
	shfl.sync.idx.b32 	%r82|%p34, %r131, 19, 31, -1;
	sub.ftz.f32 	%r83, %r3, %r81;
	sub.ftz.f32 	%r84, %r4, %r82;
	mul.ftz.f32 	%r85, %r84, %r84;
	fma.rn.ftz.f32 	%r86, %r83, %r83, %r85;
	setp.lt.ftz.f32 	%p35, %r86, %r80;
	add.s64 	%rd45, %rd61, 9;
	selp.b64 	%rd46, %rd45, %rd44, %p35;
	selp.f32 	%r87, %r86, %r80, %p35;
	shfl.sync.idx.b32 	%r88|%p36, %r131, 20, 31, -1;
	shfl.sync.idx.b32 	%r89|%p37, %r131, 21, 31, -1;
	sub.ftz.f32 	%r90, %r3, %r88;
	sub.ftz.f32 	%r91, %r4, %r89;
	mul.ftz.f32 	%r92, %r91, %r91;
	fma.rn.ftz.f32 	%r93, %r90, %r90, %r92;
	setp.lt.ftz.f32 	%p38, %r93, %r87;
	add.s64 	%rd47, %rd61, 10;
	selp.b64 	%rd48, %rd47, %rd46, %p38;
	selp.f32 	%r94, %r93, %r87, %p38;
	shfl.sync.idx.b32 	%r95|%p39, %r131, 22, 31, -1;
	shfl.sync.idx.b32 	%r96|%p40, %r131, 23, 31, -1;
	sub.ftz.f32 	%r97, %r3, %r95;
	sub.ftz.f32 	%r98, %r4, %r96;
	mul.ftz.f32 	%r99, %r98, %r98;
	fma.rn.ftz.f32 	%r100, %r97, %r97, %r99;
	setp.lt.ftz.f32 	%p41, %r100, %r94;
	add.s64 	%rd49, %rd61, 11;
	selp.b64 	%rd50, %rd49, %rd48, %p41;
	selp.f32 	%r101, %r100, %r94, %p41;
	shfl.sync.idx.b32 	%r102|%p42, %r131, 24, 31, -1;
	shfl.sync.idx.b32 	%r103|%p43, %r131, 25, 31, -1;
	sub.ftz.f32 	%r104, %r3, %r102;
	sub.ftz.f32 	%r105, %r4, %r103;
	mul.ftz.f32 	%r106, %r105, %r105;
	fma.rn.ftz.f32 	%r107, %r104, %r104, %r106;
	setp.lt.ftz.f32 	%p44, %r107, %r101;
	add.s64 	%rd51, %rd61, 12;
	selp.b64 	%rd52, %rd51, %rd50, %p44;
	selp.f32 	%r108, %r107, %r101, %p44;
	shfl.sync.idx.b32 	%r109|%p45, %r131, 26, 31, -1;
	shfl.sync.idx.b32 	%r110|%p46, %r131, 27, 31, -1;
	sub.ftz.f32 	%r111, %r3, %r109;
	sub.ftz.f32 	%r112, %r4, %r110;
	mul.ftz.f32 	%r113, %r112, %r112;
	fma.rn.ftz.f32 	%r114, %r111, %r111, %r113;
	setp.lt.ftz.f32 	%p47, %r114, %r108;
	add.s64 	%rd53, %rd61, 13;
	selp.b64 	%rd54, %rd53, %rd52, %p47;
	selp.f32 	%r115, %r114, %r108, %p47;
	shfl.sync.idx.b32 	%r116|%p48, %r131, 28, 31, -1;
	shfl.sync.idx.b32 	%r117|%p49, %r131, 29, 31, -1;
	sub.ftz.f32 	%r118, %r3, %r116;
	sub.ftz.f32 	%r119, %r4, %r117;
	mul.ftz.f32 	%r120, %r119, %r119;
	fma.rn.ftz.f32 	%r121, %r118, %r118, %r120;
	setp.lt.ftz.f32 	%p50, %r121, %r115;
	add.s64 	%rd55, %rd61, 14;
	selp.b64 	%rd56, %rd55, %rd54, %p50;
	selp.f32 	%r122, %r121, %r115, %p50;
	shfl.sync.idx.b32 	%r123|%p51, %r131, 30, 31, -1;
	shfl.sync.idx.b32 	%r124|%p52, %r131, 31, 31, -1;
	sub.ftz.f32 	%r125, %r3, %r123;
	sub.ftz.f32 	%r126, %r4, %r124;
	mul.ftz.f32 	%r127, %r126, %r126;
	fma.rn.ftz.f32 	%r128, %r125, %r125, %r127;
	setp.lt.ftz.f32 	%p53, %r128, %r122;
	add.s64 	%rd57, %rd61, 15;
	selp.b64 	%rd62, %rd57, %rd56, %p53;
	selp.f32 	%r129, %r128, %r122, %p53;
	add.s64 	%rd6, %rd60, -1;
	setp.gt.s64 	%p54, %rd60, 0;
	add.s64 	%rd61, %rd61, 16;
	mov.b64 	%rd60, %rd6;
	@%p54 bra 	$L__BB0_2;
	cvt.u32.u64 	%r130, %rd62;
$L__BB0_6:
	setp.lt.u64 	%p55, %rd1, %rd12;
	setp.gt.s64 	%p56, %rd13, %rd2;
	and.pred 	%p57, %p55, %p56;
	@%p57 bra 	$L__BB0_8;
$L__BB0_7:
	ret;
$L__BB0_8:
	mad.lo.s64 	%rd58, %rd14, %rd1, %rd11;
	mad.lo.s64 	%rd59, %rd15, %rd2, %rd58;
	st.b32 	[%rd59], %r130;
	bra.uni 	$L__BB0_7;

}