//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;
.visible .shared .align 4 .b8 _cudapy_smem_1[64];

.visible .entry _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 .ptr .align 1 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 .ptr .align 1 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 .ptr .align 1 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 .ptr .align 1 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 .ptr .align 1 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 .ptr .align 1 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<34>;
	.reg .b32 	%r<178>;
	.reg .b64 	%rd<54>;

	ld.param.b64 	%rd9, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.b64 	%rd10, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.b64 	%rd11, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.b64 	%rd12, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.b64 	%rd13, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.b64 	%rd14, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.b64 	%rd15, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	ld.param.b64 	%rd16, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.b64 	%rd17, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v54B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	mov.u32 	%r5, %tid.x;
	cvt.u64.u32 	%rd18, %r5;
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mul.wide.u32 	%rd19, %r6, %r7;
	add.s64 	%rd1, %rd19, %rd18;
	mov.u32 	%r8, %tid.y;
	mov.u32 	%r9, %ntid.y;
	mov.u32 	%r10, %ctaid.y;
	mad.lo.s32 	%r1, %r9, %r10, %r8;
	cvt.u64.u32 	%rd2, %r1;
	mad.lo.s32 	%r11, %r8, %r6, %r5;
	cvt.u64.u32 	%rd3, %r11;
	shr.u64 	%rd4, %rd3, 1;
	add.s64 	%rd20, %rd10, 7;
	shr.u64 	%rd21, %rd20, 3;
	setp.gt.s64 	%p1, %rd10, 0;
	selp.b64 	%rd22, %rd21, 0, %p1;
	setp.eq.b64 	%p2, %rd22, 0;
	setp.ne.b64 	%p3, %rd22, 0;
	selp.b64 	%rd23, -1, 0, %p3;
	add.s64 	%rd51, %rd22, %rd23;
	mov.b32 	%r177, 0;
	@%p2 bra 	$L__BB0_8;
	cvt.rn.f32.u64 	%r12, %rd14;
	cvt.rn.f32.u64 	%r13, %rd1;
	div.rn.f32 	%r2, %r13, %r12;
	cvt.rn.f32.s64 	%r14, %rd15;
	cvt.rn.f32.u32 	%r15, %r1;
	div.rn.f32 	%r3, %r15, %r14;
	cvt.u32.u64 	%r4, %rd3;
	and.b64 	%rd24, %rd3, 1;
	shl.b64 	%rd25, %rd3, 2;
	and.b64 	%rd26, %rd25, 60;
	mov.b64 	%rd27, _cudapy_smem_1;
	add.s64 	%rd5, %rd27, %rd26;
	mad.lo.s64 	%rd6, %rd12, %rd24, %rd9;
	mov.b32 	%r176, 0f7F800000;
	mov.b64 	%rd52, 0;
	mov.b64 	%rd53, %rd52;
$L__BB0_2:
	mov.b64 	%rd7, %rd51;
	setp.gt.u32 	%p4, %r4, 15;
	@%p4 bra 	$L__BB0_6;
	add.s64 	%rd8, %rd4, %rd52;
	setp.ge.s64 	%p5, %rd8, %rd10;
	@%p5 bra 	$L__BB0_5;
	shr.s64 	%rd28, %rd8, 63;
	and.b64 	%rd29, %rd28, %rd10;
	add.s64 	%rd30, %rd4, %rd29;
	add.s64 	%rd31, %rd30, %rd52;
	mad.lo.s64 	%rd32, %rd31, %rd11, %rd6;
	ld.b32 	%r16, [%rd32];
	st.shared.b32 	[%rd5], %r16;
	bra.uni 	$L__BB0_6;
$L__BB0_5:
	st.shared.b32 	[%rd5], 2139095040;
$L__BB0_6:
	bar.sync 	0;
	ld.shared.b32 	%r17, [_cudapy_smem_1];
	mov.b64 	%rd33, _cudapy_smem_1;
	cvta.shared.u64 	%rd34, %rd33;
	ld.b32 	%r18, [%rd34+4];
	sub.f32 	%r19, %r2, %r17;
	sub.f32 	%r20, %r3, %r18;
	abs.f32 	%r21, %r19;
	abs.f32 	%r22, %r20;
	min.s32 	%r23, %r22, %r21;
	max.s32 	%r24, %r21, %r22;
	and.b32 	%r25, %r24, -33554432;
	xor.b32 	%r26, %r25, 2122317824;
	mul.f32 	%r27, %r23, %r26;
	mul.f32 	%r28, %r24, %r26;
	mul.f32 	%r29, %r27, %r27;
	fma.rn.f32 	%r30, %r28, %r28, %r29;
	sqrt.rn.f32 	%r31, %r30;
	or.b32 	%r32, %r25, 8388608;
	mul.f32 	%r33, %r31, %r32;
	setp.eq.f32 	%p6, %r23, 0f00000000;
	selp.f32 	%r34, %r24, %r33, %p6;
	setp.eq.f32 	%p7, %r23, 0f7F800000;
	selp.f32 	%r35, 0f7F800000, %r34, %p7;
	setp.lt.f32 	%p8, %r35, %r176;
	selp.b64 	%rd35, %rd52, %rd53, %p8;
	selp.f32 	%r36, %r35, %r176, %p8;
	ld.shared.b32 	%r37, [_cudapy_smem_1+8];
	ld.b32 	%r38, [%rd34+12];
	sub.f32 	%r39, %r2, %r37;
	sub.f32 	%r40, %r3, %r38;
	abs.f32 	%r41, %r39;
	abs.f32 	%r42, %r40;
	min.s32 	%r43, %r42, %r41;
	max.s32 	%r44, %r41, %r42;
	and.b32 	%r45, %r44, -33554432;
	xor.b32 	%r46, %r45, 2122317824;
	mul.f32 	%r47, %r43, %r46;
	mul.f32 	%r48, %r44, %r46;
	mul.f32 	%r49, %r47, %r47;
	fma.rn.f32 	%r50, %r48, %r48, %r49;
	sqrt.rn.f32 	%r51, %r50;
	or.b32 	%r52, %r45, 8388608;
	mul.f32 	%r53, %r51, %r52;
	setp.eq.f32 	%p9, %r43, 0f00000000;
	selp.f32 	%r54, %r44, %r53, %p9;
	setp.eq.f32 	%p10, %r43, 0f7F800000;
	selp.f32 	%r55, 0f7F800000, %r54, %p10;
	setp.lt.f32 	%p11, %r55, %r36;
	add.s64 	%rd36, %rd52, 1;
	selp.b64 	%rd37, %rd36, %rd35, %p11;
	selp.f32 	%r56, %r55, %r36, %p11;
	ld.shared.b32 	%r57, [_cudapy_smem_1+16];
	ld.b32 	%r58, [%rd34+20];
	sub.f32 	%r59, %r2, %r57;
	sub.f32 	%r60, %r3, %r58;
	abs.f32 	%r61, %r59;
	abs.f32 	%r62, %r60;
	min.s32 	%r63, %r62, %r61;
	max.s32 	%r64, %r61, %r62;
	and.b32 	%r65, %r64, -33554432;
	xor.b32 	%r66, %r65, 2122317824;
	mul.f32 	%r67, %r63, %r66;
	mul.f32 	%r68, %r64, %r66;
	mul.f32 	%r69, %r67, %r67;
	fma.rn.f32 	%r70, %r68, %r68, %r69;
	sqrt.rn.f32 	%r71, %r70;
	or.b32 	%r72, %r65, 8388608;
	mul.f32 	%r73, %r71, %r72;
	setp.eq.f32 	%p12, %r63, 0f00000000;
	selp.f32 	%r74, %r64, %r73, %p12;
	setp.eq.f32 	%p13, %r63, 0f7F800000;
	selp.f32 	%r75, 0f7F800000, %r74, %p13;
	setp.lt.f32 	%p14, %r75, %r56;
	add.s64 	%rd38, %rd52, 2;
	selp.b64 	%rd39, %rd38, %rd37, %p14;
	selp.f32 	%r76, %r75, %r56, %p14;
	ld.shared.b32 	%r77, [_cudapy_smem_1+24];
	ld.b32 	%r78, [%rd34+28];
	sub.f32 	%r79, %r2, %r77;
	sub.f32 	%r80, %r3, %r78;
	abs.f32 	%r81, %r79;
	abs.f32 	%r82, %r80;
	min.s32 	%r83, %r82, %r81;
	max.s32 	%r84, %r81, %r82;
	and.b32 	%r85, %r84, -33554432;
	xor.b32 	%r86, %r85, 2122317824;
	mul.f32 	%r87, %r83, %r86;
	mul.f32 	%r88, %r84, %r86;
	mul.f32 	%r89, %r87, %r87;
	fma.rn.f32 	%r90, %r88, %r88, %r89;
	sqrt.rn.f32 	%r91, %r90;
	or.b32 	%r92, %r85, 8388608;
	mul.f32 	%r93, %r91, %r92;
	setp.eq.f32 	%p15, %r83, 0f00000000;
	selp.f32 	%r94, %r84, %r93, %p15;
	setp.eq.f32 	%p16, %r83, 0f7F800000;
	selp.f32 	%r95, 0f7F800000, %r94, %p16;
	setp.lt.f32 	%p17, %r95, %r76;
	add.s64 	%rd40, %rd52, 3;
	selp.b64 	%rd41, %rd40, %rd39, %p17;
	selp.f32 	%r96, %r95, %r76, %p17;
	ld.shared.b32 	%r97, [_cudapy_smem_1+32];
	ld.b32 	%r98, [%rd34+36];
	sub.f32 	%r99, %r2, %r97;
	sub.f32 	%r100, %r3, %r98;
	abs.f32 	%r101, %r99;
	abs.f32 	%r102, %r100;
	min.s32 	%r103, %r102, %r101;
	max.s32 	%r104, %r101, %r102;
	and.b32 	%r105, %r104, -33554432;
	xor.b32 	%r106, %r105, 2122317824;
	mul.f32 	%r107, %r103, %r106;
	mul.f32 	%r108, %r104, %r106;
	mul.f32 	%r109, %r107, %r107;
	fma.rn.f32 	%r110, %r108, %r108, %r109;
	sqrt.rn.f32 	%r111, %r110;
	or.b32 	%r112, %r105, 8388608;
	mul.f32 	%r113, %r111, %r112;
	setp.eq.f32 	%p18, %r103, 0f00000000;
	selp.f32 	%r114, %r104, %r113, %p18;
	setp.eq.f32 	%p19, %r103, 0f7F800000;
	selp.f32 	%r115, 0f7F800000, %r114, %p19;
	setp.lt.f32 	%p20, %r115, %r96;
	add.s64 	%rd42, %rd52, 4;
	selp.b64 	%rd43, %rd42, %rd41, %p20;
	selp.f32 	%r116, %r115, %r96, %p20;
	ld.shared.b32 	%r117, [_cudapy_smem_1+40];
	ld.b32 	%r118, [%rd34+44];
	sub.f32 	%r119, %r2, %r117;
	sub.f32 	%r120, %r3, %r118;
	abs.f32 	%r121, %r119;
	abs.f32 	%r122, %r120;
	min.s32 	%r123, %r122, %r121;
	max.s32 	%r124, %r121, %r122;
	and.b32 	%r125, %r124, -33554432;
	xor.b32 	%r126, %r125, 2122317824;
	mul.f32 	%r127, %r123, %r126;
	mul.f32 	%r128, %r124, %r126;
	mul.f32 	%r129, %r127, %r127;
	fma.rn.f32 	%r130, %r128, %r128, %r129;
	sqrt.rn.f32 	%r131, %r130;
	or.b32 	%r132, %r125, 8388608;
	mul.f32 	%r133, %r131, %r132;
	setp.eq.f32 	%p21, %r123, 0f00000000;
	selp.f32 	%r134, %r124, %r133, %p21;
	setp.eq.f32 	%p22, %r123, 0f7F800000;
	selp.f32 	%r135, 0f7F800000, %r134, %p22;
	setp.lt.f32 	%p23, %r135, %r116;
	add.s64 	%rd44, %rd52, 5;
	selp.b64 	%rd45, %rd44, %rd43, %p23;
	selp.f32 	%r136, %r135, %r116, %p23;
	ld.shared.b32 	%r137, [_cudapy_smem_1+48];
	ld.b32 	%r138, [%rd34+52];
	sub.f32 	%r139, %r2, %r137;
	sub.f32 	%r140, %r3, %r138;
	abs.f32 	%r141, %r139;
	abs.f32 	%r142, %r140;
	min.s32 	%r143, %r142, %r141;
	max.s32 	%r144, %r141, %r142;
	and.b32 	%r145, %r144, -33554432;
	xor.b32 	%r146, %r145, 2122317824;
	mul.f32 	%r147, %r143, %r146;
	mul.f32 	%r148, %r144, %r146;
	mul.f32 	%r149, %r147, %r147;
	fma.rn.f32 	%r150, %r148, %r148, %r149;
	sqrt.rn.f32 	%r151, %r150;
	or.b32 	%r152, %r145, 8388608;
	mul.f32 	%r153, %r151, %r152;
	setp.eq.f32 	%p24, %r143, 0f00000000;
	selp.f32 	%r154, %r144, %r153, %p24;
	setp.eq.f32 	%p25, %r143, 0f7F800000;
	selp.f32 	%r155, 0f7F800000, %r154, %p25;
	setp.lt.f32 	%p26, %r155, %r136;
	add.s64 	%rd46, %rd52, 6;
	selp.b64 	%rd47, %rd46, %rd45, %p26;
	selp.f32 	%r156, %r155, %r136, %p26;
	ld.shared.b32 	%r157, [_cudapy_smem_1+56];
	ld.b32 	%r158, [%rd34+60];
	sub.f32 	%r159, %r2, %r157;
	sub.f32 	%r160, %r3, %r158;
	abs.f32 	%r161, %r159;
	abs.f32 	%r162, %r160;
	min.s32 	%r163, %r162, %r161;
	max.s32 	%r164, %r161, %r162;
	and.b32 	%r165, %r164, -33554432;
	xor.b32 	%r166, %r165, 2122317824;
	mul.f32 	%r167, %r163, %r166;
	mul.f32 	%r168, %r164, %r166;
	mul.f32 	%r169, %r167, %r167;
	fma.rn.f32 	%r170, %r168, %r168, %r169;
	sqrt.rn.f32 	%r171, %r170;
	or.b32 	%r172, %r165, 8388608;
	mul.f32 	%r173, %r171, %r172;
	setp.eq.f32 	%p27, %r163, 0f00000000;
	selp.f32 	%r174, %r164, %r173, %p27;
	setp.eq.f32 	%p28, %r163, 0f7F800000;
	selp.f32 	%r175, 0f7F800000, %r174, %p28;
	setp.lt.f32 	%p29, %r175, %r156;
	add.s64 	%rd48, %rd52, 7;
	selp.b64 	%rd53, %rd48, %rd47, %p29;
	selp.f32 	%r176, %r175, %r156, %p29;
	bar.sync 	0;
	add.s64 	%rd51, %rd7, -1;
	setp.gt.s64 	%p30, %rd7, 0;
	add.s64 	%rd52, %rd52, 8;
	@%p30 bra 	$L__BB0_2;
	cvt.u32.u64 	%r177, %rd53;
$L__BB0_8:
	setp.lt.u64 	%p31, %rd1, %rd14;
	setp.gt.s64 	%p32, %rd15, %rd2;
	and.pred 	%p33, %p31, %p32;
	@%p33 bra 	$L__BB0_10;
$L__BB0_9:
	ret;
$L__BB0_10:
	mad.lo.s64 	%rd49, %rd16, %rd1, %rd13;
	mad.lo.s64 	%rd50, %rd17, %rd2, %rd49;
	st.b32 	[%rd50], %r177;
	bra.uni 	$L__BB0_9;

}