//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii
.common .global .align 8 .u64 _ZN08NumbaEnv6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii;
.visible .shared .align 4 .b8 _cudapy_smem_3[4608];

.visible .entry _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii(
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_0,
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_1,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_2,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_3,
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_4,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_5,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_6,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_7,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_8,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_9,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_10,
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_11,
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_12,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_13,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_14,
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_15,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_16,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_17,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_18,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_19,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_20,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_21,
	.param .u32 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_22,
	.param .u32 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_23
)
{
	.reg .pred 	%p<115>;
	.reg .b32 	%r<58>;
	.reg .b64 	%rd<283>;

	ld.param.b64 	%rd39, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_4];
	ld.param.b64 	%rd40, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_5];
	ld.param.b64 	%rd41, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_6];
	ld.param.b64 	%rd42, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_8];
	ld.param.b64 	%rd43, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_9];
	ld.param.b64 	%rd44, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_10];
	ld.param.b64 	%rd45, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_20];
	ld.param.b32 	%r17, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_22];
	ld.param.b32 	%r18, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_23];
	mov.u32 	%r19, %tid.x;
	mov.u32 	%r1, %tid.y;
	cvt.u64.u32 	%rd1, %r19;
	mov.u32 	%r20, %ntid.x;
	mov.u32 	%r2, %ctaid.x;
	mul.wide.u32 	%rd46, %r20, %r2;
	add.s64 	%rd2, %rd46, %rd1;
	mov.u32 	%r21, %ntid.y;
	mov.u32 	%r3, %ctaid.y;
	mad.lo.s32 	%r22, %r21, %r3, %r1;
	cvt.u64.u32 	%rd3, %r22;
	setp.gt.s32 	%p4, %r17, 7;
	@%p4 bra 	$L__BB0_52;
	cvt.u32.u64 	%r28, %rd1;
	mul.wide.u32 	%rd104, %r2, 16;
	cvt.s64.s32 	%rd4, %r17;
	sub.s64 	%rd5, %rd104, %rd4;
	mul.wide.u32 	%rd105, %r3, 16;
	sub.s64 	%rd6, %rd105, %rd4;
	mul.wide.s32 	%rd106, %r17, 2;
	add.s64 	%rd7, %rd106, 16;
	mul.lo.s64 	%rd107, %rd7, %rd7;
	shl.b32 	%r29, %r1, 4;
	add.s32 	%r30, %r29, %r28;
	cvt.u64.u32 	%rd276, %r30;
	sub.s64 	%rd108, %rd107, %rd276;
	add.s64 	%rd109, %rd108, 255;
	shr.u64 	%rd110, %rd109, 8;
	setp.gt.s64 	%p52, %rd108, 0;
	selp.b64 	%rd111, %rd110, 0, %p52;
	setp.eq.b64 	%p53, %rd111, 0;
	setp.ne.b64 	%p54, %rd111, 0;
	selp.b64 	%rd112, -1, 0, %p54;
	add.s64 	%rd275, %rd111, %rd112;
	@%p53 bra 	$L__BB0_32;
	setp.eq.b64 	%p55, %rd7, 0;
	cvt.s64.s32 	%rd8, %r18;
	@%p55 bra 	$L__BB0_6;
	cvt.u32.u64 	%r31, %rd7;
$L__BB0_4:
	or.b64 	%rd113, %rd276, %rd7;
	and.b64 	%rd114, %rd113, -4294967296;
	setp.ne.b64 	%p56, %rd114, 0;
	@%p56 bra 	$L__BB0_27;
	cvt.u32.u64 	%r32, %rd276;
	div.u32 	%r33, %r32, %r31;
	mul.lo.s32 	%r34, %r33, %r31;
	sub.s32 	%r35, %r32, %r34;
	cvt.u64.u32 	%rd277, %r33;
	cvt.u64.u32 	%rd278, %r35;
	bra.uni 	$L__BB0_28;
$L__BB0_6:
	min.s64 	%rd9, %rd275, 0;
	sub.s64 	%rd148, %rd275, %rd9;
	add.s64 	%rd149, %rd148, 1;
	and.b64 	%rd274, %rd149, 3;
	setp.eq.b64 	%p64, %rd274, 0;
	@%p64 bra 	$L__BB0_12;
	or.b64 	%rd150, %rd5, %rd6;
	setp.gt.s64 	%p65, %rd150, -1;
	max.s64 	%rd151, %rd5, %rd6;
	setp.lt.s64 	%p66, %rd151, %rd8;
	and.pred 	%p1, %p66, %p65;
	mul.lo.s64 	%rd152, %rd5, %rd43;
	mad.lo.s64 	%rd153, %rd6, %rd42, %rd152;
	add.s64 	%rd10, %rd153, %rd39;
	add.s64 	%rd11, %rd10, %rd44;
$L__BB0_8:
	.pragma "nounroll";
	@%p1 bra 	$L__BB0_10;
	st.shared.b32 	[_cudapy_smem_3], -1;
	mov.b32 	%r50, -1;
	bra.uni 	$L__BB0_11;
$L__BB0_10:
	ld.b32 	%r37, [%rd10];
	st.shared.b32 	[_cudapy_smem_3], %r37;
	ld.b32 	%r50, [%rd11];
$L__BB0_11:
	st.shared.b32 	[_cudapy_smem_3+4], %r50;
	setp.gt.s64 	%p67, %rd275, 0;
	selp.b64 	%rd154, -1, 0, %p67;
	add.s64 	%rd275, %rd275, %rd154;
	add.s64 	%rd274, %rd274, -1;
	setp.ne.b64 	%p68, %rd274, 0;
	@%p68 bra 	$L__BB0_8;
$L__BB0_12:
	setp.lt.u64 	%p69, %rd148, 3;
	@%p69 bra 	$L__BB0_32;
	or.b64 	%rd155, %rd5, %rd6;
	setp.gt.s64 	%p70, %rd155, -1;
	max.s64 	%rd156, %rd5, %rd6;
	setp.lt.s64 	%p71, %rd156, %rd8;
	and.pred 	%p2, %p71, %p70;
	mul.lo.s64 	%rd157, %rd5, %rd43;
	mad.lo.s64 	%rd158, %rd6, %rd42, %rd157;
	add.s64 	%rd12, %rd158, %rd39;
	add.s64 	%rd13, %rd12, %rd44;
$L__BB0_14:
	@%p2 bra 	$L__BB0_16;
	st.shared.b32 	[_cudapy_smem_3], -1;
	mov.b32 	%r51, -1;
	bra.uni 	$L__BB0_17;
$L__BB0_16:
	ld.b32 	%r38, [%rd12];
	st.shared.b32 	[_cudapy_smem_3], %r38;
	ld.b32 	%r51, [%rd13];
$L__BB0_17:
	st.shared.b32 	[_cudapy_smem_3+4], %r51;
	@%p2 bra 	$L__BB0_19;
	st.shared.b32 	[_cudapy_smem_3], -1;
	mov.b32 	%r52, -1;
	bra.uni 	$L__BB0_20;
$L__BB0_19:
	ld.b32 	%r39, [%rd12];
	st.shared.b32 	[_cudapy_smem_3], %r39;
	ld.b32 	%r52, [%rd13];
$L__BB0_20:
	setp.gt.s64 	%p72, %rd275, 0;
	selp.b64 	%rd159, -1, 0, %p72;
	add.s64 	%rd14, %rd275, %rd159;
	st.shared.b32 	[_cudapy_smem_3+4], %r52;
	@%p2 bra 	$L__BB0_22;
	st.shared.b32 	[_cudapy_smem_3], -1;
	mov.b32 	%r53, -1;
	bra.uni 	$L__BB0_23;
$L__BB0_22:
	ld.b32 	%r40, [%rd12];
	st.shared.b32 	[_cudapy_smem_3], %r40;
	ld.b32 	%r53, [%rd13];
$L__BB0_23:
	setp.gt.s64 	%p73, %rd14, 0;
	selp.b64 	%rd160, -1, 0, %p73;
	add.s64 	%rd15, %rd14, %rd160;
	st.shared.b32 	[_cudapy_smem_3+4], %r53;
	@%p2 bra 	$L__BB0_25;
	st.shared.b32 	[_cudapy_smem_3], -1;
	mov.b32 	%r54, -1;
	bra.uni 	$L__BB0_26;
$L__BB0_25:
	ld.b32 	%r41, [%rd12];
	st.shared.b32 	[_cudapy_smem_3], %r41;
	ld.b32 	%r54, [%rd13];
$L__BB0_26:
	setp.gt.s64 	%p74, %rd15, 0;
	selp.b64 	%rd161, -1, 0, %p74;
	add.s64 	%rd162, %rd15, %rd161;
	st.shared.b32 	[_cudapy_smem_3+4], %r54;
	setp.gt.s64 	%p75, %rd162, 0;
	selp.b64 	%rd163, -1, 0, %p75;
	add.s64 	%rd275, %rd162, %rd163;
	@%p75 bra 	$L__BB0_14;
	bra.uni 	$L__BB0_32;
$L__BB0_27:
	div.s64 	%rd277, %rd276, %rd7;
	mul.lo.s64 	%rd115, %rd277, %rd7;
	sub.s64 	%rd278, %rd276, %rd115;
$L__BB0_28:
	xor.b64 	%rd116, %rd278, %rd7;
	setp.lt.s64 	%p57, %rd116, 0;
	setp.ne.b64 	%p58, %rd278, 0;
	and.pred 	%p59, %p58, %p57;
	selp.b64 	%rd117, %rd7, 0, %p59;
	add.s64 	%rd16, %rd117, %rd278;
	selp.b64 	%rd118, -1, 0, %p59;
	add.s64 	%rd17, %rd277, %rd118;
	add.s64 	%rd18, %rd16, %rd5;
	add.s64 	%rd19, %rd17, %rd6;
	or.b64 	%rd119, %rd18, %rd19;
	setp.lt.s64 	%p60, %rd119, 0;
	max.s64 	%rd120, %rd18, %rd19;
	setp.ge.s64 	%p61, %rd120, %rd8;
	or.pred 	%p62, %p61, %p60;
	@%p62 bra 	$L__BB0_30;
	mul.lo.s64 	%rd131, %rd18, %rd43;
	mad.lo.s64 	%rd132, %rd19, %rd42, %rd131;
	add.s64 	%rd133, %rd132, %rd39;
	ld.b32 	%r36, [%rd133];
	shr.s64 	%rd134, %rd17, 63;
	and.b64 	%rd135, %rd134, 24;
	add.s64 	%rd136, %rd135, %rd17;
	shr.s64 	%rd137, %rd16, 63;
	and.b64 	%rd138, %rd137, 24;
	add.s64 	%rd139, %rd138, %rd16;
	shl.b64 	%rd140, %rd139, 1;
	mad.lo.s64 	%rd279, %rd136, 48, %rd140;
	shl.b64 	%rd141, %rd279, 2;
	mov.b64 	%rd142, _cudapy_smem_3;
	add.s64 	%rd143, %rd142, %rd141;
	st.shared.b32 	[%rd143], %r36;
	add.s64 	%rd144, %rd133, %rd44;
	ld.b32 	%r55, [%rd144];
	bra.uni 	$L__BB0_31;
$L__BB0_30:
	shr.s64 	%rd121, %rd17, 63;
	and.b64 	%rd122, %rd121, 24;
	add.s64 	%rd123, %rd122, %rd17;
	shr.s64 	%rd124, %rd16, 63;
	and.b64 	%rd125, %rd124, 24;
	add.s64 	%rd126, %rd125, %rd16;
	shl.b64 	%rd127, %rd126, 1;
	mad.lo.s64 	%rd279, %rd123, 48, %rd127;
	shl.b64 	%rd128, %rd279, 2;
	mov.b64 	%rd129, _cudapy_smem_3;
	add.s64 	%rd130, %rd129, %rd128;
	st.shared.b32 	[%rd130], -1;
	mov.b32 	%r55, -1;
$L__BB0_31:
	shl.b64 	%rd145, %rd279, 2;
	mov.b64 	%rd146, _cudapy_smem_3;
	add.s64 	%rd147, %rd146, %rd145;
	st.shared.b32 	[%rd147+4], %r55;
	add.s64 	%rd20, %rd275, -1;
	add.s64 	%rd276, %rd276, 256;
	setp.gt.s64 	%p63, %rd275, 0;
	mov.b64 	%rd275, %rd20;
	@%p63 bra 	$L__BB0_4;
$L__BB0_32:
	bar.sync 	0;
	setp.ge.u64 	%p76, %rd2, %rd40;
	setp.le.u64 	%p77, %rd41, %rd3;
	or.pred 	%p78, %p76, %p77;
	@%p78 bra 	$L__BB0_33;
	bra.uni 	$L__BB0_34;
$L__BB0_33:
	ret;
$L__BB0_34:
	add.s64 	%rd21, %rd4, %rd1;
	cvt.u64.u32 	%rd22, %r1;
	add.s64 	%rd23, %rd4, %rd22;
	shr.s64 	%rd164, %rd23, 63;
	and.b64 	%rd165, %rd164, 24;
	add.s64 	%rd166, %rd165, %rd23;
	shr.s64 	%rd167, %rd21, 63;
	and.b64 	%rd168, %rd167, 24;
	add.s64 	%rd169, %rd168, %rd21;
	mul.lo.s64 	%rd24, %rd166, 48;
	shl.b64 	%rd25, %rd169, 1;
	add.s64 	%rd170, %rd24, %rd25;
	shl.b64 	%rd171, %rd170, 2;
	mov.b64 	%rd172, _cudapy_smem_3;
	add.s64 	%rd173, %rd172, %rd171;
	ld.shared.b32 	%r57, [%rd173];
	ld.shared.b32 	%r56, [%rd173+4];
	setp.eq.b32 	%p79, %r57, -1;
	setp.eq.b32 	%p80, %r56, -1;
	or.pred 	%p81, %p79, %p80;
	mov.b64 	%rd280, 9223372036854775807;
	@%p81 bra 	$L__BB0_36;
	cvt.s64.s32 	%rd174, %r57;
	sub.s64 	%rd175, %rd2, %rd174;
	cvt.s64.s32 	%rd176, %r56;
	sub.s64 	%rd177, %rd3, %rd176;
	mul.lo.s64 	%rd178, %rd175, %rd175;
	mad.lo.s64 	%rd280, %rd177, %rd177, %rd178;
$L__BB0_36:
	mul.lo.s64 	%rd34, %rd22, 48;
	shl.b64 	%rd35, %rd1, 1;
	add.s64 	%rd179, %rd35, %rd34;
	shl.b64 	%rd180, %rd179, 2;
	mov.b64 	%rd181, _cudapy_smem_3;
	add.s64 	%rd182, %rd181, %rd180;
	ld.shared.b32 	%r13, [%rd182];
	ld.shared.b32 	%r42, [%rd182+4];
	setp.eq.b32 	%p82, %r13, -1;
	setp.eq.b32 	%p83, %r42, -1;
	or.pred 	%p84, %p82, %p83;
	@%p84 bra 	$L__BB0_38;
	cvt.s64.s32 	%rd183, %r13;
	cvt.s64.s32 	%rd184, %r42;
	sub.s64 	%rd185, %rd2, %rd183;
	sub.s64 	%rd186, %rd3, %rd184;
	mul.lo.s64 	%rd187, %rd185, %rd185;
	mad.lo.s64 	%rd188, %rd186, %rd186, %rd187;
	setp.lt.s64 	%p85, %rd188, %rd280;
	min.s64 	%rd280, %rd188, %rd280;
	selp.b32 	%r56, %r42, %r56, %p85;
	selp.b32 	%r57, %r13, %r57, %p85;
$L__BB0_38:
	add.s64 	%rd189, %rd25, %rd34;
	shl.b64 	%rd190, %rd189, 2;
	mov.b64 	%rd191, _cudapy_smem_3;
	add.s64 	%rd192, %rd191, %rd190;
	ld.shared.b32 	%r4, [%rd192];
	ld.shared.b32 	%r43, [%rd192+4];
	setp.eq.b32 	%p86, %r4, -1;
	setp.eq.b32 	%p87, %r43, -1;
	or.pred 	%p88, %p86, %p87;
	@%p88 bra 	$L__BB0_40;
	cvt.s64.s32 	%rd193, %r4;
	cvt.s64.s32 	%rd194, %r43;
	sub.s64 	%rd195, %rd2, %rd193;
	sub.s64 	%rd196, %rd3, %rd194;
	mul.lo.s64 	%rd197, %rd195, %rd195;
	mad.lo.s64 	%rd198, %rd196, %rd196, %rd197;
	setp.lt.s64 	%p89, %rd198, %rd280;
	min.s64 	%rd280, %rd198, %rd280;
	selp.b32 	%r56, %r43, %r56, %p89;
	selp.b32 	%r57, %r4, %r57, %p89;
$L__BB0_40:
	add.s64 	%rd199, %rd21, %rd4;
	shr.s64 	%rd200, %rd199, 63;
	and.b64 	%rd201, %rd200, 24;
	add.s64 	%rd202, %rd201, %rd199;
	shl.b64 	%rd26, %rd202, 1;
	add.s64 	%rd203, %rd26, %rd34;
	shl.b64 	%rd204, %rd203, 2;
	mov.b64 	%rd205, _cudapy_smem_3;
	add.s64 	%rd206, %rd205, %rd204;
	ld.shared.b32 	%r5, [%rd206];
	ld.shared.b32 	%r44, [%rd206+4];
	setp.eq.b32 	%p90, %r5, -1;
	setp.eq.b32 	%p91, %r44, -1;
	or.pred 	%p92, %p90, %p91;
	@%p92 bra 	$L__BB0_42;
	cvt.s64.s32 	%rd207, %r5;
	cvt.s64.s32 	%rd208, %r44;
	sub.s64 	%rd209, %rd2, %rd207;
	sub.s64 	%rd210, %rd3, %rd208;
	mul.lo.s64 	%rd211, %rd209, %rd209;
	mad.lo.s64 	%rd212, %rd210, %rd210, %rd211;
	setp.lt.s64 	%p93, %rd212, %rd280;
	min.s64 	%rd280, %rd212, %rd280;
	selp.b32 	%r56, %r44, %r56, %p93;
	selp.b32 	%r57, %r5, %r57, %p93;
$L__BB0_42:
	add.s64 	%rd213, %rd35, %rd24;
	shl.b64 	%rd214, %rd213, 2;
	mov.b64 	%rd215, _cudapy_smem_3;
	add.s64 	%rd216, %rd215, %rd214;
	ld.shared.b32 	%r6, [%rd216];
	ld.shared.b32 	%r45, [%rd216+4];
	setp.eq.b32 	%p94, %r6, -1;
	setp.eq.b32 	%p95, %r45, -1;
	or.pred 	%p96, %p94, %p95;
	@%p96 bra 	$L__BB0_44;
	cvt.s64.s32 	%rd217, %r6;
	cvt.s64.s32 	%rd218, %r45;
	sub.s64 	%rd219, %rd2, %rd217;
	sub.s64 	%rd220, %rd3, %rd218;
	mul.lo.s64 	%rd221, %rd219, %rd219;
	mad.lo.s64 	%rd222, %rd220, %rd220, %rd221;
	setp.lt.s64 	%p97, %rd222, %rd280;
	min.s64 	%rd280, %rd222, %rd280;
	selp.b32 	%r56, %r45, %r56, %p97;
	selp.b32 	%r57, %r6, %r57, %p97;
$L__BB0_44:
	add.s64 	%rd223, %rd26, %rd24;
	shl.b64 	%rd224, %rd223, 2;
	mov.b64 	%rd225, _cudapy_smem_3;
	add.s64 	%rd226, %rd225, %rd224;
	ld.shared.b32 	%r7, [%rd226];
	ld.shared.b32 	%r46, [%rd226+4];
	setp.eq.b32 	%p98, %r7, -1;
	setp.eq.b32 	%p99, %r46, -1;
	or.pred 	%p100, %p98, %p99;
	@%p100 bra 	$L__BB0_46;
	cvt.s64.s32 	%rd227, %r7;
	cvt.s64.s32 	%rd228, %r46;
	sub.s64 	%rd229, %rd2, %rd227;
	sub.s64 	%rd230, %rd3, %rd228;
	mul.lo.s64 	%rd231, %rd229, %rd229;
	mad.lo.s64 	%rd232, %rd230, %rd230, %rd231;
	setp.lt.s64 	%p101, %rd232, %rd280;
	min.s64 	%rd280, %rd232, %rd280;
	selp.b32 	%r56, %r46, %r56, %p101;
	selp.b32 	%r57, %r7, %r57, %p101;
$L__BB0_46:
	add.s64 	%rd233, %rd23, %rd4;
	shr.s64 	%rd234, %rd233, 63;
	and.b64 	%rd235, %rd234, 24;
	add.s64 	%rd236, %rd235, %rd233;
	mul.lo.s64 	%rd27, %rd236, 48;
	add.s64 	%rd237, %rd35, %rd27;
	shl.b64 	%rd238, %rd237, 2;
	mov.b64 	%rd239, _cudapy_smem_3;
	add.s64 	%rd240, %rd239, %rd238;
	ld.shared.b32 	%r8, [%rd240];
	ld.shared.b32 	%r47, [%rd240+4];
	setp.eq.b32 	%p102, %r8, -1;
	setp.eq.b32 	%p103, %r47, -1;
	or.pred 	%p104, %p102, %p103;
	@%p104 bra 	$L__BB0_48;
	cvt.s64.s32 	%rd241, %r8;
	cvt.s64.s32 	%rd242, %r47;
	sub.s64 	%rd243, %rd2, %rd241;
	sub.s64 	%rd244, %rd3, %rd242;
	mul.lo.s64 	%rd245, %rd243, %rd243;
	mad.lo.s64 	%rd246, %rd244, %rd244, %rd245;
	setp.lt.s64 	%p105, %rd246, %rd280;
	min.s64 	%rd280, %rd246, %rd280;
	selp.b32 	%r56, %r47, %r56, %p105;
	selp.b32 	%r57, %r8, %r57, %p105;
$L__BB0_48:
	add.s64 	%rd247, %rd25, %rd27;
	shl.b64 	%rd248, %rd247, 2;
	mov.b64 	%rd249, _cudapy_smem_3;
	add.s64 	%rd250, %rd249, %rd248;
	ld.shared.b32 	%r9, [%rd250];
	ld.shared.b32 	%r48, [%rd250+4];
	setp.eq.b32 	%p106, %r9, -1;
	setp.eq.b32 	%p107, %r48, -1;
	or.pred 	%p108, %p106, %p107;
	@%p108 bra 	$L__BB0_50;
	cvt.s64.s32 	%rd251, %r9;
	cvt.s64.s32 	%rd252, %r48;
	sub.s64 	%rd253, %rd2, %rd251;
	sub.s64 	%rd254, %rd3, %rd252;
	mul.lo.s64 	%rd255, %rd253, %rd253;
	mad.lo.s64 	%rd256, %rd254, %rd254, %rd255;
	setp.lt.s64 	%p109, %rd256, %rd280;
	min.s64 	%rd280, %rd256, %rd280;
	selp.b32 	%r56, %r48, %r56, %p109;
	selp.b32 	%r57, %r9, %r57, %p109;
$L__BB0_50:
	add.s64 	%rd257, %rd26, %rd27;
	shl.b64 	%rd258, %rd257, 2;
	mov.b64 	%rd259, _cudapy_smem_3;
	add.s64 	%rd260, %rd259, %rd258;
	ld.shared.b32 	%r10, [%rd260];
	ld.shared.b32 	%r49, [%rd260+4];
	setp.eq.b32 	%p110, %r10, -1;
	setp.eq.b32 	%p111, %r49, -1;
	or.pred 	%p112, %p110, %p111;
	@%p112 bra 	$L__BB0_75;
	cvt.s64.s32 	%rd261, %r10;
	cvt.s64.s32 	%rd262, %r49;
	sub.s64 	%rd263, %rd2, %rd261;
	sub.s64 	%rd264, %rd3, %rd262;
	mul.lo.s64 	%rd265, %rd263, %rd263;
	mad.lo.s64 	%rd266, %rd264, %rd264, %rd265;
	setp.lt.s64 	%p113, %rd266, %rd280;
	selp.b32 	%r56, %r49, %r56, %p113;
	selp.b32 	%r57, %r10, %r57, %p113;
	bra.uni 	$L__BB0_75;
$L__BB0_52:
	setp.ge.u64 	%p5, %rd2, %rd40;
	setp.le.u64 	%p6, %rd41, %rd3;
	or.pred 	%p7, %p5, %p6;
	@%p7 bra 	$L__BB0_33;
	mul.lo.s64 	%rd28, %rd43, %rd2;
	mad.lo.s64 	%rd47, %rd42, %rd3, %rd28;
	add.s64 	%rd48, %rd47, %rd39;
	ld.b32 	%r57, [%rd48];
	add.s64 	%rd49, %rd48, %rd44;
	ld.b32 	%r56, [%rd49];
	setp.eq.b32 	%p8, %r57, -1;
	setp.eq.b32 	%p9, %r56, -1;
	or.pred 	%p10, %p8, %p9;
	mov.b64 	%rd281, 9223372036854775807;
	@%p10 bra 	$L__BB0_55;
	cvt.s64.s32 	%rd50, %r57;
	sub.s64 	%rd51, %rd2, %rd50;
	cvt.s64.s32 	%rd52, %r56;
	sub.s64 	%rd53, %rd3, %rd52;
	mul.lo.s64 	%rd54, %rd51, %rd51;
	mad.lo.s64 	%rd281, %rd53, %rd53, %rd54;
$L__BB0_55:
	cvt.u64.u32 	%rd29, %r17;
	cvt.s64.s32 	%rd30, %r18;
	sub.s64 	%rd55, %rd2, %rd29;
	setp.gt.s64 	%p11, %rd55, -1;
	setp.lt.s64 	%p12, %rd55, %rd30;
	and.pred 	%p3, %p11, %p12;
	mul.lo.s64 	%rd31, %rd55, %rd43;
	add.s64 	%rd32, %rd2, %rd29;
	mul.lo.s64 	%rd33, %rd32, %rd43;
	mov.b64 	%rd36, 0;
$L__BB0_56:
	mov.b64 	%rd282, -1;
	mov.pred 	%p114, 0;
	setp.eq.b64 	%p13, %rd36, 2;
	@%p13 bra 	$L__BB0_77;
	setp.eq.b64 	%p14, %rd36, 1;
	@%p14 bra 	$L__BB0_76;
$L__BB0_58:
	add.s64 	%rd36, %rd36, 1;
	mad.lo.s64 	%rd37, %rd282, %rd29, %rd3;
	mul.lo.s64 	%rd38, %rd37, %rd42;
	@%p114 bra 	$L__BB0_59;
	bra.uni 	$L__BB0_65;
$L__BB0_59:
	setp.lt.s64 	%p36, %rd37, %rd30;
	setp.gt.s64 	%p37, %rd37, -1;
	and.pred 	%p38, %p3, %p37;
	and.pred 	%p39, %p38, %p36;
	@%p39 bra 	$L__BB0_60;
	bra.uni 	$L__BB0_62;
$L__BB0_60:
	add.s64 	%rd85, %rd31, %rd38;
	add.s64 	%rd86, %rd85, %rd39;
	ld.b32 	%r11, [%rd86];
	add.s64 	%rd87, %rd86, %rd44;
	ld.b32 	%r26, [%rd87];
	setp.eq.b32 	%p40, %r11, -1;
	setp.eq.b32 	%p41, %r26, -1;
	or.pred 	%p42, %p40, %p41;
	@%p42 bra 	$L__BB0_62;
	cvt.s64.s32 	%rd88, %r11;
	cvt.s64.s32 	%rd89, %r26;
	sub.s64 	%rd90, %rd2, %rd88;
	sub.s64 	%rd91, %rd3, %rd89;
	mul.lo.s64 	%rd92, %rd90, %rd90;
	mad.lo.s64 	%rd93, %rd91, %rd91, %rd92;
	setp.lt.s64 	%p43, %rd93, %rd281;
	min.s64 	%rd281, %rd93, %rd281;
	selp.b32 	%r56, %r26, %r56, %p43;
	selp.b32 	%r57, %r11, %r57, %p43;
$L__BB0_62:
	setp.lt.s64 	%p44, %rd37, 0;
	max.s64 	%rd94, %rd32, %rd37;
	setp.ge.s64 	%p45, %rd94, %rd30;
	or.pred 	%p46, %p45, %p44;
	@%p46 bra 	$L__BB0_74;
	add.s64 	%rd95, %rd33, %rd38;
	add.s64 	%rd96, %rd95, %rd39;
	ld.b32 	%r12, [%rd96];
	add.s64 	%rd97, %rd96, %rd44;
	ld.b32 	%r27, [%rd97];
	setp.eq.b32 	%p47, %r12, -1;
	setp.eq.b32 	%p48, %r27, -1;
	or.pred 	%p49, %p47, %p48;
	@%p49 bra 	$L__BB0_74;
	cvt.s64.s32 	%rd98, %r12;
	cvt.s64.s32 	%rd99, %r27;
	sub.s64 	%rd100, %rd2, %rd98;
	sub.s64 	%rd101, %rd3, %rd99;
	mul.lo.s64 	%rd102, %rd100, %rd100;
	mad.lo.s64 	%rd103, %rd101, %rd101, %rd102;
	setp.lt.s64 	%p50, %rd103, %rd281;
	min.s64 	%rd281, %rd103, %rd281;
	selp.b32 	%r56, %r27, %r56, %p50;
	selp.b32 	%r57, %r12, %r57, %p50;
	bra.uni 	$L__BB0_74;
$L__BB0_65:
	setp.ge.s64 	%p15, %rd37, %rd30;
	setp.lt.s64 	%p16, %rd37, 0;
	not.pred 	%p17, %p3;
	or.pred 	%p18, %p17, %p16;
	or.pred 	%p19, %p18, %p15;
	@%p19 bra 	$L__BB0_68;
	add.s64 	%rd56, %rd31, %rd38;
	add.s64 	%rd57, %rd56, %rd39;
	ld.b32 	%r14, [%rd57];
	add.s64 	%rd58, %rd57, %rd44;
	ld.b32 	%r23, [%rd58];
	setp.eq.b32 	%p20, %r14, -1;
	setp.eq.b32 	%p21, %r23, -1;
	or.pred 	%p22, %p20, %p21;
	@%p22 bra 	$L__BB0_68;
	cvt.s64.s32 	%rd59, %r14;
	cvt.s64.s32 	%rd60, %r23;
	sub.s64 	%rd61, %rd2, %rd59;
	sub.s64 	%rd62, %rd3, %rd60;
	mul.lo.s64 	%rd63, %rd61, %rd61;
	mad.lo.s64 	%rd64, %rd62, %rd62, %rd63;
	setp.lt.s64 	%p23, %rd64, %rd281;
	min.s64 	%rd281, %rd64, %rd281;
	selp.b32 	%r56, %r23, %r56, %p23;
	selp.b32 	%r57, %r14, %r57, %p23;
$L__BB0_68:
	max.s64 	%rd65, %rd2, %rd37;
	setp.ge.s64 	%p24, %rd65, %rd30;
	or.pred 	%p25, %p24, %p16;
	@%p25 bra 	$L__BB0_71;
	add.s64 	%rd66, %rd28, %rd38;
	add.s64 	%rd67, %rd66, %rd39;
	ld.b32 	%r15, [%rd67];
	add.s64 	%rd68, %rd67, %rd44;
	ld.b32 	%r24, [%rd68];
	setp.eq.b32 	%p26, %r15, -1;
	setp.eq.b32 	%p27, %r24, -1;
	or.pred 	%p28, %p26, %p27;
	@%p28 bra 	$L__BB0_71;
	cvt.s64.s32 	%rd69, %r15;
	cvt.s64.s32 	%rd70, %r24;
	sub.s64 	%rd71, %rd2, %rd69;
	sub.s64 	%rd72, %rd3, %rd70;
	mul.lo.s64 	%rd73, %rd71, %rd71;
	mad.lo.s64 	%rd74, %rd72, %rd72, %rd73;
	setp.lt.s64 	%p29, %rd74, %rd281;
	min.s64 	%rd281, %rd74, %rd281;
	selp.b32 	%r56, %r24, %r56, %p29;
	selp.b32 	%r57, %r15, %r57, %p29;
$L__BB0_71:
	max.s64 	%rd75, %rd32, %rd37;
	setp.ge.s64 	%p30, %rd75, %rd30;
	or.pred 	%p31, %p30, %p16;
	@%p31 bra 	$L__BB0_74;
	add.s64 	%rd76, %rd33, %rd38;
	add.s64 	%rd77, %rd76, %rd39;
	ld.b32 	%r16, [%rd77];
	add.s64 	%rd78, %rd77, %rd44;
	ld.b32 	%r25, [%rd78];
	setp.eq.b32 	%p32, %r16, -1;
	setp.eq.b32 	%p33, %r25, -1;
	or.pred 	%p34, %p32, %p33;
	@%p34 bra 	$L__BB0_74;
	cvt.s64.s32 	%rd79, %r16;
	cvt.s64.s32 	%rd80, %r25;
	sub.s64 	%rd81, %rd2, %rd79;
	sub.s64 	%rd82, %rd3, %rd80;
	mul.lo.s64 	%rd83, %rd81, %rd81;
	mad.lo.s64 	%rd84, %rd82, %rd82, %rd83;
	setp.lt.s64 	%p35, %rd84, %rd281;
	min.s64 	%rd281, %rd84, %rd281;
	selp.b32 	%r56, %r25, %r56, %p35;
	selp.b32 	%r57, %r16, %r57, %p35;
$L__BB0_74:
	setp.eq.b64 	%p51, %rd36, 3;
	@%p51 bra 	$L__BB0_75;
	bra.uni 	$L__BB0_56;
$L__BB0_75:
	ld.param.b64 	%rd273, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_21];
	ld.param.b64 	%rd272, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_19];
	ld.param.b64 	%rd271, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v79B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_15];
	mul.lo.s64 	%rd267, %rd272, %rd3;
	mad.lo.s64 	%rd268, %rd45, %rd2, %rd267;
	add.s64 	%rd269, %rd268, %rd271;
	st.b32 	[%rd269], %r57;
	add.s64 	%rd270, %rd269, %rd273;
	st.b32 	[%rd270], %r56;
	bra.uni 	$L__BB0_33;
$L__BB0_76:
	mov.b64 	%rd282, 0;
	mov.pred 	%p114, -1;
	bra.uni 	$L__BB0_58;
$L__BB0_77:
	mov.b64 	%rd282, 1;
	bra.uni 	$L__BB0_58;

}