//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;

.visible .entry _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 .ptr .align 1 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 .ptr .align 1 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 .ptr .align 1 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 .ptr .align 1 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 .ptr .align 1 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 .ptr .align 1 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<35>;
	.reg .b32 	%r<109>;
	.reg .b64 	%rd<49>;

	ld.param.b64 	%rd8, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.b64 	%rd9, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.b64 	%rd10, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.b64 	%rd11, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.b64 	%rd12, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	mov.u32 	%r4, %tid.x;
	cvt.u64.u32 	%rd13, %r4;
	mov.u32 	%r5, %ntid.x;
	mov.u32 	%r6, %ctaid.x;
	mul.wide.u32 	%rd14, %r5, %r6;
	add.s64 	%rd1, %rd14, %rd13;
	mov.u32 	%r7, %tid.y;
	mov.u32 	%r8, %ntid.y;
	mov.u32 	%r9, %ctaid.y;
	mad.lo.s32 	%r10, %r8, %r9, %r7;
	cvt.u64.u32 	%rd2, %r10;
	cvt.rn.f32.u64 	%r11, %rd1;
	cvt.rn.f32.u64 	%r12, %rd11;
	div.rn.f32 	%r1, %r11, %r12;
	cvt.rn.f32.u32 	%r13, %r10;
	cvt.rn.f32.s64 	%r14, %rd12;
	div.rn.f32 	%r2, %r13, %r14;
	mad.lo.s32 	%r3, %r7, %r5, %r4;
	add.s64 	%rd15, %rd9, 15;
	shr.u64 	%rd16, %rd15, 4;
	setp.gt.s64 	%p1, %rd9, 0;
	selp.b64 	%rd17, %rd16, 0, %p1;
	setp.eq.b64 	%p2, %rd17, 0;
	setp.ne.b64 	%p3, %rd17, 0;
	selp.b64 	%rd18, -1, 0, %p3;
	add.s64 	%rd5, %rd17, %rd18;
	mov.b32 	%r107, 0;
	@%p2 bra 	$L__BB0_8;
	and.b32 	%r15, %r3, 1;
	setp.ne.b32 	%p4, %r15, 0;
	selp.b64 	%rd19, %rd10, 0, %p4;
	add.s64 	%rd3, %rd19, %rd8;
	shr.u32 	%r16, %r3, 1;
	and.b32 	%r17, %r16, 15;
	cvt.u64.u32 	%rd4, %r17;
	mov.b32 	%r105, 0f7F800000;
	mov.b64 	%rd44, 16;
	mov.b64 	%rd45, 0;
	mov.b64 	%rd46, %rd45;
	bra.uni 	$L__BB0_3;
$L__BB0_2:
	setp.lt.s64 	%p30, %rd5, 1;
	setp.gt.s64 	%p31, %rd5, 0;
	add.s64 	%rd44, %rd6, 16;
	selp.b64 	%rd37, -1, 0, %p31;
	add.s64 	%rd5, %rd5, %rd37;
	mov.b64 	%rd46, %rd6;
	@%p30 bra 	$L__BB0_7;
$L__BB0_3:
	mov.b64 	%rd6, %rd44;
	add.s64 	%rd7, %rd46, %rd4;
	setp.ge.s64 	%p5, %rd7, %rd9;
	mov.b32 	%r108, 2139095040;
	@%p5 bra 	$L__BB0_5;
	ld.param.b64 	%rd40, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	shr.s64 	%rd20, %rd7, 63;
	and.b64 	%rd21, %rd20, %rd9;
	add.s64 	%rd22, %rd21, %rd7;
	mad.lo.s64 	%rd23, %rd22, %rd40, %rd3;
	ld.b32 	%r108, [%rd23];
$L__BB0_5:
	mov.b64 	%rd48, 0;
	mov.b64 	%rd47, 15;
	mov.b32 	%r106, 3;
$L__BB0_6:
	add.s32 	%r18, %r106, -3;
	shfl.sync.idx.b32 	%r19|%p6, %r108, %r18, 31, -1;
	add.s32 	%r20, %r106, -2;
	shfl.sync.idx.b32 	%r21|%p7, %r108, %r20, 31, -1;
	sub.f32 	%r22, %r1, %r19;
	sub.f32 	%r23, %r2, %r21;
	abs.f32 	%r24, %r22;
	abs.f32 	%r25, %r23;
	min.s32 	%r26, %r25, %r24;
	max.s32 	%r27, %r24, %r25;
	and.b32 	%r28, %r27, -33554432;
	xor.b32 	%r29, %r28, 2122317824;
	mul.f32 	%r30, %r26, %r29;
	mul.f32 	%r31, %r27, %r29;
	mul.f32 	%r32, %r30, %r30;
	fma.rn.f32 	%r33, %r31, %r31, %r32;
	sqrt.rn.f32 	%r34, %r33;
	or.b32 	%r35, %r28, 8388608;
	mul.f32 	%r36, %r34, %r35;
	setp.eq.f32 	%p8, %r26, 0f00000000;
	selp.f32 	%r37, %r27, %r36, %p8;
	setp.eq.f32 	%p9, %r26, 0f7F800000;
	selp.f32 	%r38, 0f7F800000, %r37, %p9;
	setp.lt.f32 	%p10, %r38, %r105;
	selp.b64 	%rd24, %rd46, %rd45, %p10;
	selp.f32 	%r39, %r38, %r105, %p10;
	setp.ne.b64 	%p11, %rd47, 0;
	selp.b64 	%rd25, -1, 0, %p11;
	add.s64 	%rd26, %rd47, %rd25;
	cvt.u32.u64 	%r40, %rd48;
	add.s32 	%r41, %r40, 2;
	shfl.sync.idx.b32 	%r42|%p12, %r108, %r41, 31, -1;
	add.s32 	%r43, %r106, 4;
	shfl.sync.idx.b32 	%r44|%p13, %r108, %r106, 31, -1;
	sub.f32 	%r45, %r1, %r42;
	sub.f32 	%r46, %r2, %r44;
	abs.f32 	%r47, %r45;
	abs.f32 	%r48, %r46;
	min.s32 	%r49, %r48, %r47;
	max.s32 	%r50, %r47, %r48;
	and.b32 	%r51, %r50, -33554432;
	xor.b32 	%r52, %r51, 2122317824;
	mul.f32 	%r53, %r49, %r52;
	mul.f32 	%r54, %r50, %r52;
	mul.f32 	%r55, %r53, %r53;
	fma.rn.f32 	%r56, %r54, %r54, %r55;
	sqrt.rn.f32 	%r57, %r56;
	or.b32 	%r58, %r51, 8388608;
	mul.f32 	%r59, %r57, %r58;
	setp.eq.f32 	%p14, %r49, 0f00000000;
	selp.f32 	%r60, %r50, %r59, %p14;
	setp.eq.f32 	%p15, %r49, 0f7F800000;
	selp.f32 	%r61, 0f7F800000, %r60, %p15;
	setp.lt.f32 	%p16, %r61, %r39;
	add.s64 	%rd27, %rd46, 1;
	selp.b64 	%rd28, %rd27, %rd24, %p16;
	selp.f32 	%r62, %r61, %r39, %p16;
	setp.ne.b64 	%p17, %rd26, 0;
	selp.b64 	%rd29, -1, 0, %p17;
	add.s64 	%rd30, %rd26, %rd29;
	add.s32 	%r63, %r40, 4;
	shfl.sync.idx.b32 	%r64|%p18, %r108, %r63, 31, -1;
	add.s32 	%r65, %r106, 2;
	shfl.sync.idx.b32 	%r66|%p19, %r108, %r65, 31, -1;
	sub.f32 	%r67, %r1, %r64;
	sub.f32 	%r68, %r2, %r66;
	abs.f32 	%r69, %r67;
	abs.f32 	%r70, %r68;
	min.s32 	%r71, %r70, %r69;
	max.s32 	%r72, %r69, %r70;
	and.b32 	%r73, %r72, -33554432;
	xor.b32 	%r74, %r73, 2122317824;
	mul.f32 	%r75, %r71, %r74;
	mul.f32 	%r76, %r72, %r74;
	mul.f32 	%r77, %r75, %r75;
	fma.rn.f32 	%r78, %r76, %r76, %r77;
	sqrt.rn.f32 	%r79, %r78;
	or.b32 	%r80, %r73, 8388608;
	mul.f32 	%r81, %r79, %r80;
	setp.eq.f32 	%p20, %r71, 0f00000000;
	selp.f32 	%r82, %r72, %r81, %p20;
	setp.eq.f32 	%p21, %r71, 0f7F800000;
	selp.f32 	%r83, 0f7F800000, %r82, %p21;
	setp.lt.f32 	%p22, %r83, %r62;
	add.s64 	%rd31, %rd46, 2;
	selp.b64 	%rd32, %rd31, %rd28, %p22;
	selp.f32 	%r84, %r83, %r62, %p22;
	setp.ne.b64 	%p23, %rd30, 0;
	selp.b64 	%rd33, -1, 0, %p23;
	add.s64 	%rd34, %rd30, %rd33;
	add.s64 	%rd48, %rd48, 8;
	add.s32 	%r85, %r40, 6;
	shfl.sync.idx.b32 	%r86|%p24, %r108, %r85, 31, -1;
	shfl.sync.idx.b32 	%r87|%p25, %r108, %r43, 31, -1;
	sub.f32 	%r88, %r1, %r86;
	sub.f32 	%r89, %r2, %r87;
	abs.f32 	%r90, %r88;
	abs.f32 	%r91, %r89;
	min.s32 	%r92, %r91, %r90;
	max.s32 	%r93, %r90, %r91;
	and.b32 	%r94, %r93, -33554432;
	xor.b32 	%r95, %r94, 2122317824;
	mul.f32 	%r96, %r92, %r95;
	mul.f32 	%r97, %r93, %r95;
	mul.f32 	%r98, %r96, %r96;
	fma.rn.f32 	%r99, %r97, %r97, %r98;
	sqrt.rn.f32 	%r100, %r99;
	or.b32 	%r101, %r94, 8388608;
	mul.f32 	%r102, %r100, %r101;
	setp.eq.f32 	%p26, %r92, 0f00000000;
	selp.f32 	%r103, %r93, %r102, %p26;
	setp.eq.f32 	%p27, %r92, 0f7F800000;
	selp.f32 	%r104, 0f7F800000, %r103, %p27;
	setp.lt.f32 	%p28, %r104, %r84;
	add.s64 	%rd35, %rd46, 3;
	selp.b64 	%rd45, %rd35, %rd32, %p28;
	selp.f32 	%r105, %r104, %r84, %p28;
	setp.ne.b64 	%p29, %rd34, 0;
	selp.b64 	%rd36, -1, 0, %p29;
	add.s64 	%rd47, %rd34, %rd36;
	add.s64 	%rd46, %rd46, 4;
	add.s32 	%r106, %r106, 8;
	@%p29 bra 	$L__BB0_6;
	bra.uni 	$L__BB0_2;
$L__BB0_7:
	cvt.u32.u64 	%r107, %rd45;
$L__BB0_8:
	setp.lt.u64 	%p32, %rd1, %rd11;
	setp.gt.s64 	%p33, %rd12, %rd2;
	and.pred 	%p34, %p32, %p33;
	@%p34 bra 	$L__BB0_10;
$L__BB0_9:
	ret;
$L__BB0_10:
	ld.param.b64 	%rd43, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	ld.param.b64 	%rd42, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.b64 	%rd41, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v57B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	mad.lo.s64 	%rd38, %rd42, %rd1, %rd41;
	mad.lo.s64 	%rd39, %rd43, %rd2, %rd38;
	st.b32 	[%rd39], %r107;
	bra.uni 	$L__BB0_9;

}