//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-36037853
// Cuda compilation tools, release 12.9, V12.9.86
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_75
.address_size 64

	// .globl	_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;
.visible .shared .align 4 .b8 _cudapy_smem_2[64];

.visible .entry _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<20>;
	.reg .f32 	%f<67>;
	.reg .b32 	%r<12>;
	.reg .b64 	%rd<102>;


	ld.param.u64 	%rd16, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.u64 	%rd17, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.u64 	%rd18, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6];
	ld.param.u64 	%rd19, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.u64 	%rd20, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.u64 	%rd22, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd23, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	mov.u32 	%r4, %tid.x;
	cvt.s64.s32 	%rd26, %r4;
	mov.u32 	%r5, %ntid.x;
	mov.u32 	%r6, %ctaid.x;
	mul.wide.s32 	%rd27, %r5, %r6;
	add.s64 	%rd1, %rd27, %rd26;
	mov.u32 	%r7, %tid.y;
	cvt.s64.s32 	%rd28, %r7;
	mov.u32 	%r8, %ntid.y;
	mov.u32 	%r9, %ctaid.y;
	mul.wide.s32 	%rd29, %r8, %r9;
	add.s64 	%rd2, %rd29, %rd28;
	mul.wide.s32 	%rd30, %r7, %r5;
	add.s64 	%rd31, %rd30, %rd26;
	shr.u64 	%rd32, %rd31, 63;
	add.s64 	%rd33, %rd31, %rd32;
	shr.s64 	%rd34, %rd33, 1;
	and.b64  	%rd35, %rd33, -2;
	sub.s64 	%rd3, %rd31, %rd35;
	shr.s64 	%rd36, %rd3, 63;
	add.s64 	%rd4, %rd36, %rd34;
	and.b64  	%rd37, %rd17, 7;
	setp.ne.s64 	%p2, %rd37, 0;
	selp.u64 	%rd38, 1, 0, %p2;
	shr.u64 	%rd39, %rd17, 3;
	add.s64 	%rd40, %rd39, %rd38;
	setp.gt.s64 	%p3, %rd17, 0;
	selp.b64 	%rd5, %rd40, 0, %p3;
	setp.ne.s64 	%p1, %rd5, 0;
	setp.eq.s64 	%p4, %rd5, 0;
	mov.u32 	%r11, 0;
	@%p4 bra 	$L__BB0_8;

	cvt.rn.f32.s64 	%f6, %rd22;
	cvt.rn.f32.s64 	%f7, %rd1;
	div.approx.ftz.f32 	%f1, %f7, %f6;
	cvt.rn.f32.s64 	%f8, %rd23;
	cvt.rn.f32.s64 	%f9, %rd2;
	div.approx.ftz.f32 	%f2, %f9, %f8;
	add.s64 	%rd43, %rd3, 2;
	setp.lt.s64 	%p5, %rd3, 0;
	mov.u64 	%rd100, 0;
	selp.b64 	%rd44, %rd43, %rd3, %p5;
	shr.s64 	%rd45, %rd44, 63;
	and.b64  	%rd46, %rd45, %rd18;
	add.s64 	%rd47, %rd46, %rd44;
	mul.lo.s64 	%rd48, %rd47, %rd20;
	add.s64 	%rd6, %rd48, %rd16;
	and.b64  	%rd49, %rd4, -9223372036854775808;
	shr.u64 	%rd50, %rd49, 60;
	add.s64 	%rd51, %rd50, %rd4;
	and.b64  	%rd52, %rd44, -9223372036854775808;
	shr.u64 	%rd53, %rd52, 62;
	add.s64 	%rd54, %rd53, %rd44;
	shl.b64 	%rd55, %rd51, 1;
	add.s64 	%rd56, %rd54, %rd55;
	shl.b64 	%rd57, %rd56, 2;
	mov.u64 	%rd58, _cudapy_smem_2;
	add.s64 	%rd7, %rd58, %rd57;
	selp.s64 	%rd59, -1, 0, %p1;
	add.s64 	%rd99, %rd5, %rd59;
	mov.f32 	%f66, 0f7F800000;
	mov.u64 	%rd101, %rd100;

$L__BB0_2:
	mov.u64 	%rd9, %rd99;
	setp.gt.s64 	%p6, %rd4, 7;
	@%p6 bra 	$L__BB0_6;

	add.s64 	%rd12, %rd4, %rd100;
	setp.lt.s64 	%p7, %rd12, %rd17;
	@%p7 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_4;

$L__BB0_5:
	shr.s64 	%rd60, %rd12, 63;
	and.b64  	%rd61, %rd60, %rd17;
	add.s64 	%rd62, %rd4, %rd61;
	add.s64 	%rd63, %rd62, %rd100;
	mul.lo.s64 	%rd64, %rd63, %rd19;
	add.s64 	%rd65, %rd6, %rd64;
	ld.f32 	%f10, [%rd65];
	st.shared.f32 	[%rd7], %f10;
	bra.uni 	$L__BB0_6;

$L__BB0_4:
	mov.u32 	%r10, 2139095040;
	st.shared.u32 	[%rd7], %r10;

$L__BB0_6:
	bar.sync 	0;
	ld.shared.f32 	%f11, [_cudapy_smem_2];
	sub.ftz.f32 	%f12, %f1, %f11;
	cvta.shared.u64 	%rd67, %rd58;
	ld.f32 	%f13, [%rd67+4];
	sub.ftz.f32 	%f14, %f2, %f13;
	mul.ftz.f32 	%f15, %f14, %f14;
	fma.rn.ftz.f32 	%f16, %f12, %f12, %f15;
	setp.lt.ftz.f32 	%p8, %f16, %f66;
	selp.b64 	%rd68, %rd100, %rd101, %p8;
	selp.f32 	%f17, %f16, %f66, %p8;
	ld.shared.f32 	%f18, [_cudapy_smem_2+8];
	sub.ftz.f32 	%f19, %f1, %f18;
	ld.f32 	%f20, [%rd67+12];
	sub.ftz.f32 	%f21, %f2, %f20;
	mul.ftz.f32 	%f22, %f21, %f21;
	fma.rn.ftz.f32 	%f23, %f19, %f19, %f22;
	setp.lt.ftz.f32 	%p9, %f23, %f17;
	add.s64 	%rd69, %rd100, 1;
	selp.b64 	%rd70, %rd69, %rd68, %p9;
	selp.f32 	%f24, %f23, %f17, %p9;
	ld.shared.f32 	%f25, [_cudapy_smem_2+16];
	sub.ftz.f32 	%f26, %f1, %f25;
	ld.f32 	%f27, [%rd67+20];
	sub.ftz.f32 	%f28, %f2, %f27;
	mul.ftz.f32 	%f29, %f28, %f28;
	fma.rn.ftz.f32 	%f30, %f26, %f26, %f29;
	setp.lt.ftz.f32 	%p10, %f30, %f24;
	add.s64 	%rd71, %rd100, 2;
	selp.b64 	%rd72, %rd71, %rd70, %p10;
	selp.f32 	%f31, %f30, %f24, %p10;
	ld.shared.f32 	%f32, [_cudapy_smem_2+24];
	sub.ftz.f32 	%f33, %f1, %f32;
	ld.f32 	%f34, [%rd67+28];
	sub.ftz.f32 	%f35, %f2, %f34;
	mul.ftz.f32 	%f36, %f35, %f35;
	fma.rn.ftz.f32 	%f37, %f33, %f33, %f36;
	setp.lt.ftz.f32 	%p11, %f37, %f31;
	add.s64 	%rd73, %rd100, 3;
	selp.b64 	%rd74, %rd73, %rd72, %p11;
	selp.f32 	%f38, %f37, %f31, %p11;
	ld.shared.f32 	%f39, [_cudapy_smem_2+32];
	sub.ftz.f32 	%f40, %f1, %f39;
	ld.f32 	%f41, [%rd67+36];
	sub.ftz.f32 	%f42, %f2, %f41;
	mul.ftz.f32 	%f43, %f42, %f42;
	fma.rn.ftz.f32 	%f44, %f40, %f40, %f43;
	setp.lt.ftz.f32 	%p12, %f44, %f38;
	add.s64 	%rd75, %rd100, 4;
	selp.b64 	%rd76, %rd75, %rd74, %p12;
	selp.f32 	%f45, %f44, %f38, %p12;
	ld.shared.f32 	%f46, [_cudapy_smem_2+40];
	sub.ftz.f32 	%f47, %f1, %f46;
	ld.f32 	%f48, [%rd67+44];
	sub.ftz.f32 	%f49, %f2, %f48;
	mul.ftz.f32 	%f50, %f49, %f49;
	fma.rn.ftz.f32 	%f51, %f47, %f47, %f50;
	setp.lt.ftz.f32 	%p13, %f51, %f45;
	add.s64 	%rd77, %rd100, 5;
	selp.b64 	%rd78, %rd77, %rd76, %p13;
	selp.f32 	%f52, %f51, %f45, %p13;
	ld.shared.f32 	%f53, [_cudapy_smem_2+48];
	sub.ftz.f32 	%f54, %f1, %f53;
	ld.f32 	%f55, [%rd67+52];
	sub.ftz.f32 	%f56, %f2, %f55;
	mul.ftz.f32 	%f57, %f56, %f56;
	fma.rn.ftz.f32 	%f58, %f54, %f54, %f57;
	setp.lt.ftz.f32 	%p14, %f58, %f52;
	add.s64 	%rd79, %rd100, 6;
	selp.b64 	%rd80, %rd79, %rd78, %p14;
	selp.f32 	%f59, %f58, %f52, %p14;
	ld.shared.f32 	%f60, [_cudapy_smem_2+56];
	sub.ftz.f32 	%f61, %f1, %f60;
	ld.f32 	%f62, [%rd67+60];
	sub.ftz.f32 	%f63, %f2, %f62;
	mul.ftz.f32 	%f64, %f63, %f63;
	fma.rn.ftz.f32 	%f65, %f61, %f61, %f64;
	setp.lt.ftz.f32 	%p15, %f65, %f59;
	add.s64 	%rd81, %rd100, 7;
	selp.b64 	%rd101, %rd81, %rd80, %p15;
	selp.f32 	%f66, %f65, %f59, %p15;
	bar.sync 	0;
	add.s64 	%rd99, %rd9, -1;
	add.s64 	%rd100, %rd100, 8;
	setp.gt.s64 	%p16, %rd9, 0;
	@%p16 bra 	$L__BB0_2;

	cvt.u32.u64 	%r11, %rd101;

$L__BB0_8:
	ld.param.u64 	%rd97, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd92, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	setp.ge.s64 	%p17, %rd2, %rd92;
	setp.ge.s64 	%p18, %rd1, %rd97;
	or.pred  	%p19, %p18, %p17;
	@%p19 bra 	$L__BB0_10;

	ld.param.u64 	%rd98, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd96, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.u64 	%rd95, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	ld.param.u64 	%rd94, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.u64 	%rd93, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v63B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	shr.s64 	%rd82, %rd1, 63;
	and.b64  	%rd83, %rd82, %rd98;
	add.s64 	%rd84, %rd83, %rd1;
	shr.s64 	%rd85, %rd2, 63;
	and.b64  	%rd86, %rd85, %rd93;
	add.s64 	%rd87, %rd86, %rd2;
	mul.lo.s64 	%rd88, %rd84, %rd94;
	mul.lo.s64 	%rd89, %rd87, %rd95;
	add.s64 	%rd90, %rd88, %rd96;
	add.s64 	%rd91, %rd90, %rd89;
	st.u32 	[%rd91], %r11;

$L__BB0_10:
	ret;

}