//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-36037853
// Cuda compilation tools, release 12.9, V12.9.86
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_75
.address_size 64

	// .globl	_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;

.visible .entry _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<12>;
	.reg .f32 	%f<29>;
	.reg .b32 	%r<19>;
	.reg .b64 	%rd<52>;


	ld.param.u64 	%rd11, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.u64 	%rd12, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.u64 	%rd13, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6];
	ld.param.u64 	%rd14, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.u64 	%rd15, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.u64 	%rd16, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.u64 	%rd17, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd18, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	ld.param.u64 	%rd19, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.u64 	%rd20, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v45B126cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEADwxQaHrboAVKtDpJSrwUaBLTVFpQ6gbGDllCQhCFpEkkANZ3BJJD8bQuxAmS7upUCRF4dKAfkGNdqAgA_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	mov.u32 	%r3, %tid.x;
	cvt.s64.s32 	%rd21, %r3;
	mov.u32 	%r4, %ntid.x;
	mov.u32 	%r5, %ctaid.x;
	mul.wide.s32 	%rd22, %r4, %r5;
	add.s64 	%rd1, %rd22, %rd21;
	mov.u32 	%r6, %tid.y;
	cvt.s64.s32 	%rd23, %r6;
	mov.u32 	%r7, %ntid.y;
	mov.u32 	%r8, %ctaid.y;
	mul.wide.s32 	%rd24, %r7, %r8;
	add.s64 	%rd2, %rd24, %rd23;
	setp.ge.s64 	%p2, %rd1, %rd17;
	setp.ge.s64 	%p3, %rd2, %rd18;
	or.pred  	%p4, %p2, %p3;
	@%p4 bra 	$L__BB0_8;

	setp.gt.s64 	%p1, %rd12, 0;
	setp.lt.s64 	%p5, %rd12, 1;
	mov.u32 	%r18, 0;
	@%p5 bra 	$L__BB0_7;

	setp.lt.s64 	%p6, %rd13, 2;
	@%p6 bra 	$L__BB0_8;

	selp.b64 	%rd28, %rd12, 0, %p1;
	mov.u64 	%rd50, 0;
	selp.s64 	%rd29, -1, 0, %p1;
	add.s64 	%rd48, %rd28, %rd29;
	cvt.rn.f32.s64 	%f6, %rd18;
	cvt.rn.f32.s64 	%f7, %rd2;
	div.approx.ftz.f32 	%f1, %f7, %f6;
	cvt.rn.f32.s64 	%f8, %rd17;
	cvt.rn.f32.s64 	%f9, %rd1;
	div.approx.ftz.f32 	%f2, %f9, %f8;
	mov.f32 	%f28, 0f7F800000;
	mov.u64 	%rd49, 1;
	mov.u64 	%rd51, %rd50;

$L__BB0_4:
	mov.u64 	%rd6, %rd49;
	setp.ne.s64 	%p7, %rd13, 2;
	@%p7 bra 	$L__BB0_8;

	shr.s64 	%rd30, %rd51, 63;
	and.b64  	%rd31, %rd30, %rd12;
	add.s64 	%rd32, %rd31, %rd51;
	mul.lo.s64 	%rd33, %rd32, %rd14;
	add.s64 	%rd34, %rd33, %rd11;
	add.s64 	%rd35, %rd34, %rd15;
	ld.f32 	%f10, [%rd34];
	sub.ftz.f32 	%f11, %f2, %f10;
	ld.f32 	%f12, [%rd35];
	sub.ftz.f32 	%f13, %f1, %f12;
	abs.ftz.f32 	%f14, %f11;
	abs.ftz.f32 	%f15, %f13;
	mov.b32 	%r10, %f15;
	mov.b32 	%r11, %f14;
	min.s32 	%r12, %r10, %r11;
	mov.b32 	%f16, %r12;
	max.s32 	%r13, %r10, %r11;
	mov.b32 	%f17, %r13;
	and.b32  	%r14, %r13, -33554432;
	mov.u32 	%r15, 2122317824;
	sub.s32 	%r16, %r15, %r14;
	mov.b32 	%f18, %r16;
	mul.ftz.f32 	%f19, %f16, %f18;
	mul.ftz.f32 	%f20, %f17, %f18;
	mul.ftz.f32 	%f21, %f19, %f19;
	fma.rn.ftz.f32 	%f22, %f20, %f20, %f21;
	sqrt.approx.ftz.f32 	%f23, %f22;
	or.b32  	%r17, %r14, 8388608;
	mov.b32 	%f24, %r17;
	mul.ftz.f32 	%f25, %f23, %f24;
	setp.eq.ftz.f32 	%p8, %f16, 0f00000000;
	selp.f32 	%f26, %f17, %f25, %p8;
	setp.eq.ftz.f32 	%p9, %f16, 0f7F800000;
	selp.f32 	%f27, 0f7F800000, %f26, %p9;
	setp.lt.ftz.f32 	%p10, %f27, %f28;
	selp.b64 	%rd50, %rd51, %rd50, %p10;
	selp.f32 	%f28, %f27, %f28, %p10;
	setp.gt.s64 	%p11, %rd48, 0;
	selp.u64 	%rd36, 1, 0, %p11;
	add.s64 	%rd49, %rd6, %rd36;
	selp.b64 	%rd37, -1, 0, %p11;
	add.s64 	%rd48, %rd48, %rd37;
	mov.u64 	%rd51, %rd6;
	@%p11 bra 	$L__BB0_4;

	cvt.u32.u64 	%r18, %rd50;

$L__BB0_7:
	shr.s64 	%rd38, %rd1, 63;
	and.b64  	%rd39, %rd38, %rd17;
	add.s64 	%rd40, %rd39, %rd1;
	shr.s64 	%rd41, %rd2, 63;
	and.b64  	%rd42, %rd41, %rd18;
	add.s64 	%rd43, %rd42, %rd2;
	mul.lo.s64 	%rd44, %rd40, %rd19;
	mul.lo.s64 	%rd45, %rd43, %rd20;
	add.s64 	%rd46, %rd44, %rd16;
	add.s64 	%rd47, %rd46, %rd45;
	st.u32 	[%rd47], %r18;

$L__BB0_8:
	ret;

}