//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;
.visible .shared .align 4 .b8 _cudapy_smem_2[64];

.visible .entry _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 .ptr .align 1 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 .ptr .align 1 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 .ptr .align 1 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 .ptr .align 1 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 .ptr .align 1 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 .ptr .align 1 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<18>;
	.reg .b32 	%r<74>;
	.reg .b64 	%rd<54>;

	ld.param.b64 	%rd9, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.b64 	%rd10, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.b64 	%rd11, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.b64 	%rd12, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.b64 	%rd13, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.b64 	%rd14, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.b64 	%rd15, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	ld.param.b64 	%rd16, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.b64 	%rd17, [_ZN5task548_voroni_square_euclidean_fast_grid_stride_kernelB3v64B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	mov.u32 	%r5, %tid.x;
	cvt.u64.u32 	%rd18, %r5;
	mov.u32 	%r6, %ntid.x;
	mov.u32 	%r7, %ctaid.x;
	mul.wide.u32 	%rd19, %r6, %r7;
	add.s64 	%rd1, %rd19, %rd18;
	mov.u32 	%r8, %tid.y;
	mov.u32 	%r9, %ntid.y;
	mov.u32 	%r10, %ctaid.y;
	mad.lo.s32 	%r1, %r9, %r10, %r8;
	cvt.u64.u32 	%rd2, %r1;
	mad.lo.s32 	%r11, %r8, %r6, %r5;
	cvt.u64.u32 	%rd3, %r11;
	shr.u64 	%rd4, %rd3, 1;
	add.s64 	%rd20, %rd10, 7;
	shr.u64 	%rd21, %rd20, 3;
	setp.gt.s64 	%p1, %rd10, 0;
	selp.b64 	%rd22, %rd21, 0, %p1;
	setp.eq.b64 	%p2, %rd22, 0;
	setp.ne.b64 	%p3, %rd22, 0;
	selp.b64 	%rd23, -1, 0, %p3;
	add.s64 	%rd51, %rd22, %rd23;
	mov.b32 	%r73, 0;
	@%p2 bra 	$L__BB0_8;
	cvt.rn.f32.u64 	%r12, %rd14;
	cvt.rn.f32.u64 	%r13, %rd1;
	div.approx.ftz.f32 	%r2, %r13, %r12;
	cvt.rn.f32.s64 	%r14, %rd15;
	cvt.rn.f32.u32 	%r15, %r1;
	div.approx.ftz.f32 	%r3, %r15, %r14;
	cvt.u32.u64 	%r4, %rd3;
	and.b64 	%rd24, %rd3, 1;
	shl.b64 	%rd25, %rd3, 2;
	and.b64 	%rd26, %rd25, 60;
	mov.b64 	%rd27, _cudapy_smem_2;
	add.s64 	%rd5, %rd27, %rd26;
	mad.lo.s64 	%rd6, %rd12, %rd24, %rd9;
	mov.b32 	%r72, 0f7F800000;
	mov.b64 	%rd52, 0;
	mov.b64 	%rd53, %rd52;
$L__BB0_2:
	mov.b64 	%rd7, %rd51;
	setp.gt.u32 	%p4, %r4, 15;
	@%p4 bra 	$L__BB0_6;
	add.s64 	%rd8, %rd4, %rd52;
	setp.ge.s64 	%p5, %rd8, %rd10;
	@%p5 bra 	$L__BB0_5;
	shr.s64 	%rd28, %rd8, 63;
	and.b64 	%rd29, %rd28, %rd10;
	add.s64 	%rd30, %rd4, %rd29;
	add.s64 	%rd31, %rd30, %rd52;
	mad.lo.s64 	%rd32, %rd31, %rd11, %rd6;
	ld.b32 	%r16, [%rd32];
	st.shared.b32 	[%rd5], %r16;
	bra.uni 	$L__BB0_6;
$L__BB0_5:
	st.shared.b32 	[%rd5], 2139095040;
$L__BB0_6:
	bar.sync 	0;
	ld.shared.b32 	%r17, [_cudapy_smem_2];
	mov.b64 	%rd33, _cudapy_smem_2;
	cvta.shared.u64 	%rd34, %rd33;
	ld.b32 	%r18, [%rd34+4];
	sub.ftz.f32 	%r19, %r2, %r17;
	sub.ftz.f32 	%r20, %r3, %r18;
	mul.ftz.f32 	%r21, %r20, %r20;
	fma.rn.ftz.f32 	%r22, %r19, %r19, %r21;
	setp.lt.ftz.f32 	%p6, %r22, %r72;
	selp.b64 	%rd35, %rd52, %rd53, %p6;
	selp.f32 	%r23, %r22, %r72, %p6;
	ld.shared.b32 	%r24, [_cudapy_smem_2+8];
	ld.b32 	%r25, [%rd34+12];
	sub.ftz.f32 	%r26, %r2, %r24;
	sub.ftz.f32 	%r27, %r3, %r25;
	mul.ftz.f32 	%r28, %r27, %r27;
	fma.rn.ftz.f32 	%r29, %r26, %r26, %r28;
	setp.lt.ftz.f32 	%p7, %r29, %r23;
	add.s64 	%rd36, %rd52, 1;
	selp.b64 	%rd37, %rd36, %rd35, %p7;
	selp.f32 	%r30, %r29, %r23, %p7;
	ld.shared.b32 	%r31, [_cudapy_smem_2+16];
	ld.b32 	%r32, [%rd34+20];
	sub.ftz.f32 	%r33, %r2, %r31;
	sub.ftz.f32 	%r34, %r3, %r32;
	mul.ftz.f32 	%r35, %r34, %r34;
	fma.rn.ftz.f32 	%r36, %r33, %r33, %r35;
	setp.lt.ftz.f32 	%p8, %r36, %r30;
	add.s64 	%rd38, %rd52, 2;
	selp.b64 	%rd39, %rd38, %rd37, %p8;
	selp.f32 	%r37, %r36, %r30, %p8;
	ld.shared.b32 	%r38, [_cudapy_smem_2+24];
	ld.b32 	%r39, [%rd34+28];
	sub.ftz.f32 	%r40, %r2, %r38;
	sub.ftz.f32 	%r41, %r3, %r39;
	mul.ftz.f32 	%r42, %r41, %r41;
	fma.rn.ftz.f32 	%r43, %r40, %r40, %r42;
	setp.lt.ftz.f32 	%p9, %r43, %r37;
	add.s64 	%rd40, %rd52, 3;
	selp.b64 	%rd41, %rd40, %rd39, %p9;
	selp.f32 	%r44, %r43, %r37, %p9;
	ld.shared.b32 	%r45, [_cudapy_smem_2+32];
	ld.b32 	%r46, [%rd34+36];
	sub.ftz.f32 	%r47, %r2, %r45;
	sub.ftz.f32 	%r48, %r3, %r46;
	mul.ftz.f32 	%r49, %r48, %r48;
	fma.rn.ftz.f32 	%r50, %r47, %r47, %r49;
	setp.lt.ftz.f32 	%p10, %r50, %r44;
	add.s64 	%rd42, %rd52, 4;
	selp.b64 	%rd43, %rd42, %rd41, %p10;
	selp.f32 	%r51, %r50, %r44, %p10;
	ld.shared.b32 	%r52, [_cudapy_smem_2+40];
	ld.b32 	%r53, [%rd34+44];
	sub.ftz.f32 	%r54, %r2, %r52;
	sub.ftz.f32 	%r55, %r3, %r53;
	mul.ftz.f32 	%r56, %r55, %r55;
	fma.rn.ftz.f32 	%r57, %r54, %r54, %r56;
	setp.lt.ftz.f32 	%p11, %r57, %r51;
	add.s64 	%rd44, %rd52, 5;
	selp.b64 	%rd45, %rd44, %rd43, %p11;
	selp.f32 	%r58, %r57, %r51, %p11;
	ld.shared.b32 	%r59, [_cudapy_smem_2+48];
	ld.b32 	%r60, [%rd34+52];
	sub.ftz.f32 	%r61, %r2, %r59;
	sub.ftz.f32 	%r62, %r3, %r60;
	mul.ftz.f32 	%r63, %r62, %r62;
	fma.rn.ftz.f32 	%r64, %r61, %r61, %r63;
	setp.lt.ftz.f32 	%p12, %r64, %r58;
	add.s64 	%rd46, %rd52, 6;
	selp.b64 	%rd47, %rd46, %rd45, %p12;
	selp.f32 	%r65, %r64, %r58, %p12;
	ld.shared.b32 	%r66, [_cudapy_smem_2+56];
	ld.b32 	%r67, [%rd34+60];
	sub.ftz.f32 	%r68, %r2, %r66;
	sub.ftz.f32 	%r69, %r3, %r67;
	mul.ftz.f32 	%r70, %r69, %r69;
	fma.rn.ftz.f32 	%r71, %r68, %r68, %r70;
	setp.lt.ftz.f32 	%p13, %r71, %r65;
	add.s64 	%rd48, %rd52, 7;
	selp.b64 	%rd53, %rd48, %rd47, %p13;
	selp.f32 	%r72, %r71, %r65, %p13;
	bar.sync 	0;
	add.s64 	%rd51, %rd7, -1;
	setp.gt.s64 	%p14, %rd7, 0;
	add.s64 	%rd52, %rd52, 8;
	@%p14 bra 	$L__BB0_2;
	cvt.u32.u64 	%r73, %rd53;
$L__BB0_8:
	setp.lt.u64 	%p15, %rd1, %rd14;
	setp.gt.s64 	%p16, %rd15, %rd2;
	and.pred 	%p17, %p15, %p16;
	@%p17 bra 	$L__BB0_10;
$L__BB0_9:
	ret;
$L__BB0_10:
	mad.lo.s64 	%rd49, %rd16, %rd1, %rd13;
	mad.lo.s64 	%rd50, %rd17, %rd2, %rd49;
	st.b32 	[%rd50], %r73;
	bra.uni 	$L__BB0_9;

}