//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-36037853
// Cuda compilation tools, release 12.9, V12.9.86
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_75
.address_size 64

	// .globl	_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;

.visible .entry _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<36>;
	.reg .f32 	%f<89>;
	.reg .b32 	%r<68>;
	.reg .b64 	%rd<123>;


	ld.param.u64 	%rd25, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.u64 	%rd26, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.u64 	%rd27, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6];
	ld.param.u64 	%rd28, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.u64 	%rd29, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.u64 	%rd31, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd32, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	mov.u32 	%r8, %tid.x;
	cvt.s64.s32 	%rd35, %r8;
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mul.wide.s32 	%rd36, %r9, %r10;
	add.s64 	%rd1, %rd36, %rd35;
	mov.u32 	%r11, %tid.y;
	cvt.s64.s32 	%rd37, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mul.wide.s32 	%rd38, %r12, %r13;
	add.s64 	%rd2, %rd38, %rd37;
	cvt.rn.f32.s64 	%f8, %rd1;
	cvt.rn.f32.s64 	%f9, %rd31;
	div.rn.f32 	%f1, %f8, %f9;
	cvt.rn.f32.s64 	%f10, %rd2;
	cvt.rn.f32.s64 	%f11, %rd32;
	div.rn.f32 	%f2, %f10, %f11;
	mul.wide.s32 	%rd39, %r11, %r9;
	add.s64 	%rd3, %rd39, %rd35;
	and.b64  	%rd40, %rd26, 15;
	setp.ne.s64 	%p2, %rd40, 0;
	selp.u64 	%rd41, 1, 0, %p2;
	shr.u64 	%rd42, %rd26, 4;
	add.s64 	%rd43, %rd42, %rd41;
	setp.gt.s64 	%p3, %rd26, 0;
	selp.b64 	%rd4, %rd43, 0, %p3;
	setp.ne.s64 	%p1, %rd4, 0;
	setp.eq.s64 	%p4, %rd4, 0;
	mov.u32 	%r67, 0;
	@%p4 bra 	$L__BB0_10;

	shr.u64 	%rd47, %rd3, 63;
	add.s64 	%rd48, %rd3, %rd47;
	shr.s64 	%rd49, %rd48, 1;
	and.b64  	%rd50, %rd48, -2;
	sub.s64 	%rd51, %rd3, %rd50;
	shr.s64 	%rd52, %rd51, 63;
	add.s64 	%rd53, %rd52, %rd49;
	shr.s64 	%rd54, %rd53, 63;
	shr.u64 	%rd55, %rd54, 60;
	add.s64 	%rd56, %rd53, %rd55;
	and.b64  	%rd57, %rd56, -16;
	sub.s64 	%rd58, %rd53, %rd57;
	mov.u64 	%rd115, 16;
	add.s64 	%rd59, %rd51, 2;
	setp.lt.s64 	%p5, %rd51, 0;
	mov.u64 	%rd122, 0;
	selp.b64 	%rd60, %rd59, %rd51, %p5;
	shr.s64 	%rd61, %rd60, 63;
	and.b64  	%rd62, %rd61, %rd27;
	add.s64 	%rd63, %rd62, %rd60;
	mul.lo.s64 	%rd64, %rd63, %rd29;
	add.s64 	%rd5, %rd64, %rd25;
	selp.s64 	%rd65, -1, 0, %p1;
	add.s64 	%rd114, %rd4, %rd65;
	add.s64 	%rd66, %rd58, 16;
	setp.lt.s64 	%p6, %rd58, 0;
	selp.b64 	%rd7, %rd66, %rd58, %p6;
	mov.f32 	%f88, 0f7F800000;
	mov.u64 	%rd117, %rd122;

$L__BB0_2:
	mov.u64 	%rd10, %rd115;
	add.s64 	%rd12, %rd117, %rd7;
	setp.ge.s64 	%p7, %rd12, %rd26;
	mov.u32 	%r65, 2139095040;
	@%p7 bra 	$L__BB0_4;

	shr.s64 	%rd67, %rd12, 63;
	and.b64  	%rd68, %rd67, %rd26;
	add.s64 	%rd69, %rd68, %rd12;
	mul.lo.s64 	%rd70, %rd69, %rd28;
	add.s64 	%rd71, %rd5, %rd70;
	ld.u32 	%r65, [%rd71];

$L__BB0_4:
	mov.u64 	%rd120, 2;
	mov.u64 	%rd119, 15;
	mov.u32 	%r66, 1;
	mov.u64 	%rd118, 0;

$L__BB0_5:
	add.s32 	%r16, %r66, -1;
	mov.u32 	%r17, -1;
	mov.u32 	%r18, 31;
	shfl.sync.idx.b32 	%r19|%p8, %r65, %r16, %r18, %r17;
	mov.b32 	%f13, %r19;
	shfl.sync.idx.b32 	%r20|%p9, %r65, %r66, %r18, %r17;
	mov.b32 	%f14, %r20;
	sub.f32 	%f15, %f1, %f13;
	sub.f32 	%f16, %f2, %f14;
	abs.f32 	%f17, %f15;
	abs.f32 	%f18, %f16;
	mov.b32 	%r21, %f18;
	mov.b32 	%r22, %f17;
	min.s32 	%r23, %r21, %r22;
	mov.b32 	%f19, %r23;
	max.s32 	%r24, %r21, %r22;
	mov.b32 	%f20, %r24;
	and.b32  	%r25, %r24, -33554432;
	mov.u32 	%r26, 2122317824;
	sub.s32 	%r27, %r26, %r25;
	mov.b32 	%f21, %r27;
	mul.f32 	%f22, %f19, %f21;
	mul.f32 	%f23, %f20, %f21;
	mul.f32 	%f24, %f22, %f22;
	fma.rn.f32 	%f25, %f23, %f23, %f24;
	sqrt.rn.f32 	%f26, %f25;
	or.b32  	%r28, %r25, 8388608;
	mov.b32 	%f27, %r28;
	mul.f32 	%f28, %f26, %f27;
	setp.eq.f32 	%p10, %f19, 0f00000000;
	selp.f32 	%f29, %f20, %f28, %p10;
	setp.eq.f32 	%p11, %f19, 0f7F800000;
	selp.f32 	%f5, 0f7F800000, %f29, %p11;
	setp.geu.f32 	%p12, %f5, %f88;
	@%p12 bra 	$L__BB0_7;

	shr.u64 	%rd75, %rd118, 63;
	add.s64 	%rd76, %rd118, %rd75;
	shr.s64 	%rd77, %rd76, 1;
	add.s64 	%rd122, %rd77, %rd117;
	mov.f32 	%f88, %f5;

$L__BB0_7:
	setp.ne.s64 	%p13, %rd119, 0;
	selp.b64 	%rd78, -1, 0, %p13;
	add.s64 	%rd79, %rd119, %rd78;
	selp.b64 	%rd80, %rd120, 0, %p13;
	cvt.u32.u64 	%r29, %rd80;
	shfl.sync.idx.b32 	%r32|%p14, %r65, %r29, %r18, %r17;
	mov.b32 	%f30, %r32;
	add.s32 	%r33, %r29, 1;
	shfl.sync.idx.b32 	%r34|%p15, %r65, %r33, %r18, %r17;
	mov.b32 	%f31, %r34;
	sub.f32 	%f32, %f1, %f30;
	sub.f32 	%f33, %f2, %f31;
	abs.f32 	%f34, %f32;
	abs.f32 	%f35, %f33;
	mov.b32 	%r35, %f35;
	mov.b32 	%r36, %f34;
	min.s32 	%r37, %r35, %r36;
	mov.b32 	%f36, %r37;
	max.s32 	%r38, %r35, %r36;
	mov.b32 	%f37, %r38;
	and.b32  	%r39, %r38, -33554432;
	sub.s32 	%r41, %r26, %r39;
	mov.b32 	%f38, %r41;
	mul.f32 	%f39, %f36, %f38;
	mul.f32 	%f40, %f37, %f38;
	mul.f32 	%f41, %f39, %f39;
	fma.rn.f32 	%f42, %f40, %f40, %f41;
	sqrt.rn.f32 	%f43, %f42;
	or.b32  	%r42, %r39, 8388608;
	mov.b32 	%f44, %r42;
	mul.f32 	%f45, %f43, %f44;
	setp.eq.f32 	%p16, %f36, 0f00000000;
	selp.f32 	%f46, %f37, %f45, %p16;
	setp.eq.f32 	%p17, %f36, 0f7F800000;
	selp.f32 	%f47, 0f7F800000, %f46, %p17;
	setp.lt.f32 	%p18, %f47, %f88;
	shr.u64 	%rd81, %rd80, 1;
	add.s64 	%rd82, %rd81, %rd117;
	selp.b64 	%rd83, %rd82, %rd122, %p18;
	selp.f32 	%f48, %f47, %f88, %p18;
	setp.ne.s64 	%p19, %rd79, 0;
	selp.b64 	%rd84, -1, 0, %p19;
	add.s64 	%rd85, %rd79, %rd84;
	add.s64 	%rd86, %rd120, 2;
	selp.b64 	%rd87, %rd86, 0, %p19;
	cvt.u32.u64 	%r43, %rd87;
	shfl.sync.idx.b32 	%r44|%p20, %r65, %r43, %r18, %r17;
	mov.b32 	%f49, %r44;
	add.s32 	%r45, %r43, 1;
	shfl.sync.idx.b32 	%r46|%p21, %r65, %r45, %r18, %r17;
	mov.b32 	%f50, %r46;
	sub.f32 	%f51, %f1, %f49;
	sub.f32 	%f52, %f2, %f50;
	abs.f32 	%f53, %f51;
	abs.f32 	%f54, %f52;
	mov.b32 	%r47, %f54;
	mov.b32 	%r48, %f53;
	min.s32 	%r49, %r47, %r48;
	mov.b32 	%f55, %r49;
	max.s32 	%r50, %r47, %r48;
	mov.b32 	%f56, %r50;
	and.b32  	%r51, %r50, -33554432;
	sub.s32 	%r52, %r26, %r51;
	mov.b32 	%f57, %r52;
	mul.f32 	%f58, %f55, %f57;
	mul.f32 	%f59, %f56, %f57;
	mul.f32 	%f60, %f58, %f58;
	fma.rn.f32 	%f61, %f59, %f59, %f60;
	sqrt.rn.f32 	%f62, %f61;
	or.b32  	%r53, %r51, 8388608;
	mov.b32 	%f63, %r53;
	mul.f32 	%f64, %f62, %f63;
	setp.eq.f32 	%p22, %f55, 0f00000000;
	selp.f32 	%f65, %f56, %f64, %p22;
	setp.eq.f32 	%p23, %f55, 0f7F800000;
	selp.f32 	%f66, 0f7F800000, %f65, %p23;
	setp.lt.f32 	%p24, %f66, %f48;
	shr.u64 	%rd88, %rd87, 1;
	add.s64 	%rd89, %rd88, %rd117;
	selp.b64 	%rd90, %rd89, %rd83, %p24;
	selp.f32 	%f67, %f66, %f48, %p24;
	setp.ne.s64 	%p25, %rd85, 0;
	selp.b64 	%rd91, -1, 0, %p25;
	add.s64 	%rd92, %rd85, %rd91;
	add.s64 	%rd93, %rd120, 4;
	selp.b64 	%rd94, %rd93, 0, %p25;
	cvt.u32.u64 	%r54, %rd94;
	shfl.sync.idx.b32 	%r55|%p26, %r65, %r54, %r18, %r17;
	mov.b32 	%f68, %r55;
	add.s32 	%r56, %r54, 1;
	shfl.sync.idx.b32 	%r57|%p27, %r65, %r56, %r18, %r17;
	mov.b32 	%f69, %r57;
	sub.f32 	%f70, %f1, %f68;
	sub.f32 	%f71, %f2, %f69;
	abs.f32 	%f72, %f70;
	abs.f32 	%f73, %f71;
	mov.b32 	%r58, %f73;
	mov.b32 	%r59, %f72;
	min.s32 	%r60, %r58, %r59;
	mov.b32 	%f74, %r60;
	max.s32 	%r61, %r58, %r59;
	mov.b32 	%f75, %r61;
	and.b32  	%r62, %r61, -33554432;
	sub.s32 	%r63, %r26, %r62;
	mov.b32 	%f76, %r63;
	mul.f32 	%f77, %f74, %f76;
	mul.f32 	%f78, %f75, %f76;
	mul.f32 	%f79, %f77, %f77;
	fma.rn.f32 	%f80, %f78, %f78, %f79;
	sqrt.rn.f32 	%f81, %f80;
	or.b32  	%r64, %r62, 8388608;
	mov.b32 	%f82, %r64;
	mul.f32 	%f83, %f81, %f82;
	setp.eq.f32 	%p28, %f74, 0f00000000;
	selp.f32 	%f84, %f75, %f83, %p28;
	setp.eq.f32 	%p29, %f74, 0f7F800000;
	selp.f32 	%f85, 0f7F800000, %f84, %p29;
	setp.lt.f32 	%p30, %f85, %f67;
	shr.u64 	%rd95, %rd94, 1;
	add.s64 	%rd96, %rd95, %rd117;
	selp.b64 	%rd122, %rd96, %rd90, %p30;
	selp.f32 	%f88, %f85, %f67, %p30;
	setp.ne.s64 	%p31, %rd92, 0;
	add.s64 	%rd120, %rd120, 8;
	selp.b64 	%rd97, -1, 0, %p31;
	add.s64 	%rd119, %rd92, %rd97;
	add.s32 	%r66, %r66, 8;
	add.s64 	%rd118, %rd118, 8;
	@%p31 bra 	$L__BB0_5;

	setp.gt.s64 	%p32, %rd114, 0;
	add.s64 	%rd115, %rd10, 16;
	selp.b64 	%rd98, -1, 0, %p32;
	add.s64 	%rd114, %rd114, %rd98;
	mov.u64 	%rd117, %rd10;
	@%p32 bra 	$L__BB0_2;

	cvt.u32.u64 	%r67, %rd122;

$L__BB0_10:
	ld.param.u64 	%rd109, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	setp.ge.s64 	%p33, %rd2, %rd32;
	setp.ge.s64 	%p34, %rd1, %rd109;
	or.pred  	%p35, %p34, %p33;
	@%p35 bra 	$L__BB0_12;

	ld.param.u64 	%rd113, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.u64 	%rd112, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	ld.param.u64 	%rd111, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.u64 	%rd110, [_ZN5task540_voroni_euclidean_hypot_warp_shfl_kernelB3v58B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	shr.s64 	%rd99, %rd1, 63;
	and.b64  	%rd100, %rd99, %rd110;
	add.s64 	%rd101, %rd100, %rd1;
	shr.s64 	%rd102, %rd2, 63;
	and.b64  	%rd103, %rd102, %rd32;
	add.s64 	%rd104, %rd103, %rd2;
	mul.lo.s64 	%rd105, %rd101, %rd111;
	mul.lo.s64 	%rd106, %rd104, %rd112;
	add.s64 	%rd107, %rd105, %rd113;
	add.s64 	%rd108, %rd107, %rd106;
	st.u32 	[%rd108], %r67;

$L__BB0_12:
	ret;

}