//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii
.common .global .align 8 .u64 _ZN08NumbaEnv6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii;

.visible .entry _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii(
	.param .u64 .ptr .align 1 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_0,
	.param .u64 .ptr .align 1 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_1,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_2,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_3,
	.param .u64 .ptr .align 1 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_4,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_5,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_6,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_7,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_8,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_9,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_10,
	.param .u64 .ptr .align 1 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_11,
	.param .u64 .ptr .align 1 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_12,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_13,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_14,
	.param .u64 .ptr .align 1 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_15,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_16,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_17,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_18,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_19,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_20,
	.param .u64 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_21,
	.param .u32 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_22,
	.param .u32 _ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_23
)
{
	.reg .pred 	%p<66>;
	.reg .b32 	%r<65>;
	.reg .b64 	%rd<50>;

	ld.param.b64 	%rd8, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_4];
	ld.param.b64 	%rd16, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_5];
	ld.param.b64 	%rd17, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_6];
	ld.param.b64 	%rd9, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_8];
	ld.param.b64 	%rd10, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_9];
	ld.param.b64 	%rd11, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_10];
	ld.param.b64 	%rd12, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_17];
	ld.param.b64 	%rd13, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_19];
	ld.param.b64 	%rd14, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_20];
	ld.param.b64 	%rd15, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_21];
	ld.param.b32 	%r7, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_22];
	ld.param.b32 	%r8, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_23];
	mov.u32 	%r9, %tid.x;
	mov.u32 	%r10, %ntid.x;
	mov.u32 	%r11, %ctaid.x;
	mad.lo.s32 	%r12, %r10, %r11, %r9;
	mov.u32 	%r13, %tid.y;
	mov.u32 	%r14, %ntid.y;
	mov.u32 	%r15, %ctaid.y;
	mad.lo.s32 	%r16, %r14, %r15, %r13;
	cvt.s64.s32 	%rd1, %r12;
	setp.le.s64 	%p4, %rd16, %rd1;
	cvt.u64.u32 	%rd2, %r16;
	setp.le.u64 	%p5, %rd17, %rd2;
	or.pred 	%p6, %p4, %p5;
	@%p6 bra 	$L__BB0_1;
	bra.uni 	$L__BB0_2;
$L__BB0_1:
	ret;
$L__BB0_2:
	cvt.u32.u64 	%r17, %rd1;
	setp.lt.s32 	%p7, %r17, 0;
	selp.b64 	%rd18, %rd17, 0, %p7;
	add.s64 	%rd19, %rd18, %rd1;
	mul.lo.s64 	%rd20, %rd9, %rd2;
	mad.lo.s64 	%rd21, %rd10, %rd19, %rd20;
	add.s64 	%rd22, %rd21, %rd8;
	ld.b32 	%r63, [%rd22];
	add.s64 	%rd23, %rd22, %rd11;
	ld.b32 	%r62, [%rd23];
	setp.eq.b32 	%p8, %r63, -1;
	setp.eq.b32 	%p9, %r62, -1;
	or.pred 	%p10, %p8, %p9;
	mov.b32 	%r61, 2147483647;
	@%p10 bra 	$L__BB0_4;
	cvt.u32.u64 	%r18, %rd2;
	sub.s32 	%r19, %r17, %r63;
	sub.s32 	%r20, %r18, %r62;
	abs.s32 	%r21, %r19;
	abs.s32 	%r22, %r20;
	add.s32 	%r61, %r22, %r21;
$L__BB0_4:
	sub.s32 	%r23, %r17, %r7;
	setp.gt.s32 	%p11, %r23, -1;
	setp.lt.s32 	%p12, %r23, %r8;
	and.pred 	%p1, %p11, %p12;
	cvt.u64.u32 	%rd24, %r23;
	mul.lo.s64 	%rd3, %rd10, %rd24;
	setp.gt.s32 	%p13, %r17, -1;
	setp.lt.s32 	%p14, %r17, %r8;
	and.pred 	%p2, %p13, %p14;
	and.b64 	%rd25, %rd1, 4294967295;
	mul.lo.s64 	%rd4, %rd10, %rd25;
	add.s32 	%r24, %r7, %r17;
	setp.gt.s32 	%p15, %r24, -1;
	setp.lt.s32 	%p16, %r24, %r8;
	and.pred 	%p3, %p15, %p16;
	cvt.u64.u32 	%rd26, %r24;
	mul.lo.s64 	%rd5, %rd10, %rd26;
	mov.b64 	%rd6, 0;
	not.pred 	%p30, %p2;
$L__BB0_5:
	mov.b32 	%r64, -1;
	mov.pred 	%p65, 0;
	setp.eq.b64 	%p17, %rd6, 2;
	@%p17 bra 	$L__BB0_26;
	setp.eq.b64 	%p18, %rd6, 1;
	@%p18 bra 	$L__BB0_25;
$L__BB0_7:
	cvt.u32.u64 	%r25, %rd2;
	add.s64 	%rd6, %rd6, 1;
	mad.lo.s32 	%r3, %r64, %r7, %r25;
	cvt.u64.u32 	%rd27, %r3;
	mul.lo.s64 	%rd7, %rd9, %rd27;
	@%p65 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_14;
$L__BB0_8:
	setp.lt.s32 	%p46, %r3, %r8;
	setp.gt.s32 	%p47, %r3, -1;
	and.pred 	%p48, %p1, %p47;
	and.pred 	%p49, %p48, %p46;
	@%p49 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_11;
$L__BB0_9:
	add.s64 	%rd37, %rd3, %rd7;
	add.s64 	%rd38, %rd37, %rd8;
	ld.b32 	%r1, [%rd38];
	add.s64 	%rd39, %rd38, %rd11;
	ld.b32 	%r47, [%rd39];
	setp.eq.b32 	%p50, %r1, -1;
	setp.eq.b32 	%p51, %r47, -1;
	or.pred 	%p52, %p50, %p51;
	@%p52 bra 	$L__BB0_11;
	cvt.u32.u64 	%r48, %rd2;
	sub.s32 	%r49, %r17, %r1;
	sub.s32 	%r50, %r48, %r47;
	abs.s32 	%r51, %r49;
	abs.s32 	%r52, %r50;
	add.s32 	%r53, %r52, %r51;
	setp.lt.s32 	%p53, %r53, %r61;
	min.s32 	%r61, %r53, %r61;
	selp.b32 	%r62, %r47, %r62, %p53;
	selp.b32 	%r63, %r1, %r63, %p53;
$L__BB0_11:
	setp.ge.s32 	%p54, %r3, %r8;
	setp.lt.s32 	%p55, %r3, 0;
	not.pred 	%p56, %p3;
	or.pred 	%p57, %p56, %p55;
	or.pred 	%p58, %p57, %p54;
	@%p58 bra 	$L__BB0_23;
	add.s64 	%rd40, %rd5, %rd7;
	add.s64 	%rd41, %rd40, %rd8;
	ld.b32 	%r2, [%rd41];
	add.s64 	%rd42, %rd41, %rd11;
	ld.b32 	%r54, [%rd42];
	setp.eq.b32 	%p59, %r2, -1;
	setp.eq.b32 	%p60, %r54, -1;
	or.pred 	%p61, %p59, %p60;
	@%p61 bra 	$L__BB0_23;
	cvt.u32.u64 	%r55, %rd2;
	sub.s32 	%r56, %r17, %r2;
	sub.s32 	%r57, %r55, %r54;
	abs.s32 	%r58, %r56;
	abs.s32 	%r59, %r57;
	add.s32 	%r60, %r59, %r58;
	setp.lt.s32 	%p62, %r60, %r61;
	min.s32 	%r61, %r60, %r61;
	selp.b32 	%r62, %r54, %r62, %p62;
	selp.b32 	%r63, %r2, %r63, %p62;
	bra.uni 	$L__BB0_23;
$L__BB0_14:
	setp.ge.s32 	%p19, %r3, %r8;
	setp.lt.s32 	%p20, %r3, 0;
	not.pred 	%p21, %p1;
	or.pred 	%p22, %p21, %p20;
	or.pred 	%p23, %p22, %p19;
	@%p23 bra 	$L__BB0_17;
	add.s64 	%rd28, %rd3, %rd7;
	add.s64 	%rd29, %rd28, %rd8;
	ld.b32 	%r4, [%rd29];
	add.s64 	%rd30, %rd29, %rd11;
	ld.b32 	%r26, [%rd30];
	setp.eq.b32 	%p24, %r4, -1;
	setp.eq.b32 	%p25, %r26, -1;
	or.pred 	%p26, %p24, %p25;
	@%p26 bra 	$L__BB0_17;
	cvt.u32.u64 	%r27, %rd2;
	sub.s32 	%r28, %r17, %r4;
	sub.s32 	%r29, %r27, %r26;
	abs.s32 	%r30, %r28;
	abs.s32 	%r31, %r29;
	add.s32 	%r32, %r31, %r30;
	setp.lt.s32 	%p27, %r32, %r61;
	min.s32 	%r61, %r32, %r61;
	selp.b32 	%r62, %r26, %r62, %p27;
	selp.b32 	%r63, %r4, %r63, %p27;
$L__BB0_17:
	setp.ge.s32 	%p28, %r3, %r8;
	setp.lt.s32 	%p29, %r3, 0;
	or.pred 	%p31, %p30, %p29;
	or.pred 	%p32, %p31, %p28;
	@%p32 bra 	$L__BB0_20;
	add.s64 	%rd31, %rd4, %rd7;
	add.s64 	%rd32, %rd31, %rd8;
	ld.b32 	%r5, [%rd32];
	add.s64 	%rd33, %rd32, %rd11;
	ld.b32 	%r33, [%rd33];
	setp.eq.b32 	%p33, %r5, -1;
	setp.eq.b32 	%p34, %r33, -1;
	or.pred 	%p35, %p33, %p34;
	@%p35 bra 	$L__BB0_20;
	cvt.u32.u64 	%r34, %rd2;
	sub.s32 	%r35, %r17, %r5;
	sub.s32 	%r36, %r34, %r33;
	abs.s32 	%r37, %r35;
	abs.s32 	%r38, %r36;
	add.s32 	%r39, %r38, %r37;
	setp.lt.s32 	%p36, %r39, %r61;
	min.s32 	%r61, %r39, %r61;
	selp.b32 	%r62, %r33, %r62, %p36;
	selp.b32 	%r63, %r5, %r63, %p36;
$L__BB0_20:
	setp.ge.s32 	%p37, %r3, %r8;
	setp.lt.s32 	%p38, %r3, 0;
	not.pred 	%p39, %p3;
	or.pred 	%p40, %p39, %p38;
	or.pred 	%p41, %p40, %p37;
	@%p41 bra 	$L__BB0_23;
	add.s64 	%rd34, %rd5, %rd7;
	add.s64 	%rd35, %rd34, %rd8;
	ld.b32 	%r6, [%rd35];
	add.s64 	%rd36, %rd35, %rd11;
	ld.b32 	%r40, [%rd36];
	setp.eq.b32 	%p42, %r6, -1;
	setp.eq.b32 	%p43, %r40, -1;
	or.pred 	%p44, %p42, %p43;
	@%p44 bra 	$L__BB0_23;
	cvt.u32.u64 	%r41, %rd2;
	sub.s32 	%r42, %r17, %r6;
	sub.s32 	%r43, %r41, %r40;
	abs.s32 	%r44, %r42;
	abs.s32 	%r45, %r43;
	add.s32 	%r46, %r45, %r44;
	setp.lt.s32 	%p45, %r46, %r61;
	min.s32 	%r61, %r46, %r61;
	selp.b32 	%r62, %r40, %r62, %p45;
	selp.b32 	%r63, %r6, %r63, %p45;
$L__BB0_23:
	setp.eq.b64 	%p63, %rd6, 3;
	@%p63 bra 	$L__BB0_24;
	bra.uni 	$L__BB0_5;
$L__BB0_24:
	ld.param.b64 	%rd49, [_ZN6task6a32_jfa_pass_manhattan_kernelB3v78B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_15];
	setp.lt.s32 	%p64, %r17, 0;
	selp.b64 	%rd43, %rd12, 0, %p64;
	add.s64 	%rd44, %rd43, %rd1;
	mul.lo.s64 	%rd45, %rd13, %rd2;
	mad.lo.s64 	%rd46, %rd14, %rd44, %rd45;
	add.s64 	%rd47, %rd46, %rd49;
	st.b32 	[%rd47], %r63;
	add.s64 	%rd48, %rd47, %rd15;
	st.b32 	[%rd48], %r62;
	bra.uni 	$L__BB0_1;
$L__BB0_25:
	mov.b32 	%r64, 0;
	mov.pred 	%p65, -1;
	bra.uni 	$L__BB0_7;
$L__BB0_26:
	mov.b32 	%r64, 1;
	bra.uni 	$L__BB0_7;

}
