//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;
.visible .shared .align 4 .b8 _cudapy_smem_1[1024];

.visible .entry _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 .ptr .align 1 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 .ptr .align 1 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 .ptr .align 1 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 .ptr .align 1 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 .ptr .align 1 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 .ptr .align 1 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<18>;
	.reg .b32 	%r<45>;
	.reg .b64 	%rd<88>;

	ld.param.b64 	%rd8, [_ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.b64 	%rd9, [_ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.b64 	%rd10, [_ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.b64 	%rd11, [_ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.b64 	%rd12, [_ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	mov.u32 	%r4, %tid.x;
	cvt.u64.u32 	%rd13, %r4;
	mov.u32 	%r5, %ntid.x;
	mov.u32 	%r6, %ctaid.x;
	mul.wide.u32 	%rd14, %r5, %r6;
	add.s64 	%rd1, %rd14, %rd13;
	mov.u32 	%r7, %tid.y;
	mov.u32 	%r8, %ntid.y;
	mov.u32 	%r9, %ctaid.y;
	mad.lo.s32 	%r10, %r8, %r9, %r7;
	cvt.u64.u32 	%rd2, %r10;
	cvt.rn.f32.u64 	%r11, %rd1;
	cvt.rn.f32.u64 	%r12, %rd11;
	div.rn.f32 	%r1, %r11, %r12;
	cvt.rn.f32.u32 	%r13, %r10;
	cvt.rn.f32.s64 	%r14, %rd12;
	div.rn.f32 	%r2, %r13, %r14;
	mad.lo.s32 	%r3, %r7, %r5, %r4;
	add.s64 	%rd15, %rd9, 127;
	shr.u64 	%rd16, %rd15, 7;
	setp.gt.s64 	%p1, %rd9, 0;
	selp.b64 	%rd17, %rd16, 0, %p1;
	setp.eq.b64 	%p2, %rd17, 0;
	setp.ne.b64 	%p3, %rd17, 0;
	selp.b64 	%rd18, -1, 0, %p3;
	add.s64 	%rd81, %rd17, %rd18;
	mov.b32 	%r44, 0;
	@%p2 bra 	$L__BB0_10;
	cvt.u64.u32 	%rd19, %r3;
	and.b64 	%rd20, %rd19, 1;
	mul.wide.u32 	%rd21, %r3, 4;
	and.b64 	%rd22, %rd21, 1020;
	mov.b64 	%rd23, _cudapy_smem_1;
	add.s64 	%rd3, %rd23, %rd22;
	mad.lo.s64 	%rd4, %rd10, %rd20, %rd8;
	shr.u64 	%rd5, %rd19, 1;
	mov.b32 	%r43, 0f7F800000;
	mov.b64 	%rd82, 128;
	mov.b64 	%rd86, 0;
	mov.b64 	%rd83, %rd86;
$L__BB0_2:
	mov.b64 	%rd6, %rd82;
	setp.gt.u32 	%p4, %r3, 255;
	@%p4 bra 	$L__BB0_6;
	add.s64 	%rd7, %rd83, %rd5;
	setp.ge.s64 	%p5, %rd7, %rd9;
	@%p5 bra 	$L__BB0_5;
	ld.param.b64 	%rd77, [_ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	shr.s64 	%rd24, %rd7, 63;
	and.b64 	%rd25, %rd24, %rd9;
	add.s64 	%rd26, %rd25, %rd7;
	mad.lo.s64 	%rd27, %rd26, %rd77, %rd4;
	ld.b32 	%r15, [%rd27];
	st.shared.b32 	[%rd3], %r15;
	bra.uni 	$L__BB0_6;
$L__BB0_5:
	st.shared.b32 	[%rd3], 2139095040;
$L__BB0_6:
	bar.sync 	0;
	mov.b64 	%rd87, 0;
	mov.b64 	%rd85, 1;
	mov.b64 	%rd84, 127;
$L__BB0_7:
	shr.u64 	%rd28, %rd87, 56;
	and.b64 	%rd29, %rd28, 128;
	add.s64 	%rd30, %rd29, %rd87;
	shl.b64 	%rd31, %rd30, 3;
	mov.b64 	%rd32, _cudapy_smem_1;
	add.s64 	%rd33, %rd32, %rd31;
	cvta.shared.u64 	%rd34, %rd32;
	add.s64 	%rd35, %rd34, %rd31;
	ld.shared.b32 	%r16, [%rd33];
	ld.b32 	%r17, [%rd35+4];
	sub.f32 	%r18, %r1, %r16;
	sub.f32 	%r19, %r2, %r17;
	mul.f32 	%r20, %r19, %r19;
	fma.rn.f32 	%r21, %r18, %r18, %r20;
	setp.lt.f32 	%p6, %r21, %r43;
	add.s64 	%rd36, %rd87, %rd83;
	selp.b64 	%rd37, %rd36, %rd86, %p6;
	selp.f32 	%r22, %r21, %r43, %p6;
	setp.ne.b64 	%p7, %rd84, 0;
	selp.b64 	%rd38, 1, 0, %p7;
	add.s64 	%rd39, %rd85, %rd38;
	selp.b64 	%rd40, -1, 0, %p7;
	add.s64 	%rd41, %rd84, %rd40;
	shr.u64 	%rd42, %rd85, 56;
	and.b64 	%rd43, %rd42, 128;
	add.s64 	%rd44, %rd43, %rd85;
	shl.b64 	%rd45, %rd44, 3;
	add.s64 	%rd46, %rd32, %rd45;
	add.s64 	%rd47, %rd34, %rd45;
	ld.shared.b32 	%r23, [%rd46];
	ld.b32 	%r24, [%rd47+4];
	sub.f32 	%r25, %r1, %r23;
	sub.f32 	%r26, %r2, %r24;
	mul.f32 	%r27, %r26, %r26;
	fma.rn.f32 	%r28, %r25, %r25, %r27;
	setp.lt.f32 	%p8, %r28, %r22;
	add.s64 	%rd48, %rd85, %rd83;
	selp.b64 	%rd49, %rd48, %rd37, %p8;
	selp.f32 	%r29, %r28, %r22, %p8;
	setp.ne.b64 	%p9, %rd41, 0;
	selp.b64 	%rd50, 1, 0, %p9;
	add.s64 	%rd51, %rd39, %rd50;
	selp.b64 	%rd52, -1, 0, %p9;
	add.s64 	%rd53, %rd41, %rd52;
	shr.u64 	%rd54, %rd39, 56;
	and.b64 	%rd55, %rd54, 128;
	add.s64 	%rd56, %rd55, %rd39;
	shl.b64 	%rd57, %rd56, 3;
	add.s64 	%rd58, %rd32, %rd57;
	add.s64 	%rd59, %rd34, %rd57;
	ld.shared.b32 	%r30, [%rd58];
	ld.b32 	%r31, [%rd59+4];
	sub.f32 	%r32, %r1, %r30;
	sub.f32 	%r33, %r2, %r31;
	mul.f32 	%r34, %r33, %r33;
	fma.rn.f32 	%r35, %r32, %r32, %r34;
	setp.lt.f32 	%p10, %r35, %r29;
	add.s64 	%rd60, %rd48, %rd38;
	selp.b64 	%rd61, %rd60, %rd49, %p10;
	selp.f32 	%r36, %r35, %r29, %p10;
	setp.ne.b64 	%p11, %rd53, 0;
	selp.b64 	%rd62, 1, 0, %p11;
	add.s64 	%rd87, %rd51, %rd62;
	selp.b64 	%rd63, -1, 0, %p11;
	add.s64 	%rd64, %rd53, %rd63;
	shr.u64 	%rd65, %rd51, 56;
	and.b64 	%rd66, %rd65, 128;
	add.s64 	%rd67, %rd66, %rd51;
	shl.b64 	%rd68, %rd67, 3;
	add.s64 	%rd69, %rd32, %rd68;
	add.s64 	%rd70, %rd34, %rd68;
	ld.shared.b32 	%r37, [%rd69];
	ld.b32 	%r38, [%rd70+4];
	sub.f32 	%r39, %r1, %r37;
	sub.f32 	%r40, %r2, %r38;
	mul.f32 	%r41, %r40, %r40;
	fma.rn.f32 	%r42, %r39, %r39, %r41;
	setp.lt.f32 	%p12, %r42, %r36;
	add.s64 	%rd71, %rd60, %rd50;
	selp.b64 	%rd86, %rd71, %rd61, %p12;
	selp.f32 	%r43, %r42, %r36, %p12;
	setp.ne.b64 	%p13, %rd64, 0;
	selp.b64 	%rd72, 1, 0, %p13;
	add.s64 	%rd85, %rd87, %rd72;
	selp.b64 	%rd73, -1, 0, %p13;
	add.s64 	%rd84, %rd64, %rd73;
	@%p13 bra 	$L__BB0_7;
	bar.sync 	0;
	setp.gt.s64 	%p14, %rd81, 0;
	add.s64 	%rd82, %rd6, 128;
	selp.b64 	%rd74, -1, 0, %p14;
	add.s64 	%rd81, %rd81, %rd74;
	mov.b64 	%rd83, %rd6;
	@%p14 bra 	$L__BB0_2;
	cvt.u32.u64 	%r44, %rd86;
$L__BB0_10:
	setp.lt.u64 	%p15, %rd1, %rd11;
	setp.gt.s64 	%p16, %rd12, %rd2;
	and.pred 	%p17, %p15, %p16;
	@%p17 bra 	$L__BB0_12;
$L__BB0_11:
	ret;
$L__BB0_12:
	ld.param.b64 	%rd80, [_ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	ld.param.b64 	%rd79, [_ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.b64 	%rd78, [_ZN5task536_voroni_euclidean_grid_stride_kernelB3v52B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	mad.lo.s64 	%rd75, %rd79, %rd1, %rd78;
	mad.lo.s64 	%rd76, %rd80, %rd2, %rd75;
	st.b32 	[%rd76], %r44;
	bra.uni 	$L__BB0_11;

}