//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii
.common .global .align 8 .u64 _ZN08NumbaEnv6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii;
.visible .shared .align 4 .b8 _cudapy_smem_3[4608];

.visible .entry _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii(
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_0,
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_1,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_2,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_3,
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_4,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_5,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_6,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_7,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_8,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_9,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_10,
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_11,
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_12,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_13,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_14,
	.param .u64 .ptr .align 1 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_15,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_16,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_17,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_18,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_19,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_20,
	.param .u64 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_21,
	.param .u32 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_22,
	.param .u32 _ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_23
)
{
	.reg .pred 	%p<131>;
	.reg .b32 	%r<122>;
	.reg .b64 	%rd<210>;

	ld.param.b64 	%rd34, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_4];
	ld.param.b64 	%rd35, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_5];
	ld.param.b64 	%rd36, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_6];
	ld.param.b64 	%rd37, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_8];
	ld.param.b64 	%rd38, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_9];
	ld.param.b64 	%rd39, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_10];
	ld.param.b64 	%rd40, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_19];
	ld.param.b64 	%rd41, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_21];
	ld.param.b32 	%r21, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_22];
	ld.param.b32 	%r22, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_23];
	mov.u32 	%r1, %tid.x;
	mov.u32 	%r2, %tid.y;
	mov.u32 	%r23, %ntid.x;
	mov.u32 	%r3, %ctaid.x;
	mad.lo.s32 	%r4, %r23, %r3, %r1;
	mov.u32 	%r24, %ntid.y;
	mov.u32 	%r5, %ctaid.y;
	mad.lo.s32 	%r6, %r24, %r5, %r2;
	setp.gt.s32 	%p6, %r21, 7;
	@%p6 bra 	$L__BB0_52;
	mul.wide.u32 	%rd67, %r3, 16;
	cvt.s64.s32 	%rd1, %r21;
	sub.s64 	%rd2, %rd67, %rd1;
	mul.wide.u32 	%rd68, %r5, 16;
	sub.s64 	%rd3, %rd68, %rd1;
	mul.wide.s32 	%rd69, %r21, 2;
	add.s64 	%rd4, %rd69, 16;
	mul.lo.s64 	%rd70, %rd4, %rd4;
	shl.b32 	%r55, %r2, 4;
	add.s32 	%r56, %r55, %r1;
	cvt.u64.u32 	%rd206, %r56;
	sub.s64 	%rd71, %rd70, %rd206;
	add.s64 	%rd72, %rd71, 255;
	shr.u64 	%rd73, %rd72, 8;
	setp.gt.s64 	%p67, %rd71, 0;
	selp.b64 	%rd74, %rd73, 0, %p67;
	setp.eq.b64 	%p68, %rd74, 0;
	setp.ne.b64 	%p69, %rd74, 0;
	selp.b64 	%rd75, -1, 0, %p69;
	add.s64 	%rd205, %rd74, %rd75;
	@%p68 bra 	$L__BB0_32;
	setp.eq.b64 	%p70, %rd4, 0;
	cvt.s64.s32 	%rd5, %r22;
	@%p70 bra 	$L__BB0_6;
	cvt.u32.u64 	%r57, %rd4;
$L__BB0_4:
	or.b64 	%rd76, %rd206, %rd4;
	and.b64 	%rd77, %rd76, -4294967296;
	setp.ne.b64 	%p71, %rd77, 0;
	@%p71 bra 	$L__BB0_27;
	cvt.u32.u64 	%r58, %rd206;
	div.u32 	%r59, %r58, %r57;
	mul.lo.s32 	%r60, %r59, %r57;
	sub.s32 	%r61, %r58, %r60;
	cvt.u64.u32 	%rd207, %r59;
	cvt.u64.u32 	%rd208, %r61;
	bra.uni 	$L__BB0_28;
$L__BB0_6:
	min.s64 	%rd6, %rd205, 0;
	sub.s64 	%rd111, %rd205, %rd6;
	add.s64 	%rd112, %rd111, 1;
	and.b64 	%rd204, %rd112, 3;
	setp.eq.b64 	%p79, %rd204, 0;
	@%p79 bra 	$L__BB0_12;
	or.b64 	%rd113, %rd2, %rd3;
	setp.gt.s64 	%p80, %rd113, -1;
	max.s64 	%rd114, %rd2, %rd3;
	setp.lt.s64 	%p81, %rd114, %rd5;
	and.pred 	%p1, %p81, %p80;
	mul.lo.s64 	%rd115, %rd2, %rd38;
	mad.lo.s64 	%rd116, %rd3, %rd37, %rd115;
	add.s64 	%rd7, %rd116, %rd34;
	add.s64 	%rd8, %rd7, %rd39;
$L__BB0_8:
	.pragma "nounroll";
	@%p1 bra 	$L__BB0_10;
	st.shared.b32 	[_cudapy_smem_3], -1;
	mov.b32 	%r111, -1;
	bra.uni 	$L__BB0_11;
$L__BB0_10:
	ld.b32 	%r63, [%rd7];
	st.shared.b32 	[_cudapy_smem_3], %r63;
	ld.b32 	%r111, [%rd8];
$L__BB0_11:
	st.shared.b32 	[_cudapy_smem_3+4], %r111;
	setp.gt.s64 	%p82, %rd205, 0;
	selp.b64 	%rd117, -1, 0, %p82;
	add.s64 	%rd205, %rd205, %rd117;
	add.s64 	%rd204, %rd204, -1;
	setp.ne.b64 	%p83, %rd204, 0;
	@%p83 bra 	$L__BB0_8;
$L__BB0_12:
	setp.lt.u64 	%p84, %rd111, 3;
	@%p84 bra 	$L__BB0_32;
	or.b64 	%rd118, %rd2, %rd3;
	setp.gt.s64 	%p85, %rd118, -1;
	max.s64 	%rd119, %rd2, %rd3;
	setp.lt.s64 	%p86, %rd119, %rd5;
	and.pred 	%p2, %p86, %p85;
	mul.lo.s64 	%rd120, %rd2, %rd38;
	mad.lo.s64 	%rd121, %rd3, %rd37, %rd120;
	add.s64 	%rd9, %rd121, %rd34;
	add.s64 	%rd10, %rd9, %rd39;
$L__BB0_14:
	@%p2 bra 	$L__BB0_16;
	st.shared.b32 	[_cudapy_smem_3], -1;
	mov.b32 	%r112, -1;
	bra.uni 	$L__BB0_17;
$L__BB0_16:
	ld.b32 	%r64, [%rd9];
	st.shared.b32 	[_cudapy_smem_3], %r64;
	ld.b32 	%r112, [%rd10];
$L__BB0_17:
	st.shared.b32 	[_cudapy_smem_3+4], %r112;
	@%p2 bra 	$L__BB0_19;
	st.shared.b32 	[_cudapy_smem_3], -1;
	mov.b32 	%r113, -1;
	bra.uni 	$L__BB0_20;
$L__BB0_19:
	ld.b32 	%r65, [%rd9];
	st.shared.b32 	[_cudapy_smem_3], %r65;
	ld.b32 	%r113, [%rd10];
$L__BB0_20:
	setp.gt.s64 	%p87, %rd205, 0;
	selp.b64 	%rd122, -1, 0, %p87;
	add.s64 	%rd11, %rd205, %rd122;
	st.shared.b32 	[_cudapy_smem_3+4], %r113;
	@%p2 bra 	$L__BB0_22;
	st.shared.b32 	[_cudapy_smem_3], -1;
	mov.b32 	%r114, -1;
	bra.uni 	$L__BB0_23;
$L__BB0_22:
	ld.b32 	%r66, [%rd9];
	st.shared.b32 	[_cudapy_smem_3], %r66;
	ld.b32 	%r114, [%rd10];
$L__BB0_23:
	setp.gt.s64 	%p88, %rd11, 0;
	selp.b64 	%rd123, -1, 0, %p88;
	add.s64 	%rd12, %rd11, %rd123;
	st.shared.b32 	[_cudapy_smem_3+4], %r114;
	@%p2 bra 	$L__BB0_25;
	st.shared.b32 	[_cudapy_smem_3], -1;
	mov.b32 	%r115, -1;
	bra.uni 	$L__BB0_26;
$L__BB0_25:
	ld.b32 	%r67, [%rd9];
	st.shared.b32 	[_cudapy_smem_3], %r67;
	ld.b32 	%r115, [%rd10];
$L__BB0_26:
	setp.gt.s64 	%p89, %rd12, 0;
	selp.b64 	%rd124, -1, 0, %p89;
	add.s64 	%rd125, %rd12, %rd124;
	st.shared.b32 	[_cudapy_smem_3+4], %r115;
	setp.gt.s64 	%p90, %rd125, 0;
	selp.b64 	%rd126, -1, 0, %p90;
	add.s64 	%rd205, %rd125, %rd126;
	@%p90 bra 	$L__BB0_14;
	bra.uni 	$L__BB0_32;
$L__BB0_27:
	div.s64 	%rd207, %rd206, %rd4;
	mul.lo.s64 	%rd78, %rd207, %rd4;
	sub.s64 	%rd208, %rd206, %rd78;
$L__BB0_28:
	xor.b64 	%rd79, %rd208, %rd4;
	setp.lt.s64 	%p72, %rd79, 0;
	setp.ne.b64 	%p73, %rd208, 0;
	and.pred 	%p74, %p73, %p72;
	selp.b64 	%rd80, %rd4, 0, %p74;
	add.s64 	%rd13, %rd80, %rd208;
	selp.b64 	%rd81, -1, 0, %p74;
	add.s64 	%rd14, %rd207, %rd81;
	add.s64 	%rd15, %rd13, %rd2;
	add.s64 	%rd16, %rd14, %rd3;
	or.b64 	%rd82, %rd15, %rd16;
	setp.lt.s64 	%p75, %rd82, 0;
	max.s64 	%rd83, %rd15, %rd16;
	setp.ge.s64 	%p76, %rd83, %rd5;
	or.pred 	%p77, %p76, %p75;
	@%p77 bra 	$L__BB0_30;
	mul.lo.s64 	%rd94, %rd15, %rd38;
	mad.lo.s64 	%rd95, %rd16, %rd37, %rd94;
	add.s64 	%rd96, %rd95, %rd34;
	ld.b32 	%r62, [%rd96];
	shr.s64 	%rd97, %rd14, 63;
	and.b64 	%rd98, %rd97, 24;
	add.s64 	%rd99, %rd98, %rd14;
	shr.s64 	%rd100, %rd13, 63;
	and.b64 	%rd101, %rd100, 24;
	add.s64 	%rd102, %rd101, %rd13;
	shl.b64 	%rd103, %rd102, 1;
	mad.lo.s64 	%rd209, %rd99, 48, %rd103;
	shl.b64 	%rd104, %rd209, 2;
	mov.b64 	%rd105, _cudapy_smem_3;
	add.s64 	%rd106, %rd105, %rd104;
	st.shared.b32 	[%rd106], %r62;
	add.s64 	%rd107, %rd96, %rd39;
	ld.b32 	%r116, [%rd107];
	bra.uni 	$L__BB0_31;
$L__BB0_30:
	shr.s64 	%rd84, %rd14, 63;
	and.b64 	%rd85, %rd84, 24;
	add.s64 	%rd86, %rd85, %rd14;
	shr.s64 	%rd87, %rd13, 63;
	and.b64 	%rd88, %rd87, 24;
	add.s64 	%rd89, %rd88, %rd13;
	shl.b64 	%rd90, %rd89, 1;
	mad.lo.s64 	%rd209, %rd86, 48, %rd90;
	shl.b64 	%rd91, %rd209, 2;
	mov.b64 	%rd92, _cudapy_smem_3;
	add.s64 	%rd93, %rd92, %rd91;
	st.shared.b32 	[%rd93], -1;
	mov.b32 	%r116, -1;
$L__BB0_31:
	shl.b64 	%rd108, %rd209, 2;
	mov.b64 	%rd109, _cudapy_smem_3;
	add.s64 	%rd110, %rd109, %rd108;
	st.shared.b32 	[%rd110+4], %r116;
	add.s64 	%rd17, %rd205, -1;
	add.s64 	%rd206, %rd206, 256;
	setp.gt.s64 	%p78, %rd205, 0;
	mov.b64 	%rd205, %rd17;
	@%p78 bra 	$L__BB0_4;
$L__BB0_32:
	bar.sync 	0;
	cvt.s64.s32 	%rd127, %r4;
	setp.le.s64 	%p91, %rd35, %rd127;
	cvt.u64.u32 	%rd128, %r6;
	setp.le.u64 	%p92, %rd36, %rd128;
	or.pred 	%p93, %p91, %p92;
	@%p93 bra 	$L__BB0_33;
	bra.uni 	$L__BB0_34;
$L__BB0_33:
	ret;
$L__BB0_34:
	cvt.u64.u32 	%rd129, %r1;
	add.s64 	%rd18, %rd1, %rd129;
	cvt.u64.u32 	%rd130, %r2;
	add.s64 	%rd19, %rd1, %rd130;
	shr.s64 	%rd131, %rd19, 63;
	and.b64 	%rd132, %rd131, 24;
	add.s64 	%rd133, %rd132, %rd19;
	shr.s64 	%rd134, %rd18, 63;
	and.b64 	%rd135, %rd134, 24;
	add.s64 	%rd136, %rd135, %rd18;
	mul.lo.s64 	%rd20, %rd133, 48;
	shl.b64 	%rd21, %rd136, 1;
	add.s64 	%rd137, %rd20, %rd21;
	shl.b64 	%rd138, %rd137, 2;
	mov.b64 	%rd139, _cudapy_smem_3;
	add.s64 	%rd140, %rd139, %rd138;
	ld.shared.b32 	%r120, [%rd140];
	ld.shared.b32 	%r119, [%rd140+4];
	setp.eq.b32 	%p94, %r120, -1;
	setp.eq.b32 	%p95, %r119, -1;
	or.pred 	%p96, %p94, %p95;
	mov.b32 	%r117, 2147483647;
	@%p96 bra 	$L__BB0_36;
	sub.s32 	%r68, %r4, %r120;
	sub.s32 	%r69, %r6, %r119;
	mul.lo.s32 	%r70, %r68, %r68;
	mad.lo.s32 	%r117, %r69, %r69, %r70;
$L__BB0_36:
	cvt.u64.u32 	%rd22, %r21;
	sub.s64 	%rd141, %rd19, %rd22;
	cvt.s64.s32 	%rd142, %rd141;
	shr.s64 	%rd143, %rd142, 63;
	and.b64 	%rd144, %rd143, 24;
	add.s64 	%rd145, %rd144, %rd142;
	mul.lo.s64 	%rd23, %rd145, 48;
	sub.s64 	%rd146, %rd18, %rd22;
	cvt.s64.s32 	%rd147, %rd146;
	shr.s64 	%rd148, %rd147, 63;
	and.b64 	%rd149, %rd148, 24;
	add.s64 	%rd150, %rd149, %rd147;
	shl.b64 	%rd24, %rd150, 1;
	add.s64 	%rd151, %rd24, %rd23;
	shl.b64 	%rd152, %rd151, 2;
	mov.b64 	%rd153, _cudapy_smem_3;
	add.s64 	%rd154, %rd153, %rd152;
	ld.shared.b32 	%r7, [%rd154];
	ld.shared.b32 	%r71, [%rd154+4];
	setp.eq.b32 	%p97, %r7, -1;
	setp.eq.b32 	%p98, %r71, -1;
	or.pred 	%p99, %p97, %p98;
	@%p99 bra 	$L__BB0_38;
	sub.s32 	%r72, %r4, %r7;
	sub.s32 	%r73, %r6, %r71;
	mul.lo.s32 	%r74, %r72, %r72;
	mad.lo.s32 	%r75, %r73, %r73, %r74;
	setp.lt.s32 	%p100, %r75, %r117;
	min.s32 	%r117, %r75, %r117;
	selp.b32 	%r119, %r71, %r119, %p100;
	selp.b32 	%r120, %r7, %r120, %p100;
$L__BB0_38:
	add.s64 	%rd155, %rd21, %rd23;
	shl.b64 	%rd156, %rd155, 2;
	mov.b64 	%rd157, _cudapy_smem_3;
	add.s64 	%rd158, %rd157, %rd156;
	ld.shared.b32 	%r8, [%rd158];
	ld.shared.b32 	%r76, [%rd158+4];
	setp.eq.b32 	%p101, %r8, -1;
	setp.eq.b32 	%p102, %r76, -1;
	or.pred 	%p103, %p101, %p102;
	@%p103 bra 	$L__BB0_40;
	sub.s32 	%r77, %r4, %r8;
	sub.s32 	%r78, %r6, %r76;
	mul.lo.s32 	%r79, %r77, %r77;
	mad.lo.s32 	%r80, %r78, %r78, %r79;
	setp.lt.s32 	%p104, %r80, %r117;
	min.s32 	%r117, %r80, %r117;
	selp.b32 	%r119, %r76, %r119, %p104;
	selp.b32 	%r120, %r8, %r120, %p104;
$L__BB0_40:
	add.s64 	%rd159, %rd18, %rd22;
	cvt.s64.s32 	%rd160, %rd159;
	shr.s64 	%rd161, %rd160, 63;
	and.b64 	%rd162, %rd161, 24;
	add.s64 	%rd163, %rd162, %rd160;
	shl.b64 	%rd25, %rd163, 1;
	add.s64 	%rd164, %rd25, %rd23;
	shl.b64 	%rd165, %rd164, 2;
	mov.b64 	%rd166, _cudapy_smem_3;
	add.s64 	%rd167, %rd166, %rd165;
	ld.shared.b32 	%r9, [%rd167];
	ld.shared.b32 	%r81, [%rd167+4];
	setp.eq.b32 	%p105, %r9, -1;
	setp.eq.b32 	%p106, %r81, -1;
	or.pred 	%p107, %p105, %p106;
	@%p107 bra 	$L__BB0_42;
	sub.s32 	%r82, %r4, %r9;
	sub.s32 	%r83, %r6, %r81;
	mul.lo.s32 	%r84, %r82, %r82;
	mad.lo.s32 	%r85, %r83, %r83, %r84;
	setp.lt.s32 	%p108, %r85, %r117;
	min.s32 	%r117, %r85, %r117;
	selp.b32 	%r119, %r81, %r119, %p108;
	selp.b32 	%r120, %r9, %r120, %p108;
$L__BB0_42:
	add.s64 	%rd168, %rd24, %rd20;
	shl.b64 	%rd169, %rd168, 2;
	mov.b64 	%rd170, _cudapy_smem_3;
	add.s64 	%rd171, %rd170, %rd169;
	ld.shared.b32 	%r10, [%rd171];
	ld.shared.b32 	%r86, [%rd171+4];
	setp.eq.b32 	%p109, %r10, -1;
	setp.eq.b32 	%p110, %r86, -1;
	or.pred 	%p111, %p109, %p110;
	@%p111 bra 	$L__BB0_44;
	sub.s32 	%r87, %r4, %r10;
	sub.s32 	%r88, %r6, %r86;
	mul.lo.s32 	%r89, %r87, %r87;
	mad.lo.s32 	%r90, %r88, %r88, %r89;
	setp.lt.s32 	%p112, %r90, %r117;
	min.s32 	%r117, %r90, %r117;
	selp.b32 	%r119, %r86, %r119, %p112;
	selp.b32 	%r120, %r10, %r120, %p112;
$L__BB0_44:
	add.s64 	%rd172, %rd25, %rd20;
	shl.b64 	%rd173, %rd172, 2;
	mov.b64 	%rd174, _cudapy_smem_3;
	add.s64 	%rd175, %rd174, %rd173;
	ld.shared.b32 	%r11, [%rd175];
	ld.shared.b32 	%r91, [%rd175+4];
	setp.eq.b32 	%p113, %r11, -1;
	setp.eq.b32 	%p114, %r91, -1;
	or.pred 	%p115, %p113, %p114;
	@%p115 bra 	$L__BB0_46;
	sub.s32 	%r92, %r4, %r11;
	sub.s32 	%r93, %r6, %r91;
	mul.lo.s32 	%r94, %r92, %r92;
	mad.lo.s32 	%r95, %r93, %r93, %r94;
	setp.lt.s32 	%p116, %r95, %r117;
	min.s32 	%r117, %r95, %r117;
	selp.b32 	%r119, %r91, %r119, %p116;
	selp.b32 	%r120, %r11, %r120, %p116;
$L__BB0_46:
	add.s64 	%rd176, %rd19, %rd22;
	cvt.s64.s32 	%rd177, %rd176;
	shr.s64 	%rd178, %rd177, 63;
	and.b64 	%rd179, %rd178, 24;
	add.s64 	%rd180, %rd179, %rd177;
	mul.lo.s64 	%rd26, %rd180, 48;
	add.s64 	%rd181, %rd24, %rd26;
	shl.b64 	%rd182, %rd181, 2;
	mov.b64 	%rd183, _cudapy_smem_3;
	add.s64 	%rd184, %rd183, %rd182;
	ld.shared.b32 	%r12, [%rd184];
	ld.shared.b32 	%r96, [%rd184+4];
	setp.eq.b32 	%p117, %r12, -1;
	setp.eq.b32 	%p118, %r96, -1;
	or.pred 	%p119, %p117, %p118;
	@%p119 bra 	$L__BB0_48;
	sub.s32 	%r97, %r4, %r12;
	sub.s32 	%r98, %r6, %r96;
	mul.lo.s32 	%r99, %r97, %r97;
	mad.lo.s32 	%r100, %r98, %r98, %r99;
	setp.lt.s32 	%p120, %r100, %r117;
	min.s32 	%r117, %r100, %r117;
	selp.b32 	%r119, %r96, %r119, %p120;
	selp.b32 	%r120, %r12, %r120, %p120;
$L__BB0_48:
	add.s64 	%rd185, %rd21, %rd26;
	shl.b64 	%rd186, %rd185, 2;
	mov.b64 	%rd187, _cudapy_smem_3;
	add.s64 	%rd188, %rd187, %rd186;
	ld.shared.b32 	%r13, [%rd188];
	ld.shared.b32 	%r101, [%rd188+4];
	setp.eq.b32 	%p121, %r13, -1;
	setp.eq.b32 	%p122, %r101, -1;
	or.pred 	%p123, %p121, %p122;
	@%p123 bra 	$L__BB0_50;
	sub.s32 	%r102, %r4, %r13;
	sub.s32 	%r103, %r6, %r101;
	mul.lo.s32 	%r104, %r102, %r102;
	mad.lo.s32 	%r105, %r103, %r103, %r104;
	setp.lt.s32 	%p124, %r105, %r117;
	min.s32 	%r117, %r105, %r117;
	selp.b32 	%r119, %r101, %r119, %p124;
	selp.b32 	%r120, %r13, %r120, %p124;
$L__BB0_50:
	add.s64 	%rd189, %rd25, %rd26;
	shl.b64 	%rd190, %rd189, 2;
	mov.b64 	%rd191, _cudapy_smem_3;
	add.s64 	%rd192, %rd191, %rd190;
	ld.shared.b32 	%r14, [%rd192];
	ld.shared.b32 	%r106, [%rd192+4];
	setp.eq.b32 	%p125, %r14, -1;
	setp.eq.b32 	%p126, %r106, -1;
	or.pred 	%p127, %p125, %p126;
	@%p127 bra 	$L__BB0_75;
	sub.s32 	%r107, %r4, %r14;
	sub.s32 	%r108, %r6, %r106;
	mul.lo.s32 	%r109, %r107, %r107;
	mad.lo.s32 	%r110, %r108, %r108, %r109;
	setp.lt.s32 	%p128, %r110, %r117;
	selp.b32 	%r119, %r106, %r119, %p128;
	selp.b32 	%r120, %r14, %r120, %p128;
	bra.uni 	$L__BB0_75;
$L__BB0_52:
	cvt.s64.s32 	%rd27, %r4;
	setp.le.s64 	%p7, %rd35, %rd27;
	cvt.u64.u32 	%rd28, %r6;
	setp.le.u64 	%p8, %rd36, %rd28;
	or.pred 	%p9, %p7, %p8;
	@%p9 bra 	$L__BB0_33;
	setp.lt.s32 	%p10, %r4, 0;
	selp.b64 	%rd42, %rd36, 0, %p10;
	add.s64 	%rd43, %rd42, %rd27;
	mul.lo.s64 	%rd44, %rd37, %rd28;
	mad.lo.s64 	%rd45, %rd38, %rd43, %rd44;
	add.s64 	%rd46, %rd45, %rd34;
	ld.b32 	%r120, [%rd46];
	add.s64 	%rd47, %rd46, %rd39;
	ld.b32 	%r119, [%rd47];
	setp.eq.b32 	%p11, %r120, -1;
	setp.eq.b32 	%p12, %r119, -1;
	or.pred 	%p13, %p11, %p12;
	mov.b32 	%r118, 2147483647;
	@%p13 bra 	$L__BB0_55;
	sub.s32 	%r25, %r4, %r120;
	sub.s32 	%r26, %r6, %r119;
	mul.lo.s32 	%r27, %r25, %r25;
	mad.lo.s32 	%r118, %r26, %r26, %r27;
$L__BB0_55:
	sub.s32 	%r28, %r4, %r21;
	setp.gt.s32 	%p14, %r28, -1;
	setp.lt.s32 	%p15, %r28, %r22;
	and.pred 	%p3, %p14, %p15;
	cvt.u64.u32 	%rd48, %r28;
	mul.lo.s64 	%rd29, %rd38, %rd48;
	setp.gt.s32 	%p16, %r4, -1;
	setp.lt.s32 	%p17, %r4, %r22;
	and.pred 	%p4, %p16, %p17;
	cvt.u64.u32 	%rd49, %r4;
	mul.lo.s64 	%rd30, %rd38, %rd49;
	add.s32 	%r29, %r21, %r4;
	setp.gt.s32 	%p18, %r29, -1;
	setp.lt.s32 	%p19, %r29, %r22;
	and.pred 	%p5, %p18, %p19;
	cvt.u64.u32 	%rd50, %r29;
	mul.lo.s64 	%rd31, %rd38, %rd50;
	mov.b64 	%rd32, 0;
	not.pred 	%p33, %p4;
$L__BB0_56:
	mov.b32 	%r121, -1;
	mov.pred 	%p130, 0;
	setp.eq.b64 	%p20, %rd32, 2;
	@%p20 bra 	$L__BB0_77;
	setp.eq.b64 	%p21, %rd32, 1;
	@%p21 bra 	$L__BB0_76;
$L__BB0_58:
	add.s64 	%rd32, %rd32, 1;
	mad.lo.s32 	%r17, %r121, %r21, %r6;
	cvt.u64.u32 	%rd51, %r17;
	mul.lo.s64 	%rd33, %rd37, %rd51;
	@%p130 bra 	$L__BB0_59;
	bra.uni 	$L__BB0_65;
$L__BB0_59:
	setp.lt.s32 	%p49, %r17, %r22;
	setp.gt.s32 	%p50, %r17, -1;
	and.pred 	%p51, %p3, %p50;
	and.pred 	%p52, %p51, %p49;
	@%p52 bra 	$L__BB0_60;
	bra.uni 	$L__BB0_62;
$L__BB0_60:
	add.s64 	%rd61, %rd29, %rd33;
	add.s64 	%rd62, %rd61, %rd34;
	ld.b32 	%r15, [%rd62];
	add.s64 	%rd63, %rd62, %rd39;
	ld.b32 	%r45, [%rd63];
	setp.eq.b32 	%p53, %r15, -1;
	setp.eq.b32 	%p54, %r45, -1;
	or.pred 	%p55, %p53, %p54;
	@%p55 bra 	$L__BB0_62;
	sub.s32 	%r46, %r4, %r15;
	sub.s32 	%r47, %r6, %r45;
	mul.lo.s32 	%r48, %r46, %r46;
	mad.lo.s32 	%r49, %r47, %r47, %r48;
	setp.lt.s32 	%p56, %r49, %r118;
	min.s32 	%r118, %r49, %r118;
	selp.b32 	%r119, %r45, %r119, %p56;
	selp.b32 	%r120, %r15, %r120, %p56;
$L__BB0_62:
	setp.ge.s32 	%p57, %r17, %r22;
	setp.lt.s32 	%p58, %r17, 0;
	not.pred 	%p59, %p5;
	or.pred 	%p60, %p59, %p58;
	or.pred 	%p61, %p60, %p57;
	@%p61 bra 	$L__BB0_74;
	add.s64 	%rd64, %rd31, %rd33;
	add.s64 	%rd65, %rd64, %rd34;
	ld.b32 	%r16, [%rd65];
	add.s64 	%rd66, %rd65, %rd39;
	ld.b32 	%r50, [%rd66];
	setp.eq.b32 	%p62, %r16, -1;
	setp.eq.b32 	%p63, %r50, -1;
	or.pred 	%p64, %p62, %p63;
	@%p64 bra 	$L__BB0_74;
	sub.s32 	%r51, %r4, %r16;
	sub.s32 	%r52, %r6, %r50;
	mul.lo.s32 	%r53, %r51, %r51;
	mad.lo.s32 	%r54, %r52, %r52, %r53;
	setp.lt.s32 	%p65, %r54, %r118;
	min.s32 	%r118, %r54, %r118;
	selp.b32 	%r119, %r50, %r119, %p65;
	selp.b32 	%r120, %r16, %r120, %p65;
	bra.uni 	$L__BB0_74;
$L__BB0_65:
	setp.ge.s32 	%p22, %r17, %r22;
	setp.lt.s32 	%p23, %r17, 0;
	not.pred 	%p24, %p3;
	or.pred 	%p25, %p24, %p23;
	or.pred 	%p26, %p25, %p22;
	@%p26 bra 	$L__BB0_68;
	add.s64 	%rd52, %rd29, %rd33;
	add.s64 	%rd53, %rd52, %rd34;
	ld.b32 	%r18, [%rd53];
	add.s64 	%rd54, %rd53, %rd39;
	ld.b32 	%r30, [%rd54];
	setp.eq.b32 	%p27, %r18, -1;
	setp.eq.b32 	%p28, %r30, -1;
	or.pred 	%p29, %p27, %p28;
	@%p29 bra 	$L__BB0_68;
	sub.s32 	%r31, %r4, %r18;
	sub.s32 	%r32, %r6, %r30;
	mul.lo.s32 	%r33, %r31, %r31;
	mad.lo.s32 	%r34, %r32, %r32, %r33;
	setp.lt.s32 	%p30, %r34, %r118;
	min.s32 	%r118, %r34, %r118;
	selp.b32 	%r119, %r30, %r119, %p30;
	selp.b32 	%r120, %r18, %r120, %p30;
$L__BB0_68:
	setp.ge.s32 	%p31, %r17, %r22;
	setp.lt.s32 	%p32, %r17, 0;
	or.pred 	%p34, %p33, %p32;
	or.pred 	%p35, %p34, %p31;
	@%p35 bra 	$L__BB0_71;
	add.s64 	%rd55, %rd30, %rd33;
	add.s64 	%rd56, %rd55, %rd34;
	ld.b32 	%r19, [%rd56];
	add.s64 	%rd57, %rd56, %rd39;
	ld.b32 	%r35, [%rd57];
	setp.eq.b32 	%p36, %r19, -1;
	setp.eq.b32 	%p37, %r35, -1;
	or.pred 	%p38, %p36, %p37;
	@%p38 bra 	$L__BB0_71;
	sub.s32 	%r36, %r4, %r19;
	sub.s32 	%r37, %r6, %r35;
	mul.lo.s32 	%r38, %r36, %r36;
	mad.lo.s32 	%r39, %r37, %r37, %r38;
	setp.lt.s32 	%p39, %r39, %r118;
	min.s32 	%r118, %r39, %r118;
	selp.b32 	%r119, %r35, %r119, %p39;
	selp.b32 	%r120, %r19, %r120, %p39;
$L__BB0_71:
	setp.ge.s32 	%p40, %r17, %r22;
	setp.lt.s32 	%p41, %r17, 0;
	not.pred 	%p42, %p5;
	or.pred 	%p43, %p42, %p41;
	or.pred 	%p44, %p43, %p40;
	@%p44 bra 	$L__BB0_74;
	add.s64 	%rd58, %rd31, %rd33;
	add.s64 	%rd59, %rd58, %rd34;
	ld.b32 	%r20, [%rd59];
	add.s64 	%rd60, %rd59, %rd39;
	ld.b32 	%r40, [%rd60];
	setp.eq.b32 	%p45, %r20, -1;
	setp.eq.b32 	%p46, %r40, -1;
	or.pred 	%p47, %p45, %p46;
	@%p47 bra 	$L__BB0_74;
	sub.s32 	%r41, %r4, %r20;
	sub.s32 	%r42, %r6, %r40;
	mul.lo.s32 	%r43, %r41, %r41;
	mad.lo.s32 	%r44, %r42, %r42, %r43;
	setp.lt.s32 	%p48, %r44, %r118;
	min.s32 	%r118, %r44, %r118;
	selp.b32 	%r119, %r40, %r119, %p48;
	selp.b32 	%r120, %r20, %r120, %p48;
$L__BB0_74:
	setp.eq.b64 	%p66, %rd32, 3;
	@%p66 bra 	$L__BB0_75;
	bra.uni 	$L__BB0_56;
$L__BB0_75:
	ld.param.b64 	%rd203, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_20];
	ld.param.b64 	%rd202, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_17];
	ld.param.b64 	%rd201, [_ZN6task6b47_jfa_pass_shared_memory_square_euclidean_kernelB3v80B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi3E1A7mutable7alignedE5ArrayIiLi3E1A7mutable7alignedEii_param_15];
	cvt.u64.u32 	%rd193, %r6;
	cvt.s64.s32 	%rd194, %r4;
	setp.lt.s32 	%p129, %r4, 0;
	selp.b64 	%rd195, %rd202, 0, %p129;
	add.s64 	%rd196, %rd195, %rd194;
	mul.lo.s64 	%rd197, %rd40, %rd193;
	mad.lo.s64 	%rd198, %rd203, %rd196, %rd197;
	add.s64 	%rd199, %rd198, %rd201;
	st.b32 	[%rd199], %r120;
	add.s64 	%rd200, %rd199, %rd41;
	st.b32 	[%rd200], %r119;
	bra.uni 	$L__BB0_33;
$L__BB0_76:
	mov.b32 	%r121, 0;
	mov.pred 	%p130, -1;
	bra.uni 	$L__BB0_58;
$L__BB0_77:
	mov.b32 	%r121, 1;
	bra.uni 	$L__BB0_58;

}