//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;

.visible .entry _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 .ptr .align 1 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 .ptr .align 1 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 .ptr .align 1 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 .ptr .align 1 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 .ptr .align 1 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 .ptr .align 1 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<39>;
	.reg .b32 	%r<153>;
	.reg .b64 	%rd<77>;

	ld.param.b64 	%rd5, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.b64 	%rd6, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.b64 	%rd7, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6];
	ld.param.b64 	%rd8, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.b64 	%rd9, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.b64 	%rd10, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.b64 	%rd13, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.b64 	%rd14, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	ld.param.b64 	%rd11, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.b64 	%rd12, [_ZN5task435_voroni_euclidean_hypot_fast_kernelB3v44B124cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BIAwMVGiC26CFSrQ6SUq8FGgS01haUPIHRg5ZSkIQhiRJJADWhwSSQPG4LsQJku7qVAkReHSgH5BjXagIAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	cvta.to.global.u64 	%rd1, %rd5;
	mov.u32 	%r3, %tid.x;
	cvt.u64.u32 	%rd15, %r3;
	mov.u32 	%r4, %ntid.x;
	mov.u32 	%r5, %ctaid.x;
	mul.wide.u32 	%rd16, %r4, %r5;
	add.s64 	%rd2, %rd16, %rd15;
	mov.u32 	%r6, %tid.y;
	mov.u32 	%r7, %ntid.y;
	mov.u32 	%r8, %ctaid.y;
	mad.lo.s32 	%r9, %r7, %r8, %r6;
	cvt.u64.u32 	%rd3, %r9;
	cvt.rn.f32.u64 	%r10, %rd2;
	cvt.rn.f32.u64 	%r11, %rd13;
	div.approx.ftz.f32 	%r1, %r10, %r11;
	cvt.rn.f32.u32 	%r12, %r9;
	cvt.rn.f32.s64 	%r13, %rd14;
	div.approx.ftz.f32 	%r2, %r12, %r13;
	setp.lt.u64 	%p1, %rd2, %rd13;
	setp.gt.s64 	%p2, %rd14, %rd3;
	and.pred 	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_9;
$L__BB0_1:
	ret;
$L__BB0_2:
	.pragma "nounroll";
	mul.lo.s64 	%rd21, %rd76, %rd8;
	add.s64 	%rd22, %rd1, %rd21;
	add.s64 	%rd23, %rd5, %rd21;
	ld.global.b32 	%r14, [%rd22];
	add.s64 	%rd24, %rd9, %rd23;
	ld.b32 	%r15, [%rd24];
	sub.ftz.f32 	%r16, %r1, %r14;
	sub.ftz.f32 	%r17, %r2, %r15;
	abs.ftz.f32 	%r18, %r16;
	abs.ftz.f32 	%r19, %r17;
	min.s32 	%r20, %r19, %r18;
	max.s32 	%r21, %r18, %r19;
	and.b32 	%r22, %r21, -33554432;
	xor.b32 	%r23, %r22, 2122317824;
	mul.ftz.f32 	%r24, %r20, %r23;
	mul.ftz.f32 	%r25, %r21, %r23;
	mul.ftz.f32 	%r26, %r24, %r24;
	fma.rn.ftz.f32 	%r27, %r25, %r25, %r26;
	sqrt.approx.ftz.f32 	%r28, %r27;
	or.b32 	%r29, %r22, 8388608;
	mul.ftz.f32 	%r30, %r28, %r29;
	setp.eq.ftz.f32 	%p8, %r20, 0f00000000;
	selp.f32 	%r31, %r21, %r30, %p8;
	setp.eq.ftz.f32 	%p9, %r20, 0f7F800000;
	selp.f32 	%r32, 0f7F800000, %r31, %p9;
	setp.lt.ftz.f32 	%p10, %r32, %r151;
	selp.b64 	%rd25, %rd76, %rd75, %p10;
	selp.f32 	%r33, %r32, %r151, %p10;
	setp.gt.s64 	%p11, %rd73, 0;
	selp.b64 	%rd26, 1, 0, %p11;
	add.s64 	%rd27, %rd74, %rd26;
	selp.b64 	%rd28, -1, 0, %p11;
	add.s64 	%rd29, %rd73, %rd28;
	mul.lo.s64 	%rd30, %rd74, %rd8;
	add.s64 	%rd31, %rd1, %rd30;
	add.s64 	%rd32, %rd5, %rd30;
	ld.global.b32 	%r34, [%rd31];
	add.s64 	%rd33, %rd9, %rd32;
	ld.b32 	%r35, [%rd33];
	sub.ftz.f32 	%r36, %r1, %r34;
	sub.ftz.f32 	%r37, %r2, %r35;
	abs.ftz.f32 	%r38, %r36;
	abs.ftz.f32 	%r39, %r37;
	min.s32 	%r40, %r39, %r38;
	max.s32 	%r41, %r38, %r39;
	and.b32 	%r42, %r41, -33554432;
	xor.b32 	%r43, %r42, 2122317824;
	mul.ftz.f32 	%r44, %r40, %r43;
	mul.ftz.f32 	%r45, %r41, %r43;
	mul.ftz.f32 	%r46, %r44, %r44;
	fma.rn.ftz.f32 	%r47, %r45, %r45, %r46;
	sqrt.approx.ftz.f32 	%r48, %r47;
	or.b32 	%r49, %r42, 8388608;
	mul.ftz.f32 	%r50, %r48, %r49;
	setp.eq.ftz.f32 	%p12, %r40, 0f00000000;
	selp.f32 	%r51, %r41, %r50, %p12;
	setp.eq.ftz.f32 	%p13, %r40, 0f7F800000;
	selp.f32 	%r52, 0f7F800000, %r51, %p13;
	setp.lt.ftz.f32 	%p14, %r52, %r33;
	selp.b64 	%rd34, %rd74, %rd25, %p14;
	selp.f32 	%r53, %r52, %r33, %p14;
	setp.gt.s64 	%p15, %rd29, 0;
	selp.b64 	%rd35, 1, 0, %p15;
	add.s64 	%rd36, %rd27, %rd35;
	selp.b64 	%rd37, -1, 0, %p15;
	add.s64 	%rd38, %rd29, %rd37;
	mul.lo.s64 	%rd39, %rd27, %rd8;
	add.s64 	%rd40, %rd1, %rd39;
	add.s64 	%rd41, %rd5, %rd39;
	ld.global.b32 	%r54, [%rd40];
	add.s64 	%rd42, %rd9, %rd41;
	ld.b32 	%r55, [%rd42];
	sub.ftz.f32 	%r56, %r1, %r54;
	sub.ftz.f32 	%r57, %r2, %r55;
	abs.ftz.f32 	%r58, %r56;
	abs.ftz.f32 	%r59, %r57;
	min.s32 	%r60, %r59, %r58;
	max.s32 	%r61, %r58, %r59;
	and.b32 	%r62, %r61, -33554432;
	xor.b32 	%r63, %r62, 2122317824;
	mul.ftz.f32 	%r64, %r60, %r63;
	mul.ftz.f32 	%r65, %r61, %r63;
	mul.ftz.f32 	%r66, %r64, %r64;
	fma.rn.ftz.f32 	%r67, %r65, %r65, %r66;
	sqrt.approx.ftz.f32 	%r68, %r67;
	or.b32 	%r69, %r62, 8388608;
	mul.ftz.f32 	%r70, %r68, %r69;
	setp.eq.ftz.f32 	%p16, %r60, 0f00000000;
	selp.f32 	%r71, %r61, %r70, %p16;
	setp.eq.ftz.f32 	%p17, %r60, 0f7F800000;
	selp.f32 	%r72, 0f7F800000, %r71, %p17;
	setp.lt.ftz.f32 	%p18, %r72, %r53;
	selp.b64 	%rd43, %rd27, %rd34, %p18;
	selp.f32 	%r73, %r72, %r53, %p18;
	setp.gt.s64 	%p19, %rd38, 0;
	selp.b64 	%rd44, 1, 0, %p19;
	add.s64 	%rd76, %rd36, %rd44;
	selp.b64 	%rd45, -1, 0, %p19;
	add.s64 	%rd46, %rd38, %rd45;
	mul.lo.s64 	%rd47, %rd36, %rd8;
	add.s64 	%rd48, %rd1, %rd47;
	add.s64 	%rd49, %rd5, %rd47;
	ld.global.b32 	%r74, [%rd48];
	add.s64 	%rd50, %rd9, %rd49;
	ld.b32 	%r75, [%rd50];
	sub.ftz.f32 	%r76, %r1, %r74;
	sub.ftz.f32 	%r77, %r2, %r75;
	abs.ftz.f32 	%r78, %r76;
	abs.ftz.f32 	%r79, %r77;
	min.s32 	%r80, %r79, %r78;
	max.s32 	%r81, %r78, %r79;
	and.b32 	%r82, %r81, -33554432;
	xor.b32 	%r83, %r82, 2122317824;
	mul.ftz.f32 	%r84, %r80, %r83;
	mul.ftz.f32 	%r85, %r81, %r83;
	mul.ftz.f32 	%r86, %r84, %r84;
	fma.rn.ftz.f32 	%r87, %r85, %r85, %r86;
	sqrt.approx.ftz.f32 	%r88, %r87;
	or.b32 	%r89, %r82, 8388608;
	mul.ftz.f32 	%r90, %r88, %r89;
	setp.eq.ftz.f32 	%p20, %r80, 0f00000000;
	selp.f32 	%r91, %r81, %r90, %p20;
	setp.eq.ftz.f32 	%p21, %r80, 0f7F800000;
	selp.f32 	%r92, 0f7F800000, %r91, %p21;
	setp.lt.ftz.f32 	%p22, %r92, %r73;
	selp.b64 	%rd75, %rd36, %rd43, %p22;
	selp.f32 	%r151, %r92, %r73, %p22;
	setp.gt.s64 	%p23, %rd46, 0;
	selp.b64 	%rd51, 1, 0, %p23;
	add.s64 	%rd74, %rd76, %rd51;
	selp.b64 	%rd52, -1, 0, %p23;
	add.s64 	%rd73, %rd46, %rd52;
	add.s64 	%rd72, %rd72, -4;
	setp.ne.b64 	%p24, %rd72, 0;
	@%p24 bra 	$L__BB0_2;
	and.b64 	%rd53, %rd4, 3;
	setp.eq.b64 	%p25, %rd53, 0;
	@%p25 bra 	$L__BB0_7;
$L__BB0_4:
	and.b64 	%rd54, %rd4, 3;
	setp.eq.b64 	%p26, %rd54, 1;
	@%p26 bra 	$L__BB0_6;
	mul.lo.s64 	%rd55, %rd76, %rd8;
	add.s64 	%rd56, %rd1, %rd55;
	add.s64 	%rd57, %rd5, %rd55;
	ld.global.b32 	%r93, [%rd56];
	add.s64 	%rd58, %rd9, %rd57;
	ld.b32 	%r94, [%rd58];
	sub.ftz.f32 	%r95, %r1, %r93;
	sub.ftz.f32 	%r96, %r2, %r94;
	abs.ftz.f32 	%r97, %r95;
	abs.ftz.f32 	%r98, %r96;
	min.s32 	%r99, %r98, %r97;
	max.s32 	%r100, %r97, %r98;
	and.b32 	%r101, %r100, -33554432;
	xor.b32 	%r102, %r101, 2122317824;
	mul.ftz.f32 	%r103, %r99, %r102;
	mul.ftz.f32 	%r104, %r100, %r102;
	mul.ftz.f32 	%r105, %r103, %r103;
	fma.rn.ftz.f32 	%r106, %r104, %r104, %r105;
	sqrt.approx.ftz.f32 	%r107, %r106;
	or.b32 	%r108, %r101, 8388608;
	mul.ftz.f32 	%r109, %r107, %r108;
	setp.eq.ftz.f32 	%p27, %r99, 0f00000000;
	selp.f32 	%r110, %r100, %r109, %p27;
	setp.eq.ftz.f32 	%p28, %r99, 0f7F800000;
	selp.f32 	%r111, 0f7F800000, %r110, %p28;
	setp.lt.ftz.f32 	%p29, %r111, %r151;
	selp.b64 	%rd59, %rd76, %rd75, %p29;
	selp.f32 	%r112, %r111, %r151, %p29;
	setp.gt.s64 	%p30, %rd73, 0;
	selp.b64 	%rd60, 1, 0, %p30;
	add.s64 	%rd76, %rd74, %rd60;
	mul.lo.s64 	%rd61, %rd74, %rd8;
	add.s64 	%rd62, %rd1, %rd61;
	add.s64 	%rd63, %rd5, %rd61;
	ld.global.b32 	%r113, [%rd62];
	add.s64 	%rd64, %rd9, %rd63;
	ld.b32 	%r114, [%rd64];
	sub.ftz.f32 	%r115, %r1, %r113;
	sub.ftz.f32 	%r116, %r2, %r114;
	abs.ftz.f32 	%r117, %r115;
	abs.ftz.f32 	%r118, %r116;
	min.s32 	%r119, %r118, %r117;
	max.s32 	%r120, %r117, %r118;
	and.b32 	%r121, %r120, -33554432;
	xor.b32 	%r122, %r121, 2122317824;
	mul.ftz.f32 	%r123, %r119, %r122;
	mul.ftz.f32 	%r124, %r120, %r122;
	mul.ftz.f32 	%r125, %r123, %r123;
	fma.rn.ftz.f32 	%r126, %r124, %r124, %r125;
	sqrt.approx.ftz.f32 	%r127, %r126;
	or.b32 	%r128, %r121, 8388608;
	mul.ftz.f32 	%r129, %r127, %r128;
	setp.eq.ftz.f32 	%p31, %r119, 0f00000000;
	selp.f32 	%r130, %r120, %r129, %p31;
	setp.eq.ftz.f32 	%p32, %r119, 0f7F800000;
	selp.f32 	%r131, 0f7F800000, %r130, %p32;
	setp.lt.ftz.f32 	%p33, %r131, %r112;
	selp.b64 	%rd75, %rd74, %rd59, %p33;
	selp.f32 	%r151, %r131, %r112, %p33;
	and.b64 	%rd65, %rd4, 1;
	setp.ne.b64 	%p34, %rd65, 0;
	not.pred 	%p35, %p34;
	@%p35 bra 	$L__BB0_7;
$L__BB0_6:
	mul.lo.s64 	%rd66, %rd76, %rd8;
	add.s64 	%rd67, %rd1, %rd66;
	add.s64 	%rd68, %rd5, %rd66;
	ld.global.b32 	%r132, [%rd67];
	add.s64 	%rd69, %rd9, %rd68;
	ld.b32 	%r133, [%rd69];
	sub.ftz.f32 	%r134, %r1, %r132;
	sub.ftz.f32 	%r135, %r2, %r133;
	abs.ftz.f32 	%r136, %r134;
	abs.ftz.f32 	%r137, %r135;
	min.s32 	%r138, %r137, %r136;
	max.s32 	%r139, %r136, %r137;
	and.b32 	%r140, %r139, -33554432;
	xor.b32 	%r141, %r140, 2122317824;
	mul.ftz.f32 	%r142, %r138, %r141;
	mul.ftz.f32 	%r143, %r139, %r141;
	mul.ftz.f32 	%r144, %r142, %r142;
	fma.rn.ftz.f32 	%r145, %r143, %r143, %r144;
	sqrt.approx.ftz.f32 	%r146, %r145;
	or.b32 	%r147, %r140, 8388608;
	mul.ftz.f32 	%r148, %r146, %r147;
	setp.eq.ftz.f32 	%p36, %r138, 0f00000000;
	selp.f32 	%r149, %r139, %r148, %p36;
	setp.eq.ftz.f32 	%p37, %r138, 0f7F800000;
	selp.f32 	%r150, 0f7F800000, %r149, %p37;
	setp.lt.ftz.f32 	%p38, %r150, %r151;
	selp.b64 	%rd75, %rd76, %rd75, %p38;
$L__BB0_7:
	cvt.u32.u64 	%r152, %rd75;
$L__BB0_8:
	mad.lo.s64 	%rd70, %rd11, %rd2, %rd10;
	mad.lo.s64 	%rd71, %rd12, %rd3, %rd70;
	st.b32 	[%rd71], %r152;
	bra.uni 	$L__BB0_1;
$L__BB0_9:
	max.s64 	%rd17, %rd6, 0;
	setp.lt.s64 	%p4, %rd6, 1;
	setp.gt.s64 	%p5, %rd6, 0;
	selp.b64 	%rd18, -1, 0, %p5;
	add.s64 	%rd73, %rd17, %rd18;
	mov.b32 	%r152, 0;
	@%p4 bra 	$L__BB0_8;
	setp.ne.b64 	%p6, %rd7, 2;
	@%p6 bra 	$L__BB0_1;
	min.s64 	%rd19, %rd73, 0;
	sub.s64 	%rd20, %rd73, %rd19;
	add.s64 	%rd4, %rd20, 1;
	setp.lt.u64 	%p7, %rd20, 3;
	mov.b32 	%r151, 0f7F800000;
	mov.b64 	%rd75, 0;
	mov.b64 	%rd74, 1;
	mov.b64 	%rd76, %rd75;
	@%p7 bra 	$L__BB0_4;
	and.b64 	%rd72, %rd4, -4;
	mov.b32 	%r151, 0f7F800000;
	mov.b64 	%rd75, 0;
	mov.b64 	%rd74, 1;
	bra.uni 	$L__BB0_2;

}