//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;

.visible .entry _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 .ptr .align 1 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 .ptr .align 1 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 .ptr .align 1 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 .ptr .align 1 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 .ptr .align 1 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 .ptr .align 1 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<25>;
	.reg .b32 	%r<69>;
	.reg .b64 	%rd<77>;

	ld.param.b64 	%rd5, [_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.b64 	%rd6, [_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.b64 	%rd7, [_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6];
	ld.param.b64 	%rd8, [_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.b64 	%rd9, [_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.b64 	%rd10, [_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.b64 	%rd13, [_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.b64 	%rd14, [_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	ld.param.b64 	%rd11, [_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.b64 	%rd12, [_ZN5task429_voroni_euclidean_sqrt_kernelB3v32B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	cvta.to.global.u64 	%rd1, %rd5;
	mov.u32 	%r3, %tid.x;
	cvt.u64.u32 	%rd15, %r3;
	mov.u32 	%r4, %ntid.x;
	mov.u32 	%r5, %ctaid.x;
	mul.wide.u32 	%rd16, %r4, %r5;
	add.s64 	%rd2, %rd16, %rd15;
	mov.u32 	%r6, %tid.y;
	mov.u32 	%r7, %ntid.y;
	mov.u32 	%r8, %ctaid.y;
	mad.lo.s32 	%r9, %r7, %r8, %r6;
	cvt.u64.u32 	%rd3, %r9;
	cvt.rn.f32.u64 	%r10, %rd2;
	cvt.rn.f32.u64 	%r11, %rd13;
	div.rn.f32 	%r1, %r10, %r11;
	cvt.rn.f32.u32 	%r12, %r9;
	cvt.rn.f32.s64 	%r13, %rd14;
	div.rn.f32 	%r2, %r12, %r13;
	setp.lt.u64 	%p1, %rd2, %rd13;
	setp.gt.s64 	%p2, %rd14, %rd3;
	and.pred 	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_9;
$L__BB0_1:
	ret;
$L__BB0_2:
	.pragma "nounroll";
	mul.lo.s64 	%rd21, %rd76, %rd8;
	add.s64 	%rd22, %rd1, %rd21;
	add.s64 	%rd23, %rd5, %rd21;
	ld.global.b32 	%r14, [%rd22];
	add.s64 	%rd24, %rd9, %rd23;
	ld.b32 	%r15, [%rd24];
	sub.f32 	%r16, %r1, %r14;
	sub.f32 	%r17, %r2, %r15;
	mul.f32 	%r18, %r17, %r17;
	fma.rn.f32 	%r19, %r16, %r16, %r18;
	sqrt.rn.f32 	%r20, %r19;
	setp.lt.f32 	%p8, %r20, %r67;
	selp.b64 	%rd25, %rd76, %rd75, %p8;
	selp.f32 	%r21, %r20, %r67, %p8;
	setp.gt.s64 	%p9, %rd73, 0;
	selp.b64 	%rd26, 1, 0, %p9;
	add.s64 	%rd27, %rd74, %rd26;
	selp.b64 	%rd28, -1, 0, %p9;
	add.s64 	%rd29, %rd73, %rd28;
	mul.lo.s64 	%rd30, %rd74, %rd8;
	add.s64 	%rd31, %rd1, %rd30;
	add.s64 	%rd32, %rd5, %rd30;
	ld.global.b32 	%r22, [%rd31];
	add.s64 	%rd33, %rd9, %rd32;
	ld.b32 	%r23, [%rd33];
	sub.f32 	%r24, %r1, %r22;
	sub.f32 	%r25, %r2, %r23;
	mul.f32 	%r26, %r25, %r25;
	fma.rn.f32 	%r27, %r24, %r24, %r26;
	sqrt.rn.f32 	%r28, %r27;
	setp.lt.f32 	%p10, %r28, %r21;
	selp.b64 	%rd34, %rd74, %rd25, %p10;
	selp.f32 	%r29, %r28, %r21, %p10;
	setp.gt.s64 	%p11, %rd29, 0;
	selp.b64 	%rd35, 1, 0, %p11;
	add.s64 	%rd36, %rd27, %rd35;
	selp.b64 	%rd37, -1, 0, %p11;
	add.s64 	%rd38, %rd29, %rd37;
	mul.lo.s64 	%rd39, %rd27, %rd8;
	add.s64 	%rd40, %rd1, %rd39;
	add.s64 	%rd41, %rd5, %rd39;
	ld.global.b32 	%r30, [%rd40];
	add.s64 	%rd42, %rd9, %rd41;
	ld.b32 	%r31, [%rd42];
	sub.f32 	%r32, %r1, %r30;
	sub.f32 	%r33, %r2, %r31;
	mul.f32 	%r34, %r33, %r33;
	fma.rn.f32 	%r35, %r32, %r32, %r34;
	sqrt.rn.f32 	%r36, %r35;
	setp.lt.f32 	%p12, %r36, %r29;
	selp.b64 	%rd43, %rd27, %rd34, %p12;
	selp.f32 	%r37, %r36, %r29, %p12;
	setp.gt.s64 	%p13, %rd38, 0;
	selp.b64 	%rd44, 1, 0, %p13;
	add.s64 	%rd76, %rd36, %rd44;
	selp.b64 	%rd45, -1, 0, %p13;
	add.s64 	%rd46, %rd38, %rd45;
	mul.lo.s64 	%rd47, %rd36, %rd8;
	add.s64 	%rd48, %rd1, %rd47;
	add.s64 	%rd49, %rd5, %rd47;
	ld.global.b32 	%r38, [%rd48];
	add.s64 	%rd50, %rd9, %rd49;
	ld.b32 	%r39, [%rd50];
	sub.f32 	%r40, %r1, %r38;
	sub.f32 	%r41, %r2, %r39;
	mul.f32 	%r42, %r41, %r41;
	fma.rn.f32 	%r43, %r40, %r40, %r42;
	sqrt.rn.f32 	%r44, %r43;
	setp.lt.f32 	%p14, %r44, %r37;
	selp.b64 	%rd75, %rd36, %rd43, %p14;
	selp.f32 	%r67, %r44, %r37, %p14;
	setp.gt.s64 	%p15, %rd46, 0;
	selp.b64 	%rd51, 1, 0, %p15;
	add.s64 	%rd74, %rd76, %rd51;
	selp.b64 	%rd52, -1, 0, %p15;
	add.s64 	%rd73, %rd46, %rd52;
	add.s64 	%rd72, %rd72, -4;
	setp.ne.b64 	%p16, %rd72, 0;
	@%p16 bra 	$L__BB0_2;
	and.b64 	%rd53, %rd4, 3;
	setp.eq.b64 	%p17, %rd53, 0;
	@%p17 bra 	$L__BB0_7;
$L__BB0_4:
	and.b64 	%rd54, %rd4, 3;
	setp.eq.b64 	%p18, %rd54, 1;
	@%p18 bra 	$L__BB0_6;
	mul.lo.s64 	%rd55, %rd76, %rd8;
	add.s64 	%rd56, %rd1, %rd55;
	add.s64 	%rd57, %rd5, %rd55;
	ld.global.b32 	%r45, [%rd56];
	add.s64 	%rd58, %rd9, %rd57;
	ld.b32 	%r46, [%rd58];
	sub.f32 	%r47, %r1, %r45;
	sub.f32 	%r48, %r2, %r46;
	mul.f32 	%r49, %r48, %r48;
	fma.rn.f32 	%r50, %r47, %r47, %r49;
	sqrt.rn.f32 	%r51, %r50;
	setp.lt.f32 	%p19, %r51, %r67;
	selp.b64 	%rd59, %rd76, %rd75, %p19;
	selp.f32 	%r52, %r51, %r67, %p19;
	setp.gt.s64 	%p20, %rd73, 0;
	selp.b64 	%rd60, 1, 0, %p20;
	add.s64 	%rd76, %rd74, %rd60;
	mul.lo.s64 	%rd61, %rd74, %rd8;
	add.s64 	%rd62, %rd1, %rd61;
	add.s64 	%rd63, %rd5, %rd61;
	ld.global.b32 	%r53, [%rd62];
	add.s64 	%rd64, %rd9, %rd63;
	ld.b32 	%r54, [%rd64];
	sub.f32 	%r55, %r1, %r53;
	sub.f32 	%r56, %r2, %r54;
	mul.f32 	%r57, %r56, %r56;
	fma.rn.f32 	%r58, %r55, %r55, %r57;
	sqrt.rn.f32 	%r59, %r58;
	setp.lt.f32 	%p21, %r59, %r52;
	selp.b64 	%rd75, %rd74, %rd59, %p21;
	selp.f32 	%r67, %r59, %r52, %p21;
	and.b64 	%rd65, %rd4, 1;
	setp.ne.b64 	%p22, %rd65, 0;
	not.pred 	%p23, %p22;
	@%p23 bra 	$L__BB0_7;
$L__BB0_6:
	mul.lo.s64 	%rd66, %rd76, %rd8;
	add.s64 	%rd67, %rd1, %rd66;
	add.s64 	%rd68, %rd5, %rd66;
	ld.global.b32 	%r60, [%rd67];
	add.s64 	%rd69, %rd9, %rd68;
	ld.b32 	%r61, [%rd69];
	sub.f32 	%r62, %r1, %r60;
	sub.f32 	%r63, %r2, %r61;
	mul.f32 	%r64, %r63, %r63;
	fma.rn.f32 	%r65, %r62, %r62, %r64;
	sqrt.rn.f32 	%r66, %r65;
	setp.lt.f32 	%p24, %r66, %r67;
	selp.b64 	%rd75, %rd76, %rd75, %p24;
$L__BB0_7:
	cvt.u32.u64 	%r68, %rd75;
$L__BB0_8:
	mad.lo.s64 	%rd70, %rd11, %rd2, %rd10;
	mad.lo.s64 	%rd71, %rd12, %rd3, %rd70;
	st.b32 	[%rd71], %r68;
	bra.uni 	$L__BB0_1;
$L__BB0_9:
	max.s64 	%rd17, %rd6, 0;
	setp.lt.s64 	%p4, %rd6, 1;
	setp.gt.s64 	%p5, %rd6, 0;
	selp.b64 	%rd18, -1, 0, %p5;
	add.s64 	%rd73, %rd17, %rd18;
	mov.b32 	%r68, 0;
	@%p4 bra 	$L__BB0_8;
	setp.ne.b64 	%p6, %rd7, 2;
	@%p6 bra 	$L__BB0_1;
	min.s64 	%rd19, %rd73, 0;
	sub.s64 	%rd20, %rd73, %rd19;
	add.s64 	%rd4, %rd20, 1;
	setp.lt.u64 	%p7, %rd20, 3;
	mov.b32 	%r67, 0f7F800000;
	mov.b64 	%rd75, 0;
	mov.b64 	%rd74, 1;
	mov.b64 	%rd76, %rd75;
	@%p7 bra 	$L__BB0_4;
	and.b64 	%rd72, %rd4, -4;
	mov.b32 	%r67, 0f7F800000;
	mov.b64 	%rd75, 0;
	mov.b64 	%rd74, 1;
	bra.uni 	$L__BB0_2;

}