//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: UNKNOWN
// Cuda compilation tools, release 13.2, V13.2.51
// Based on NVVM 22.0.0
//

.version 9.2
.target sm_120
.address_size 64

	// .globl	_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii
.common .global .align 8 .u64 _ZN08NumbaEnv6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii;

.visible .entry _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii(
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_0,
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_1,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_2,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_3,
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_4,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_5,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_6,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_7,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_8,
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_9,
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_10,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_11,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_12,
	.param .u64 .ptr .align 1 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_13,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_14,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_15,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_16,
	.param .u64 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_17,
	.param .u32 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_18,
	.param .u32 _ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_19
)
{
	.reg .pred 	%p<36>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<89>;

	ld.param.b64 	%rd17, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_4];
	ld.param.b64 	%rd18, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_7];
	ld.param.b64 	%rd19, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_8];
	ld.param.b32 	%r6, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_18];
	ld.param.b32 	%r7, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_19];
	mov.u32 	%r8, %tid.x;
	cvt.u64.u32 	%rd20, %r8;
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mul.wide.u32 	%rd21, %r9, %r10;
	add.s64 	%rd1, %rd21, %rd20;
	mov.u32 	%r11, %tid.y;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mad.lo.s32 	%r14, %r12, %r13, %r11;
	cvt.u64.u32 	%rd2, %r14;
	cvt.s64.s32 	%rd22, %r7;
	setp.lt.s64 	%p1, %rd1, %rd22;
	setp.lt.s32 	%p2, %r14, %r7;
	and.pred 	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_2;
$L__BB0_1:
	ret;
$L__BB0_2:
	mul.lo.s64 	%rd23, %rd19, %rd1;
	mad.lo.s64 	%rd24, %rd18, %rd2, %rd17;
	add.s64 	%rd25, %rd24, %rd23;
	ld.b32 	%r21, [%rd25];
	cvt.u64.u32 	%rd3, %r7;
	add.s64 	%rd4, %rd3, %rd2;
	add.s64 	%rd5, %rd23, %rd17;
	mad.lo.s64 	%rd26, %rd4, %rd18, %rd5;
	ld.b32 	%r20, [%rd26];
	setp.eq.b32 	%p4, %r21, -1;
	setp.eq.b32 	%p5, %r20, -1;
	or.pred 	%p6, %p4, %p5;
	mov.b64 	%rd87, 9223372036854775807;
	@%p6 bra 	$L__BB0_4;
	cvt.s64.s32 	%rd27, %r21;
	sub.s64 	%rd28, %rd1, %rd27;
	cvt.s64.s32 	%rd29, %r20;
	sub.s64 	%rd30, %rd2, %rd29;
	mul.lo.s64 	%rd31, %rd28, %rd28;
	mad.lo.s64 	%rd87, %rd30, %rd30, %rd31;
$L__BB0_4:
	cvt.s64.s32 	%rd6, %r6;
	sub.s64 	%rd7, %rd1, %rd6;
	mul.lo.s64 	%rd8, %rd7, %rd19;
	add.s64 	%rd9, %rd1, %rd6;
	mul.lo.s64 	%rd10, %rd9, %rd19;
	mov.b64 	%rd11, 0;
$L__BB0_5:
	mov.b64 	%rd88, -1;
	mov.pred 	%p35, 0;
	setp.eq.b64 	%p7, %rd11, 2;
	@%p7 bra 	$L__BB0_26;
	setp.eq.b64 	%p8, %rd11, 1;
	@%p8 bra 	$L__BB0_25;
$L__BB0_7:
	add.s64 	%rd11, %rd11, 1;
	mul.lo.s64 	%rd32, %rd88, %rd6;
	add.s64 	%rd12, %rd32, %rd2;
	mul.lo.s64 	%rd13, %rd12, %rd18;
	add.s64 	%rd14, %rd13, %rd17;
	add.s64 	%rd33, %rd4, %rd32;
	mul.lo.s64 	%rd15, %rd33, %rd18;
	add.s64 	%rd16, %rd15, %rd17;
	@%p35 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_14;
$L__BB0_8:
	max.u64 	%rd61, %rd7, %rd12;
	setp.lt.u64 	%p24, %rd61, %rd3;
	@%p24 bra 	$L__BB0_9;
	bra.uni 	$L__BB0_11;
$L__BB0_9:
	add.s64 	%rd62, %rd14, %rd8;
	ld.b32 	%r1, [%rd62];
	add.s64 	%rd63, %rd16, %rd8;
	ld.b32 	%r18, [%rd63];
	setp.eq.b32 	%p25, %r1, -1;
	setp.eq.b32 	%p26, %r18, -1;
	or.pred 	%p27, %p25, %p26;
	@%p27 bra 	$L__BB0_11;
	cvt.s64.s32 	%rd64, %r1;
	cvt.s64.s32 	%rd65, %r18;
	sub.s64 	%rd66, %rd1, %rd64;
	sub.s64 	%rd67, %rd2, %rd65;
	mul.lo.s64 	%rd68, %rd66, %rd66;
	mad.lo.s64 	%rd69, %rd67, %rd67, %rd68;
	setp.lt.s64 	%p28, %rd69, %rd87;
	min.s64 	%rd87, %rd69, %rd87;
	selp.b32 	%r20, %r18, %r20, %p28;
	selp.b32 	%r21, %r1, %r21, %p28;
$L__BB0_11:
	max.u64 	%rd70, %rd9, %rd12;
	setp.ge.u64 	%p29, %rd70, %rd3;
	@%p29 bra 	$L__BB0_23;
	add.s64 	%rd71, %rd14, %rd10;
	ld.b32 	%r2, [%rd71];
	add.s64 	%rd72, %rd16, %rd10;
	ld.b32 	%r19, [%rd72];
	setp.eq.b32 	%p30, %r2, -1;
	setp.eq.b32 	%p31, %r19, -1;
	or.pred 	%p32, %p30, %p31;
	@%p32 bra 	$L__BB0_23;
	cvt.s64.s32 	%rd73, %r2;
	cvt.s64.s32 	%rd74, %r19;
	sub.s64 	%rd75, %rd1, %rd73;
	sub.s64 	%rd76, %rd2, %rd74;
	mul.lo.s64 	%rd77, %rd75, %rd75;
	mad.lo.s64 	%rd78, %rd76, %rd76, %rd77;
	setp.lt.s64 	%p33, %rd78, %rd87;
	min.s64 	%rd87, %rd78, %rd87;
	selp.b32 	%r20, %r19, %r20, %p33;
	selp.b32 	%r21, %r2, %r21, %p33;
	bra.uni 	$L__BB0_23;
$L__BB0_14:
	max.u64 	%rd34, %rd7, %rd12;
	setp.ge.u64 	%p9, %rd34, %rd3;
	@%p9 bra 	$L__BB0_17;
	add.s64 	%rd35, %rd14, %rd8;
	ld.b32 	%r3, [%rd35];
	add.s64 	%rd36, %rd16, %rd8;
	ld.b32 	%r15, [%rd36];
	setp.eq.b32 	%p10, %r3, -1;
	setp.eq.b32 	%p11, %r15, -1;
	or.pred 	%p12, %p10, %p11;
	@%p12 bra 	$L__BB0_17;
	cvt.s64.s32 	%rd37, %r3;
	cvt.s64.s32 	%rd38, %r15;
	sub.s64 	%rd39, %rd1, %rd37;
	sub.s64 	%rd40, %rd2, %rd38;
	mul.lo.s64 	%rd41, %rd39, %rd39;
	mad.lo.s64 	%rd42, %rd40, %rd40, %rd41;
	setp.lt.s64 	%p13, %rd42, %rd87;
	min.s64 	%rd87, %rd42, %rd87;
	selp.b32 	%r20, %r15, %r20, %p13;
	selp.b32 	%r21, %r3, %r21, %p13;
$L__BB0_17:
	max.u64 	%rd43, %rd1, %rd12;
	setp.ge.u64 	%p14, %rd43, %rd3;
	@%p14 bra 	$L__BB0_20;
	add.s64 	%rd44, %rd5, %rd13;
	ld.b32 	%r4, [%rd44];
	add.s64 	%rd45, %rd5, %rd15;
	ld.b32 	%r16, [%rd45];
	setp.eq.b32 	%p15, %r4, -1;
	setp.eq.b32 	%p16, %r16, -1;
	or.pred 	%p17, %p15, %p16;
	@%p17 bra 	$L__BB0_20;
	cvt.s64.s32 	%rd46, %r4;
	cvt.s64.s32 	%rd47, %r16;
	sub.s64 	%rd48, %rd1, %rd46;
	sub.s64 	%rd49, %rd2, %rd47;
	mul.lo.s64 	%rd50, %rd48, %rd48;
	mad.lo.s64 	%rd51, %rd49, %rd49, %rd50;
	setp.lt.s64 	%p18, %rd51, %rd87;
	min.s64 	%rd87, %rd51, %rd87;
	selp.b32 	%r20, %r16, %r20, %p18;
	selp.b32 	%r21, %r4, %r21, %p18;
$L__BB0_20:
	max.u64 	%rd52, %rd9, %rd12;
	setp.ge.u64 	%p19, %rd52, %rd3;
	@%p19 bra 	$L__BB0_23;
	add.s64 	%rd53, %rd14, %rd10;
	ld.b32 	%r5, [%rd53];
	add.s64 	%rd54, %rd16, %rd10;
	ld.b32 	%r17, [%rd54];
	setp.eq.b32 	%p20, %r5, -1;
	setp.eq.b32 	%p21, %r17, -1;
	or.pred 	%p22, %p20, %p21;
	@%p22 bra 	$L__BB0_23;
	cvt.s64.s32 	%rd55, %r5;
	cvt.s64.s32 	%rd56, %r17;
	sub.s64 	%rd57, %rd1, %rd55;
	sub.s64 	%rd58, %rd2, %rd56;
	mul.lo.s64 	%rd59, %rd57, %rd57;
	mad.lo.s64 	%rd60, %rd58, %rd58, %rd59;
	setp.lt.s64 	%p23, %rd60, %rd87;
	min.s64 	%rd87, %rd60, %rd87;
	selp.b32 	%r20, %r17, %r20, %p23;
	selp.b32 	%r21, %r5, %r21, %p23;
$L__BB0_23:
	setp.eq.b64 	%p34, %rd11, 3;
	@%p34 bra 	$L__BB0_24;
	bra.uni 	$L__BB0_5;
$L__BB0_24:
	ld.param.b64 	%rd86, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_17];
	ld.param.b64 	%rd85, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_16];
	ld.param.b64 	%rd84, [_ZN6task6b37_jfa_pass_SoA_square_euclidean_kernelB3v86B114cw51cXTLSUwv1sDUaKthaKSjYKCpo4BIW7AwQwoOW3BI6ygAjbQFJT1g0KOlAiRhSIJDEkBNRDAJJE_2fZVqvDglrdSgFqvTpQEsgzrtUEAA_3d_3dE5ArrayIiLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedEii_param_13];
	mul.lo.s64 	%rd79, %rd86, %rd1;
	mad.lo.s64 	%rd80, %rd85, %rd2, %rd84;
	add.s64 	%rd81, %rd80, %rd79;
	st.b32 	[%rd81], %r21;
	add.s64 	%rd82, %rd79, %rd84;
	mad.lo.s64 	%rd83, %rd4, %rd85, %rd82;
	st.b32 	[%rd83], %r20;
	bra.uni 	$L__BB0_1;
$L__BB0_25:
	mov.b64 	%rd88, 0;
	mov.pred 	%p35, -1;
	bra.uni 	$L__BB0_7;
$L__BB0_26:
	mov.b64 	%rd88, 1;
	bra.uni 	$L__BB0_7;

}