//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-36037853
// Cuda compilation tools, release 12.9, V12.9.86
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_75
.address_size 64

	// .globl	_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE
.common .global .align 8 .u64 _ZN08NumbaEnv5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE;
.visible .shared .align 4 .b8 _cudapy_smem_1[64];

.visible .entry _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE(
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_0,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_1,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_2,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_3,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_9,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_10,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_11,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_12,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16,
	.param .u64 _ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17
)
{
	.reg .pred 	%p<36>;
	.reg .f32 	%f<163>;
	.reg .b32 	%r<69>;
	.reg .b64 	%rd<102>;


	ld.param.u64 	%rd16, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_4];
	ld.param.u64 	%rd17, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_5];
	ld.param.u64 	%rd18, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_6];
	ld.param.u64 	%rd19, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_7];
	ld.param.u64 	%rd20, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_8];
	ld.param.u64 	%rd22, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd23, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	mov.u32 	%r4, %tid.x;
	cvt.s64.s32 	%rd26, %r4;
	mov.u32 	%r5, %ntid.x;
	mov.u32 	%r6, %ctaid.x;
	mul.wide.s32 	%rd27, %r5, %r6;
	add.s64 	%rd1, %rd27, %rd26;
	mov.u32 	%r7, %tid.y;
	cvt.s64.s32 	%rd28, %r7;
	mov.u32 	%r8, %ntid.y;
	mov.u32 	%r9, %ctaid.y;
	mul.wide.s32 	%rd29, %r8, %r9;
	add.s64 	%rd2, %rd29, %rd28;
	mul.wide.s32 	%rd30, %r7, %r5;
	add.s64 	%rd31, %rd30, %rd26;
	shr.u64 	%rd32, %rd31, 63;
	add.s64 	%rd33, %rd31, %rd32;
	shr.s64 	%rd34, %rd33, 1;
	and.b64  	%rd35, %rd33, -2;
	sub.s64 	%rd3, %rd31, %rd35;
	shr.s64 	%rd36, %rd3, 63;
	add.s64 	%rd4, %rd36, %rd34;
	and.b64  	%rd37, %rd17, 7;
	setp.ne.s64 	%p2, %rd37, 0;
	selp.u64 	%rd38, 1, 0, %p2;
	shr.u64 	%rd39, %rd17, 3;
	add.s64 	%rd40, %rd39, %rd38;
	setp.gt.s64 	%p3, %rd17, 0;
	selp.b64 	%rd5, %rd40, 0, %p3;
	setp.ne.s64 	%p1, %rd5, 0;
	setp.eq.s64 	%p4, %rd5, 0;
	mov.u32 	%r68, 0;
	@%p4 bra 	$L__BB0_8;

	cvt.rn.f32.s64 	%f6, %rd22;
	cvt.rn.f32.s64 	%f7, %rd1;
	div.rn.f32 	%f1, %f7, %f6;
	cvt.rn.f32.s64 	%f8, %rd23;
	cvt.rn.f32.s64 	%f9, %rd2;
	div.rn.f32 	%f2, %f9, %f8;
	add.s64 	%rd43, %rd3, 2;
	setp.lt.s64 	%p5, %rd3, 0;
	mov.u64 	%rd100, 0;
	selp.b64 	%rd44, %rd43, %rd3, %p5;
	shr.s64 	%rd45, %rd44, 63;
	and.b64  	%rd46, %rd45, %rd18;
	add.s64 	%rd47, %rd46, %rd44;
	mul.lo.s64 	%rd48, %rd47, %rd20;
	add.s64 	%rd6, %rd48, %rd16;
	and.b64  	%rd49, %rd4, -9223372036854775808;
	shr.u64 	%rd50, %rd49, 60;
	add.s64 	%rd51, %rd50, %rd4;
	and.b64  	%rd52, %rd44, -9223372036854775808;
	shr.u64 	%rd53, %rd52, 62;
	add.s64 	%rd54, %rd53, %rd44;
	shl.b64 	%rd55, %rd51, 1;
	add.s64 	%rd56, %rd54, %rd55;
	shl.b64 	%rd57, %rd56, 2;
	mov.u64 	%rd58, _cudapy_smem_1;
	add.s64 	%rd7, %rd58, %rd57;
	selp.s64 	%rd59, -1, 0, %p1;
	add.s64 	%rd99, %rd5, %rd59;
	mov.f32 	%f162, 0f7F800000;
	mov.u64 	%rd101, %rd100;

$L__BB0_2:
	mov.u64 	%rd9, %rd99;
	setp.gt.s64 	%p6, %rd4, 7;
	@%p6 bra 	$L__BB0_6;

	add.s64 	%rd12, %rd4, %rd100;
	setp.lt.s64 	%p7, %rd12, %rd17;
	@%p7 bra 	$L__BB0_5;
	bra.uni 	$L__BB0_4;

$L__BB0_5:
	shr.s64 	%rd60, %rd12, 63;
	and.b64  	%rd61, %rd60, %rd17;
	add.s64 	%rd62, %rd4, %rd61;
	add.s64 	%rd63, %rd62, %rd100;
	mul.lo.s64 	%rd64, %rd63, %rd19;
	add.s64 	%rd65, %rd6, %rd64;
	ld.f32 	%f10, [%rd65];
	st.shared.f32 	[%rd7], %f10;
	bra.uni 	$L__BB0_6;

$L__BB0_4:
	mov.u32 	%r10, 2139095040;
	st.shared.u32 	[%rd7], %r10;

$L__BB0_6:
	bar.sync 	0;
	ld.shared.f32 	%f11, [_cudapy_smem_1];
	sub.f32 	%f12, %f1, %f11;
	cvta.shared.u64 	%rd67, %rd58;
	ld.f32 	%f13, [%rd67+4];
	sub.f32 	%f14, %f2, %f13;
	abs.f32 	%f15, %f12;
	abs.f32 	%f16, %f14;
	mov.b32 	%r11, %f16;
	mov.b32 	%r12, %f15;
	min.s32 	%r13, %r11, %r12;
	mov.b32 	%f17, %r13;
	max.s32 	%r14, %r11, %r12;
	mov.b32 	%f18, %r14;
	and.b32  	%r15, %r14, -33554432;
	mov.u32 	%r16, 2122317824;
	sub.s32 	%r17, %r16, %r15;
	mov.b32 	%f19, %r17;
	mul.f32 	%f20, %f17, %f19;
	mul.f32 	%f21, %f18, %f19;
	mul.f32 	%f22, %f20, %f20;
	fma.rn.f32 	%f23, %f21, %f21, %f22;
	sqrt.rn.f32 	%f24, %f23;
	or.b32  	%r18, %r15, 8388608;
	mov.b32 	%f25, %r18;
	mul.f32 	%f26, %f24, %f25;
	setp.eq.f32 	%p8, %f17, 0f00000000;
	selp.f32 	%f27, %f18, %f26, %p8;
	setp.eq.f32 	%p9, %f17, 0f7F800000;
	selp.f32 	%f28, 0f7F800000, %f27, %p9;
	setp.lt.f32 	%p10, %f28, %f162;
	selp.b64 	%rd68, %rd100, %rd101, %p10;
	selp.f32 	%f29, %f28, %f162, %p10;
	ld.shared.f32 	%f30, [_cudapy_smem_1+8];
	sub.f32 	%f31, %f1, %f30;
	ld.f32 	%f32, [%rd67+12];
	sub.f32 	%f33, %f2, %f32;
	abs.f32 	%f34, %f31;
	abs.f32 	%f35, %f33;
	mov.b32 	%r19, %f35;
	mov.b32 	%r20, %f34;
	min.s32 	%r21, %r19, %r20;
	mov.b32 	%f36, %r21;
	max.s32 	%r22, %r19, %r20;
	mov.b32 	%f37, %r22;
	and.b32  	%r23, %r22, -33554432;
	sub.s32 	%r24, %r16, %r23;
	mov.b32 	%f38, %r24;
	mul.f32 	%f39, %f36, %f38;
	mul.f32 	%f40, %f37, %f38;
	mul.f32 	%f41, %f39, %f39;
	fma.rn.f32 	%f42, %f40, %f40, %f41;
	sqrt.rn.f32 	%f43, %f42;
	or.b32  	%r25, %r23, 8388608;
	mov.b32 	%f44, %r25;
	mul.f32 	%f45, %f43, %f44;
	setp.eq.f32 	%p11, %f36, 0f00000000;
	selp.f32 	%f46, %f37, %f45, %p11;
	setp.eq.f32 	%p12, %f36, 0f7F800000;
	selp.f32 	%f47, 0f7F800000, %f46, %p12;
	setp.lt.f32 	%p13, %f47, %f29;
	add.s64 	%rd69, %rd100, 1;
	selp.b64 	%rd70, %rd69, %rd68, %p13;
	selp.f32 	%f48, %f47, %f29, %p13;
	ld.shared.f32 	%f49, [_cudapy_smem_1+16];
	sub.f32 	%f50, %f1, %f49;
	ld.f32 	%f51, [%rd67+20];
	sub.f32 	%f52, %f2, %f51;
	abs.f32 	%f53, %f50;
	abs.f32 	%f54, %f52;
	mov.b32 	%r26, %f54;
	mov.b32 	%r27, %f53;
	min.s32 	%r28, %r26, %r27;
	mov.b32 	%f55, %r28;
	max.s32 	%r29, %r26, %r27;
	mov.b32 	%f56, %r29;
	and.b32  	%r30, %r29, -33554432;
	sub.s32 	%r31, %r16, %r30;
	mov.b32 	%f57, %r31;
	mul.f32 	%f58, %f55, %f57;
	mul.f32 	%f59, %f56, %f57;
	mul.f32 	%f60, %f58, %f58;
	fma.rn.f32 	%f61, %f59, %f59, %f60;
	sqrt.rn.f32 	%f62, %f61;
	or.b32  	%r32, %r30, 8388608;
	mov.b32 	%f63, %r32;
	mul.f32 	%f64, %f62, %f63;
	setp.eq.f32 	%p14, %f55, 0f00000000;
	selp.f32 	%f65, %f56, %f64, %p14;
	setp.eq.f32 	%p15, %f55, 0f7F800000;
	selp.f32 	%f66, 0f7F800000, %f65, %p15;
	setp.lt.f32 	%p16, %f66, %f48;
	add.s64 	%rd71, %rd100, 2;
	selp.b64 	%rd72, %rd71, %rd70, %p16;
	selp.f32 	%f67, %f66, %f48, %p16;
	ld.shared.f32 	%f68, [_cudapy_smem_1+24];
	sub.f32 	%f69, %f1, %f68;
	ld.f32 	%f70, [%rd67+28];
	sub.f32 	%f71, %f2, %f70;
	abs.f32 	%f72, %f69;
	abs.f32 	%f73, %f71;
	mov.b32 	%r33, %f73;
	mov.b32 	%r34, %f72;
	min.s32 	%r35, %r33, %r34;
	mov.b32 	%f74, %r35;
	max.s32 	%r36, %r33, %r34;
	mov.b32 	%f75, %r36;
	and.b32  	%r37, %r36, -33554432;
	sub.s32 	%r38, %r16, %r37;
	mov.b32 	%f76, %r38;
	mul.f32 	%f77, %f74, %f76;
	mul.f32 	%f78, %f75, %f76;
	mul.f32 	%f79, %f77, %f77;
	fma.rn.f32 	%f80, %f78, %f78, %f79;
	sqrt.rn.f32 	%f81, %f80;
	or.b32  	%r39, %r37, 8388608;
	mov.b32 	%f82, %r39;
	mul.f32 	%f83, %f81, %f82;
	setp.eq.f32 	%p17, %f74, 0f00000000;
	selp.f32 	%f84, %f75, %f83, %p17;
	setp.eq.f32 	%p18, %f74, 0f7F800000;
	selp.f32 	%f85, 0f7F800000, %f84, %p18;
	setp.lt.f32 	%p19, %f85, %f67;
	add.s64 	%rd73, %rd100, 3;
	selp.b64 	%rd74, %rd73, %rd72, %p19;
	selp.f32 	%f86, %f85, %f67, %p19;
	ld.shared.f32 	%f87, [_cudapy_smem_1+32];
	sub.f32 	%f88, %f1, %f87;
	ld.f32 	%f89, [%rd67+36];
	sub.f32 	%f90, %f2, %f89;
	abs.f32 	%f91, %f88;
	abs.f32 	%f92, %f90;
	mov.b32 	%r40, %f92;
	mov.b32 	%r41, %f91;
	min.s32 	%r42, %r40, %r41;
	mov.b32 	%f93, %r42;
	max.s32 	%r43, %r40, %r41;
	mov.b32 	%f94, %r43;
	and.b32  	%r44, %r43, -33554432;
	sub.s32 	%r45, %r16, %r44;
	mov.b32 	%f95, %r45;
	mul.f32 	%f96, %f93, %f95;
	mul.f32 	%f97, %f94, %f95;
	mul.f32 	%f98, %f96, %f96;
	fma.rn.f32 	%f99, %f97, %f97, %f98;
	sqrt.rn.f32 	%f100, %f99;
	or.b32  	%r46, %r44, 8388608;
	mov.b32 	%f101, %r46;
	mul.f32 	%f102, %f100, %f101;
	setp.eq.f32 	%p20, %f93, 0f00000000;
	selp.f32 	%f103, %f94, %f102, %p20;
	setp.eq.f32 	%p21, %f93, 0f7F800000;
	selp.f32 	%f104, 0f7F800000, %f103, %p21;
	setp.lt.f32 	%p22, %f104, %f86;
	add.s64 	%rd75, %rd100, 4;
	selp.b64 	%rd76, %rd75, %rd74, %p22;
	selp.f32 	%f105, %f104, %f86, %p22;
	ld.shared.f32 	%f106, [_cudapy_smem_1+40];
	sub.f32 	%f107, %f1, %f106;
	ld.f32 	%f108, [%rd67+44];
	sub.f32 	%f109, %f2, %f108;
	abs.f32 	%f110, %f107;
	abs.f32 	%f111, %f109;
	mov.b32 	%r47, %f111;
	mov.b32 	%r48, %f110;
	min.s32 	%r49, %r47, %r48;
	mov.b32 	%f112, %r49;
	max.s32 	%r50, %r47, %r48;
	mov.b32 	%f113, %r50;
	and.b32  	%r51, %r50, -33554432;
	sub.s32 	%r52, %r16, %r51;
	mov.b32 	%f114, %r52;
	mul.f32 	%f115, %f112, %f114;
	mul.f32 	%f116, %f113, %f114;
	mul.f32 	%f117, %f115, %f115;
	fma.rn.f32 	%f118, %f116, %f116, %f117;
	sqrt.rn.f32 	%f119, %f118;
	or.b32  	%r53, %r51, 8388608;
	mov.b32 	%f120, %r53;
	mul.f32 	%f121, %f119, %f120;
	setp.eq.f32 	%p23, %f112, 0f00000000;
	selp.f32 	%f122, %f113, %f121, %p23;
	setp.eq.f32 	%p24, %f112, 0f7F800000;
	selp.f32 	%f123, 0f7F800000, %f122, %p24;
	setp.lt.f32 	%p25, %f123, %f105;
	add.s64 	%rd77, %rd100, 5;
	selp.b64 	%rd78, %rd77, %rd76, %p25;
	selp.f32 	%f124, %f123, %f105, %p25;
	ld.shared.f32 	%f125, [_cudapy_smem_1+48];
	sub.f32 	%f126, %f1, %f125;
	ld.f32 	%f127, [%rd67+52];
	sub.f32 	%f128, %f2, %f127;
	abs.f32 	%f129, %f126;
	abs.f32 	%f130, %f128;
	mov.b32 	%r54, %f130;
	mov.b32 	%r55, %f129;
	min.s32 	%r56, %r54, %r55;
	mov.b32 	%f131, %r56;
	max.s32 	%r57, %r54, %r55;
	mov.b32 	%f132, %r57;
	and.b32  	%r58, %r57, -33554432;
	sub.s32 	%r59, %r16, %r58;
	mov.b32 	%f133, %r59;
	mul.f32 	%f134, %f131, %f133;
	mul.f32 	%f135, %f132, %f133;
	mul.f32 	%f136, %f134, %f134;
	fma.rn.f32 	%f137, %f135, %f135, %f136;
	sqrt.rn.f32 	%f138, %f137;
	or.b32  	%r60, %r58, 8388608;
	mov.b32 	%f139, %r60;
	mul.f32 	%f140, %f138, %f139;
	setp.eq.f32 	%p26, %f131, 0f00000000;
	selp.f32 	%f141, %f132, %f140, %p26;
	setp.eq.f32 	%p27, %f131, 0f7F800000;
	selp.f32 	%f142, 0f7F800000, %f141, %p27;
	setp.lt.f32 	%p28, %f142, %f124;
	add.s64 	%rd79, %rd100, 6;
	selp.b64 	%rd80, %rd79, %rd78, %p28;
	selp.f32 	%f143, %f142, %f124, %p28;
	ld.shared.f32 	%f144, [_cudapy_smem_1+56];
	sub.f32 	%f145, %f1, %f144;
	ld.f32 	%f146, [%rd67+60];
	sub.f32 	%f147, %f2, %f146;
	abs.f32 	%f148, %f145;
	abs.f32 	%f149, %f147;
	mov.b32 	%r61, %f149;
	mov.b32 	%r62, %f148;
	min.s32 	%r63, %r61, %r62;
	mov.b32 	%f150, %r63;
	max.s32 	%r64, %r61, %r62;
	mov.b32 	%f151, %r64;
	and.b32  	%r65, %r64, -33554432;
	sub.s32 	%r66, %r16, %r65;
	mov.b32 	%f152, %r66;
	mul.f32 	%f153, %f150, %f152;
	mul.f32 	%f154, %f151, %f152;
	mul.f32 	%f155, %f153, %f153;
	fma.rn.f32 	%f156, %f154, %f154, %f155;
	sqrt.rn.f32 	%f157, %f156;
	or.b32  	%r67, %r65, 8388608;
	mov.b32 	%f158, %r67;
	mul.f32 	%f159, %f157, %f158;
	setp.eq.f32 	%p29, %f150, 0f00000000;
	selp.f32 	%f160, %f151, %f159, %p29;
	setp.eq.f32 	%p30, %f150, 0f7F800000;
	selp.f32 	%f161, 0f7F800000, %f160, %p30;
	setp.lt.f32 	%p31, %f161, %f143;
	add.s64 	%rd81, %rd100, 7;
	selp.b64 	%rd101, %rd81, %rd80, %p31;
	selp.f32 	%f162, %f161, %f143, %p31;
	bar.sync 	0;
	add.s64 	%rd99, %rd9, -1;
	add.s64 	%rd100, %rd100, 8;
	setp.gt.s64 	%p32, %rd9, 0;
	@%p32 bra 	$L__BB0_2;

	cvt.u32.u64 	%r68, %rd101;

$L__BB0_8:
	ld.param.u64 	%rd97, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd92, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	setp.ge.s64 	%p33, %rd2, %rd92;
	setp.ge.s64 	%p34, %rd1, %rd97;
	or.pred  	%p35, %p34, %p33;
	@%p35 bra 	$L__BB0_10;

	ld.param.u64 	%rd98, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_14];
	ld.param.u64 	%rd96, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_13];
	ld.param.u64 	%rd95, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_17];
	ld.param.u64 	%rd94, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_16];
	ld.param.u64 	%rd93, [_ZN5task542_voroni_euclidean_hypot_grid_stride_kernelB3v53B104cw51cXTLSUwv1sDUaKthrqNgqqmjgEhasCBDCg1bcEDrKABNtAWlPGDIoyUCJGFIekMSQE1DMAkkP9lWq8NCWt1KAWq9OlASyDOu1QQAE5ArrayIfLi2E1A7mutable7alignedE5ArrayIiLi2E1A7mutable7alignedE_param_15];
	shr.s64 	%rd82, %rd1, 63;
	and.b64  	%rd83, %rd82, %rd98;
	add.s64 	%rd84, %rd83, %rd1;
	shr.s64 	%rd85, %rd2, 63;
	and.b64  	%rd86, %rd85, %rd93;
	add.s64 	%rd87, %rd86, %rd2;
	mul.lo.s64 	%rd88, %rd84, %rd94;
	mul.lo.s64 	%rd89, %rd87, %rd95;
	add.s64 	%rd90, %rd88, %rd96;
	add.s64 	%rd91, %rd90, %rd89;
	st.u32 	[%rd91], %r68;

$L__BB0_10:
	ret;

}